// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: alerts.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const claimDueAlertRules = `-- name: ClaimDueAlertRules :many
UPDATE alert_rules
SET last_evaluated_at = now()
WHERE enabled = true
  AND (last_evaluated_at IS NULL
       OR now() - last_evaluated_at >= make_interval(secs => evaluation_interval_seconds))
RETURNING id, uuid, name, description, source, params, severity, enabled, evaluation_interval_seconds, for_seconds, repeat_interval_seconds, last_evaluated_at, created_at, updated_at
`

func (q *Queries) ClaimDueAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.QueryContext(ctx, claimDueAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.Source,
			&i.Params,
			&i.Severity,
			&i.Enabled,
			&i.EvaluationIntervalSeconds,
			&i.ForSeconds,
			&i.RepeatIntervalSeconds,
			&i.LastEvaluatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (
    name, description, source, params, severity, enabled,
    evaluation_interval_seconds, for_seconds, repeat_interval_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, uuid, name, description, source, params, severity, enabled, evaluation_interval_seconds, for_seconds, repeat_interval_seconds, last_evaluated_at, created_at, updated_at
`

type CreateAlertRuleParams struct {
	Name                      string          `db:"name" json:"name"`
	Description               string          `db:"description" json:"description"`
	Source                    string          `db:"source" json:"source"`
	Params                    json.RawMessage `db:"params" json:"params"`
	Severity                  string          `db:"severity" json:"severity"`
	Enabled                   bool            `db:"enabled" json:"enabled"`
	EvaluationIntervalSeconds int32           `db:"evaluation_interval_seconds" json:"evaluation_interval_seconds"`
	ForSeconds                int32           `db:"for_seconds" json:"for_seconds"`
	RepeatIntervalSeconds     int32           `db:"repeat_interval_seconds" json:"repeat_interval_seconds"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, createAlertRule,
		arg.Name,
		arg.Description,
		arg.Source,
		arg.Params,
		arg.Severity,
		arg.Enabled,
		arg.EvaluationIntervalSeconds,
		arg.ForSeconds,
		arg.RepeatIntervalSeconds,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Params,
		&i.Severity,
		&i.Enabled,
		&i.EvaluationIntervalSeconds,
		&i.ForSeconds,
		&i.RepeatIntervalSeconds,
		&i.LastEvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAlertRuleTarget = `-- name: CreateAlertRuleTarget :exec
INSERT INTO alert_rule_targets (rule_id, target_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateAlertRuleTargetParams struct {
	RuleID   int64 `db:"rule_id" json:"rule_id"`
	TargetID int64 `db:"target_id" json:"target_id"`
}

func (q *Queries) CreateAlertRuleTarget(ctx context.Context, arg CreateAlertRuleTargetParams) error {
	_, err := q.db.ExecContext(ctx, createAlertRuleTarget, arg.RuleID, arg.TargetID)
	return err
}

const createAlertTarget = `-- name: CreateAlertTarget :one
INSERT INTO alert_targets (name, type, config, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, name, type, config, enabled, created_at, updated_at
`

type CreateAlertTargetParams struct {
	Name    string          `db:"name" json:"name"`
	Type    string          `db:"type" json:"type"`
	Config  json.RawMessage `db:"config" json:"config"`
	Enabled bool            `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateAlertTarget(ctx context.Context, arg CreateAlertTargetParams) (AlertTarget, error) {
	row := q.db.QueryRowContext(ctx, createAlertTarget,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Enabled,
	)
	var i AlertTarget
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertRuleByUUID = `-- name: DeleteAlertRuleByUUID :execrows
DELETE FROM alert_rules WHERE uuid = $1
`

func (q *Queries) DeleteAlertRuleByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlertRuleByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAlertRuleTargetsForRule = `-- name: DeleteAlertRuleTargetsForRule :exec
DELETE FROM alert_rule_targets WHERE rule_id = $1
`

func (q *Queries) DeleteAlertRuleTargetsForRule(ctx context.Context, ruleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlertRuleTargetsForRule, ruleID)
	return err
}

const deleteAlertState = `-- name: DeleteAlertState :exec
DELETE FROM alert_state WHERE rule_id = $1 AND alert_key = $2
`

type DeleteAlertStateParams struct {
	RuleID   int64  `db:"rule_id" json:"rule_id"`
	AlertKey string `db:"alert_key" json:"alert_key"`
}

func (q *Queries) DeleteAlertState(ctx context.Context, arg DeleteAlertStateParams) error {
	_, err := q.db.ExecContext(ctx, deleteAlertState, arg.RuleID, arg.AlertKey)
	return err
}

const deleteAlertTargetByUUID = `-- name: DeleteAlertTargetByUUID :execrows
DELETE FROM alert_targets WHERE uuid = $1
`

func (q *Queries) DeleteAlertTargetByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlertTargetByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAlertRuleByName = `-- name: GetAlertRuleByName :one
SELECT id, uuid, name, description, source, params, severity, enabled, evaluation_interval_seconds, for_seconds, repeat_interval_seconds, last_evaluated_at, created_at, updated_at FROM alert_rules WHERE name = $1
`

func (q *Queries) GetAlertRuleByName(ctx context.Context, name string) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, getAlertRuleByName, name)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Params,
		&i.Severity,
		&i.Enabled,
		&i.EvaluationIntervalSeconds,
		&i.ForSeconds,
		&i.RepeatIntervalSeconds,
		&i.LastEvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertRuleByUUID = `-- name: GetAlertRuleByUUID :one
SELECT id, uuid, name, description, source, params, severity, enabled, evaluation_interval_seconds, for_seconds, repeat_interval_seconds, last_evaluated_at, created_at, updated_at FROM alert_rules WHERE uuid = $1
`

func (q *Queries) GetAlertRuleByUUID(ctx context.Context, argUuid uuid.UUID) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, getAlertRuleByUUID, argUuid)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Params,
		&i.Severity,
		&i.Enabled,
		&i.EvaluationIntervalSeconds,
		&i.ForSeconds,
		&i.RepeatIntervalSeconds,
		&i.LastEvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertTargetByName = `-- name: GetAlertTargetByName :one
SELECT id, uuid, name, type, config, enabled, created_at, updated_at FROM alert_targets WHERE name = $1
`

func (q *Queries) GetAlertTargetByName(ctx context.Context, name string) (AlertTarget, error) {
	row := q.db.QueryRowContext(ctx, getAlertTargetByName, name)
	var i AlertTarget
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertTargetByUUID = `-- name: GetAlertTargetByUUID :one
SELECT id, uuid, name, type, config, enabled, created_at, updated_at FROM alert_targets WHERE uuid = $1
`

func (q *Queries) GetAlertTargetByUUID(ctx context.Context, argUuid uuid.UUID) (AlertTarget, error) {
	row := q.db.QueryRowContext(ctx, getAlertTargetByUUID, argUuid)
	var i AlertTarget
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeOwnerLabels = `-- name: GetNodeOwnerLabels :one
SELECT o.email, o.external_id, o.display_name
FROM node_inventory ni
JOIN device_owners o ON o.id = ni.owner_id
WHERE ni.node_id = $1
`

type GetNodeOwnerLabelsRow struct {
	Email       string `db:"email" json:"email"`
	ExternalID  string `db:"external_id" json:"external_id"`
	DisplayName string `db:"display_name" json:"display_name"`
}

func (q *Queries) GetNodeOwnerLabels(ctx context.Context, nodeID int64) (GetNodeOwnerLabelsRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeOwnerLabels, nodeID)
	var i GetNodeOwnerLabelsRow
	err := row.Scan(&i.Email, &i.ExternalID, &i.DisplayName)
	return i, err
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, uuid, name, description, source, params, severity, enabled, evaluation_interval_seconds, for_seconds, repeat_interval_seconds, last_evaluated_at, created_at, updated_at, count(*) OVER () AS total_count
FROM alert_rules
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAlertRulesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAlertRulesRow struct {
	ID                        int64           `db:"id" json:"id"`
	Uuid                      uuid.UUID       `db:"uuid" json:"uuid"`
	Name                      string          `db:"name" json:"name"`
	Description               string          `db:"description" json:"description"`
	Source                    string          `db:"source" json:"source"`
	Params                    json.RawMessage `db:"params" json:"params"`
	Severity                  string          `db:"severity" json:"severity"`
	Enabled                   bool            `db:"enabled" json:"enabled"`
	EvaluationIntervalSeconds int32           `db:"evaluation_interval_seconds" json:"evaluation_interval_seconds"`
	ForSeconds                int32           `db:"for_seconds" json:"for_seconds"`
	RepeatIntervalSeconds     int32           `db:"repeat_interval_seconds" json:"repeat_interval_seconds"`
	LastEvaluatedAt           sql.NullTime    `db:"last_evaluated_at" json:"last_evaluated_at"`
	CreatedAt                 time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time       `db:"updated_at" json:"updated_at"`
	TotalCount                int64           `db:"total_count" json:"total_count"`
}

func (q *Queries) ListAlertRules(ctx context.Context, arg ListAlertRulesParams) ([]ListAlertRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertRules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertRulesRow
	for rows.Next() {
		var i ListAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.Source,
			&i.Params,
			&i.Severity,
			&i.Enabled,
			&i.EvaluationIntervalSeconds,
			&i.ForSeconds,
			&i.RepeatIntervalSeconds,
			&i.LastEvaluatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertStateByRule = `-- name: ListAlertStateByRule :many
SELECT rule_id, alert_key, status, labels, annotations, first_seen_at, last_seen_at, last_notified_at FROM alert_state WHERE rule_id = $1
`

func (q *Queries) ListAlertStateByRule(ctx context.Context, ruleID int64) ([]AlertState, error) {
	rows, err := q.db.QueryContext(ctx, listAlertStateByRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertState
	for rows.Next() {
		var i AlertState
		if err := rows.Scan(
			&i.RuleID,
			&i.AlertKey,
			&i.Status,
			&i.Labels,
			&i.Annotations,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertTargets = `-- name: ListAlertTargets :many
SELECT id, uuid, name, type, config, enabled, created_at, updated_at, count(*) OVER () AS total_count
FROM alert_targets
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAlertTargetsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAlertTargetsRow struct {
	ID         int64           `db:"id" json:"id"`
	Uuid       uuid.UUID       `db:"uuid" json:"uuid"`
	Name       string          `db:"name" json:"name"`
	Type       string          `db:"type" json:"type"`
	Config     json.RawMessage `db:"config" json:"config"`
	Enabled    bool            `db:"enabled" json:"enabled"`
	CreatedAt  time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time       `db:"updated_at" json:"updated_at"`
	TotalCount int64           `db:"total_count" json:"total_count"`
}

func (q *Queries) ListAlertTargets(ctx context.Context, arg ListAlertTargetsParams) ([]ListAlertTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertTargets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertTargetsRow
	for rows.Next() {
		var i ListAlertTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailingPolicyNodes = `-- name: ListFailingPolicyNodes :many
SELECT
    p.uuid AS policy_uuid,
    p.name AS policy_name,
    p.resolution AS resolution,
    p.severity AS severity,
    n.id AS node_id,
    n.uuid AS node_uuid,
    COALESCE(NULLIF(n.display_name, ''), n.hostname) AS hostname,
    n.platform AS platform,
    COALESCE((
        SELECT string_agg(g.name, ',' ORDER BY g.name)
        FROM group_membership gm
        JOIN groups g ON g.id = gm.group_id
        WHERE gm.node_id = n.id
    ), '')::text AS groups
FROM policy_membership pm
JOIN policies p ON p.id = pm.policy_id
JOIN nodes n ON n.id = pm.node_id
WHERE pm.passes = false
  AND (
    (coalesce(cardinality($1::uuid[]), 0) > 0 AND p.uuid = ANY($1::uuid[]))
    OR (coalesce(cardinality($1::uuid[]), 0) = 0 AND p.enabled = true)
  )
  -- only nodes still within the policy's effective scope, so alerts resolve
  -- once a policy's platform/group targeting no longer covers the node
  AND (
    p.platform IN ('all', 'any')
    OR p.platform = n.platform
    OR (p.platform = 'linux' AND n.platform NOT IN ('', 'darwin', 'windows'))
    OR (p.platform = 'posix' AND n.platform NOT IN ('', 'windows'))
  )
  AND (
    NOT EXISTS (
        SELECT 1 FROM policy_groups pg WHERE pg.policy_id = p.id
    )
    OR EXISTS (
        SELECT 1 FROM policy_groups pg
        JOIN group_membership pgm ON pgm.group_id = pg.group_id
        WHERE pg.policy_id = p.id AND pgm.node_id = n.id
    )
  )
  AND (coalesce(cardinality($2::text[]), 0) = 0 OR n.platform = ANY($2::text[]))
  AND (coalesce(cardinality($3::text[]), 0) = 0 OR p.severity = ANY($3::text[]))
  AND (
    coalesce(cardinality($4::uuid[]), 0) = 0
    OR EXISTS (
        SELECT 1 FROM group_membership gm
        JOIN groups g ON g.id = gm.group_id
        WHERE gm.node_id = n.id AND g.uuid = ANY($4::uuid[])
    )
  )
  AND ($5::bool OR pm.checked_at >= now() - $6::text::interval)
ORDER BY n.id
`

type ListFailingPolicyNodesParams struct {
	Policies     []uuid.UUID `db:"policies" json:"policies"`
	Platforms    []string    `db:"platforms" json:"platforms"`
	Severities   []string    `db:"severities" json:"severities"`
	Groups       []uuid.UUID `db:"groups" json:"groups"`
	IncludeStale bool        `db:"include_stale" json:"include_stale"`
	StaleAfter   string      `db:"stale_after" json:"stale_after"`
}

type ListFailingPolicyNodesRow struct {
	PolicyUuid uuid.UUID `db:"policy_uuid" json:"policy_uuid"`
	PolicyName string    `db:"policy_name" json:"policy_name"`
	Resolution string    `db:"resolution" json:"resolution"`
	Severity   string    `db:"severity" json:"severity"`
	NodeID     int64     `db:"node_id" json:"node_id"`
	NodeUuid   uuid.UUID `db:"node_uuid" json:"node_uuid"`
	Hostname   string    `db:"hostname" json:"hostname"`
	Platform   string    `db:"platform" json:"platform"`
	Groups     string    `db:"groups" json:"groups"`
}

func (q *Queries) ListFailingPolicyNodes(ctx context.Context, arg ListFailingPolicyNodesParams) ([]ListFailingPolicyNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailingPolicyNodes,
		pq.Array(arg.Policies),
		pq.Array(arg.Platforms),
		pq.Array(arg.Severities),
		pq.Array(arg.Groups),
		arg.IncludeStale,
		arg.StaleAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFailingPolicyNodesRow
	for rows.Next() {
		var i ListFailingPolicyNodesRow
		if err := rows.Scan(
			&i.PolicyUuid,
			&i.PolicyName,
			&i.Resolution,
			&i.Severity,
			&i.NodeID,
			&i.NodeUuid,
			&i.Hostname,
			&i.Platform,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfflineNodes = `-- name: ListOfflineNodes :many
SELECT
    n.id AS node_id,
    n.uuid AS node_uuid,
    COALESCE(NULLIF(n.display_name, ''), n.hostname) AS hostname,
    n.platform AS platform,
    n.last_seen_at AS last_seen_at,
    COALESCE((
        SELECT string_agg(g.name, ',' ORDER BY g.name)
        FROM group_membership gm
        JOIN groups g ON g.id = gm.group_id
        WHERE gm.node_id = n.id
    ), '')::text AS groups
FROM nodes n
WHERE (n.last_seen_at IS NULL OR n.last_seen_at < now() - $1::text::interval)
  AND (coalesce(cardinality($2::text[]), 0) = 0 OR n.platform = ANY($2::text[]))
  AND (
    coalesce(cardinality($3::uuid[]), 0) = 0
    OR EXISTS (
        SELECT 1 FROM group_membership gm
        JOIN groups g ON g.id = gm.group_id
        WHERE gm.node_id = n.id AND g.uuid = ANY($3::uuid[])
    )
  )
ORDER BY n.id
`

type ListOfflineNodesParams struct {
	Threshold string      `db:"threshold" json:"threshold"`
	Platforms []string    `db:"platforms" json:"platforms"`
	Groups    []uuid.UUID `db:"groups" json:"groups"`
}

type ListOfflineNodesRow struct {
	NodeID     int64        `db:"node_id" json:"node_id"`
	NodeUuid   uuid.UUID    `db:"node_uuid" json:"node_uuid"`
	Hostname   string       `db:"hostname" json:"hostname"`
	Platform   string       `db:"platform" json:"platform"`
	LastSeenAt sql.NullTime `db:"last_seen_at" json:"last_seen_at"`
	Groups     string       `db:"groups" json:"groups"`
}

func (q *Queries) ListOfflineNodes(ctx context.Context, arg ListOfflineNodesParams) ([]ListOfflineNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOfflineNodes, arg.Threshold, pq.Array(arg.Platforms), pq.Array(arg.Groups))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOfflineNodesRow
	for rows.Next() {
		var i ListOfflineNodesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.NodeUuid,
			&i.Hostname,
			&i.Platform,
			&i.LastSeenAt,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetUUIDsForRule = `-- name: ListTargetUUIDsForRule :many
SELECT t.uuid FROM alert_targets t
JOIN alert_rule_targets rt ON rt.target_id = t.id
WHERE rt.rule_id = $1
`

func (q *Queries) ListTargetUUIDsForRule(ctx context.Context, ruleID int64) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listTargetUUIDsForRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var uuid uuid.UUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsForRule = `-- name: ListTargetsForRule :many
SELECT t.id, t.uuid, t.name, t.type, t.config, t.enabled, t.created_at, t.updated_at FROM alert_targets t
JOIN alert_rule_targets rt ON rt.target_id = t.id
WHERE rt.rule_id = $1 AND t.enabled = true
`

func (q *Queries) ListTargetsForRule(ctx context.Context, ruleID int64) ([]AlertTarget, error) {
	rows, err := q.db.QueryContext(ctx, listTargetsForRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertTarget
	for rows.Next() {
		var i AlertTarget
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupMemberEmails = `-- name: ListUserGroupMemberEmails :many
SELECT u.email FROM user_groups g
JOIN user_group_members m ON m.user_group_id = g.id
JOIN users u ON u.id = m.user_id
WHERE g.name = $1 AND u.disabled = false AND length(trim(u.email)) > 0
`

func (q *Queries) ListUserGroupMemberEmails(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroupMemberEmails, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertRuleByUUID = `-- name: UpdateAlertRuleByUUID :one
UPDATE alert_rules
SET name = $2, description = $3, source = $4, params = $5, severity = $6,
    enabled = $7, evaluation_interval_seconds = $8, for_seconds = $9,
    repeat_interval_seconds = $10, updated_at = now()
WHERE uuid = $1
RETURNING id, uuid, name, description, source, params, severity, enabled, evaluation_interval_seconds, for_seconds, repeat_interval_seconds, last_evaluated_at, created_at, updated_at
`

type UpdateAlertRuleByUUIDParams struct {
	Uuid                      uuid.UUID       `db:"uuid" json:"uuid"`
	Name                      string          `db:"name" json:"name"`
	Description               string          `db:"description" json:"description"`
	Source                    string          `db:"source" json:"source"`
	Params                    json.RawMessage `db:"params" json:"params"`
	Severity                  string          `db:"severity" json:"severity"`
	Enabled                   bool            `db:"enabled" json:"enabled"`
	EvaluationIntervalSeconds int32           `db:"evaluation_interval_seconds" json:"evaluation_interval_seconds"`
	ForSeconds                int32           `db:"for_seconds" json:"for_seconds"`
	RepeatIntervalSeconds     int32           `db:"repeat_interval_seconds" json:"repeat_interval_seconds"`
}

func (q *Queries) UpdateAlertRuleByUUID(ctx context.Context, arg UpdateAlertRuleByUUIDParams) (AlertRule, error) {
	row := q.db.QueryRowContext(ctx, updateAlertRuleByUUID,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.Source,
		arg.Params,
		arg.Severity,
		arg.Enabled,
		arg.EvaluationIntervalSeconds,
		arg.ForSeconds,
		arg.RepeatIntervalSeconds,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Params,
		&i.Severity,
		&i.Enabled,
		&i.EvaluationIntervalSeconds,
		&i.ForSeconds,
		&i.RepeatIntervalSeconds,
		&i.LastEvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertTargetByUUID = `-- name: UpdateAlertTargetByUUID :one
UPDATE alert_targets
SET name = $2, config = $3, enabled = $4, updated_at = now()
WHERE uuid = $1
RETURNING id, uuid, name, type, config, enabled, created_at, updated_at
`

type UpdateAlertTargetByUUIDParams struct {
	Uuid    uuid.UUID       `db:"uuid" json:"uuid"`
	Name    string          `db:"name" json:"name"`
	Config  json.RawMessage `db:"config" json:"config"`
	Enabled bool            `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateAlertTargetByUUID(ctx context.Context, arg UpdateAlertTargetByUUIDParams) (AlertTarget, error) {
	row := q.db.QueryRowContext(ctx, updateAlertTargetByUUID,
		arg.Uuid,
		arg.Name,
		arg.Config,
		arg.Enabled,
	)
	var i AlertTarget
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAlertState = `-- name: UpsertAlertState :exec
INSERT INTO alert_state (rule_id, alert_key, status, labels, annotations, first_seen_at, last_seen_at, last_notified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (rule_id, alert_key) DO UPDATE SET
    status = EXCLUDED.status,
    labels = EXCLUDED.labels,
    annotations = EXCLUDED.annotations,
    last_seen_at = EXCLUDED.last_seen_at,
    last_notified_at = EXCLUDED.last_notified_at
`

type UpsertAlertStateParams struct {
	RuleID         int64           `db:"rule_id" json:"rule_id"`
	AlertKey       string          `db:"alert_key" json:"alert_key"`
	Status         string          `db:"status" json:"status"`
	Labels         json.RawMessage `db:"labels" json:"labels"`
	Annotations    json.RawMessage `db:"annotations" json:"annotations"`
	FirstSeenAt    time.Time       `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt     time.Time       `db:"last_seen_at" json:"last_seen_at"`
	LastNotifiedAt sql.NullTime    `db:"last_notified_at" json:"last_notified_at"`
}

func (q *Queries) UpsertAlertState(ctx context.Context, arg UpsertAlertStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlertState,
		arg.RuleID,
		arg.AlertKey,
		arg.Status,
		arg.Labels,
		arg.Annotations,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.LastNotifiedAt,
	)
	return err
}
