// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: api_tokens.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (
    user_id,
    name,
    token_hash,
    source,
    expires_at,
    role
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, uuid, user_id, name, token_hash, source, expires_at, last_used_at, revoked_at, created_at, role
`

type CreateAPITokenParams struct {
	UserID    int64          `db:"user_id" json:"user_id"`
	Name      string         `db:"name" json:"name"`
	TokenHash string         `db:"token_hash" json:"token_hash"`
	Source    string         `db:"source" json:"source"`
	ExpiresAt sql.NullTime   `db:"expires_at" json:"expires_at"`
	Role      sql.NullString `db:"role" json:"role"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Source,
		arg.ExpiresAt,
		arg.Role,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Source,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const deleteExpiredAPITokens = `-- name: DeleteExpiredAPITokens :execrows
DELETE FROM api_tokens
WHERE expires_at IS NOT NULL AND expires_at < now()
`

func (q *Queries) DeleteExpiredAPITokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAPITokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, uuid, user_id, name, token_hash, source, expires_at, last_used_at, revoked_at, created_at, role FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Source,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getAPITokenByUUID = `-- name: GetAPITokenByUUID :one
SELECT id, uuid, user_id, name, token_hash, source, expires_at, last_used_at, revoked_at, created_at, role FROM api_tokens WHERE uuid = $1
`

func (q *Queries) GetAPITokenByUUID(ctx context.Context, argUuid uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByUUID, argUuid)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Source,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT api_tokens.id, api_tokens.uuid, api_tokens.user_id, api_tokens.name, api_tokens.token_hash, api_tokens.source, api_tokens.expires_at, api_tokens.last_used_at, api_tokens.revoked_at, api_tokens.created_at, api_tokens.role
FROM api_tokens
JOIN users ON users.id = api_tokens.user_id
WHERE users.uuid = $1
ORDER BY api_tokens.created_at DESC
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, userUuid uuid.UUID) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByUser, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Source,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPITokenForUser = `-- name: RevokeAPITokenForUser :execrows
UPDATE api_tokens
SET revoked_at = now()
FROM users
WHERE api_tokens.user_id = users.id
  AND api_tokens.uuid = $1
  AND users.uuid = $2
  AND api_tokens.revoked_at IS NULL
`

type RevokeAPITokenForUserParams struct {
	TokenUuid uuid.UUID `db:"token_uuid" json:"token_uuid"`
	UserUuid  uuid.UUID `db:"user_uuid" json:"user_uuid"`
}

func (q *Queries) RevokeAPITokenForUser(ctx context.Context, arg RevokeAPITokenForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPITokenForUser, arg.TokenUuid, arg.UserUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < $2)
`

type TouchAPITokenLastUsedParams struct {
	ID        int64        `db:"id" json:"id"`
	Threshold sql.NullTime `db:"threshold" json:"threshold"`
}

func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, arg TouchAPITokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchAPITokenLastUsed, arg.ID, arg.Threshold)
	return err
}
