// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dashboard.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const dashboardFiringAlertsBySeverity = `-- name: DashboardFiringAlertsBySeverity :many
SELECT
    alert_rules.severity,
    count(*)::bigint AS count
FROM alert_state
JOIN alert_rules ON alert_rules.id = alert_state.rule_id
WHERE alert_state.status = 'firing'
GROUP BY alert_rules.severity
`

type DashboardFiringAlertsBySeverityRow struct {
	Severity string `db:"severity" json:"severity"`
	Count    int64  `db:"count" json:"count"`
}

func (q *Queries) DashboardFiringAlertsBySeverity(ctx context.Context) ([]DashboardFiringAlertsBySeverityRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardFiringAlertsBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardFiringAlertsBySeverityRow
	for rows.Next() {
		var i DashboardFiringAlertsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardLeastCompliantNodes = `-- name: DashboardLeastCompliantNodes :many
WITH per_node AS (
    SELECT
        node_id,
        count(*) FILTER (WHERE passes = true AND checked_at >= $2::timestamptz)::bigint AS passing,
        count(*) FILTER (WHERE passes = false AND checked_at >= $2::timestamptz)::bigint AS failing,
        count(*)::bigint AS total
    FROM policy_membership
    GROUP BY node_id
)
SELECT
    nodes.uuid,
    nodes.hostname,
    nodes.display_name,
    per_node.passing,
    per_node.failing,
    per_node.total
FROM per_node
JOIN nodes ON nodes.id = per_node.node_id
ORDER BY per_node.passing::numeric / per_node.total ASC, per_node.failing DESC, nodes.hostname ASC
LIMIT $1
`

type DashboardLeastCompliantNodesParams struct {
	TopN        int32     `db:"top_n" json:"top_n"`
	StaleCutoff time.Time `db:"stale_cutoff" json:"stale_cutoff"`
}

type DashboardLeastCompliantNodesRow struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Hostname    string    `db:"hostname" json:"hostname"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Passing     int64     `db:"passing" json:"passing"`
	Failing     int64     `db:"failing" json:"failing"`
	Total       int64     `db:"total" json:"total"`
}

func (q *Queries) DashboardLeastCompliantNodes(ctx context.Context, arg DashboardLeastCompliantNodesParams) ([]DashboardLeastCompliantNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardLeastCompliantNodes, arg.TopN, arg.StaleCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardLeastCompliantNodesRow
	for rows.Next() {
		var i DashboardLeastCompliantNodesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Hostname,
			&i.DisplayName,
			&i.Passing,
			&i.Failing,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardMachineComplianceCounts = `-- name: DashboardMachineComplianceCounts :one
WITH per_node AS (
    SELECT
        node_id,
        bool_or(passes = false AND checked_at >= $1::timestamptz) AS has_failing,
        bool_or(passes IS NULL OR checked_at < $1::timestamptz) AS has_unknown
    FROM policy_membership
    GROUP BY node_id
)
SELECT
    count(*) FILTER (WHERE has_failing)::bigint AS failing,
    count(*) FILTER (WHERE NOT has_failing AND has_unknown)::bigint AS unknown,
    count(*) FILTER (WHERE NOT has_failing AND NOT has_unknown)::bigint AS passing,
    ((SELECT count(*) FROM nodes) - count(*))::bigint AS no_policies
FROM per_node
`

type DashboardMachineComplianceCountsRow struct {
	Failing    int64 `db:"failing" json:"failing"`
	Unknown    int64 `db:"unknown" json:"unknown"`
	Passing    int64 `db:"passing" json:"passing"`
	NoPolicies int64 `db:"no_policies" json:"no_policies"`
}

func (q *Queries) DashboardMachineComplianceCounts(ctx context.Context, staleCutoff time.Time) (DashboardMachineComplianceCountsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardMachineComplianceCounts, staleCutoff)
	var i DashboardMachineComplianceCountsRow
	err := row.Scan(
		&i.Failing,
		&i.Unknown,
		&i.Passing,
		&i.NoPolicies,
	)
	return i, err
}

const dashboardMostCompliantNodes = `-- name: DashboardMostCompliantNodes :many
WITH per_node AS (
    SELECT
        node_id,
        count(*) FILTER (WHERE passes = true AND checked_at >= $2::timestamptz)::bigint AS passing,
        count(*) FILTER (WHERE passes = false AND checked_at >= $2::timestamptz)::bigint AS failing,
        count(*)::bigint AS total
    FROM policy_membership
    GROUP BY node_id
)
SELECT
    nodes.uuid,
    nodes.hostname,
    nodes.display_name,
    per_node.passing,
    per_node.failing,
    per_node.total
FROM per_node
JOIN nodes ON nodes.id = per_node.node_id
ORDER BY per_node.passing::numeric / per_node.total DESC, per_node.failing ASC, nodes.hostname ASC
LIMIT $1
`

type DashboardMostCompliantNodesParams struct {
	TopN        int32     `db:"top_n" json:"top_n"`
	StaleCutoff time.Time `db:"stale_cutoff" json:"stale_cutoff"`
}

type DashboardMostCompliantNodesRow struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Hostname    string    `db:"hostname" json:"hostname"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Passing     int64     `db:"passing" json:"passing"`
	Failing     int64     `db:"failing" json:"failing"`
	Total       int64     `db:"total" json:"total"`
}

func (q *Queries) DashboardMostCompliantNodes(ctx context.Context, arg DashboardMostCompliantNodesParams) ([]DashboardMostCompliantNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardMostCompliantNodes, arg.TopN, arg.StaleCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardMostCompliantNodesRow
	for rows.Next() {
		var i DashboardMostCompliantNodesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Hostname,
			&i.DisplayName,
			&i.Passing,
			&i.Failing,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardNodeCounts = `-- name: DashboardNodeCounts :one
SELECT
    count(*)::bigint AS total,
    count(*) FILTER (
        WHERE last_seen_at IS NOT NULL AND last_seen_at >= $1::timestamptz
    )::bigint AS online,
    count(*) FILTER (WHERE last_seen_at IS NULL)::bigint AS never_reported
FROM nodes
`

type DashboardNodeCountsRow struct {
	Total         int64 `db:"total" json:"total"`
	Online        int64 `db:"online" json:"online"`
	NeverReported int64 `db:"never_reported" json:"never_reported"`
}

func (q *Queries) DashboardNodeCounts(ctx context.Context, onlineCutoff time.Time) (DashboardNodeCountsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardNodeCounts, onlineCutoff)
	var i DashboardNodeCountsRow
	err := row.Scan(&i.Total, &i.Online, &i.NeverReported)
	return i, err
}

const dashboardNodeCountsByPlatform = `-- name: DashboardNodeCountsByPlatform :many
SELECT
    platform,
    count(*)::bigint AS total,
    count(*) FILTER (
        WHERE last_seen_at IS NOT NULL AND last_seen_at >= $1::timestamptz
    )::bigint AS online
FROM nodes
GROUP BY platform
ORDER BY total DESC, platform
`

type DashboardNodeCountsByPlatformRow struct {
	Platform string `db:"platform" json:"platform"`
	Total    int64  `db:"total" json:"total"`
	Online   int64  `db:"online" json:"online"`
}

func (q *Queries) DashboardNodeCountsByPlatform(ctx context.Context, onlineCutoff time.Time) ([]DashboardNodeCountsByPlatformRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardNodeCountsByPlatform, onlineCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardNodeCountsByPlatformRow
	for rows.Next() {
		var i DashboardNodeCountsByPlatformRow
		if err := rows.Scan(&i.Platform, &i.Total, &i.Online); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPolicyRowCounts = `-- name: DashboardPolicyRowCounts :one
SELECT
    count(*) FILTER (WHERE passes = true AND checked_at >= $1::timestamptz)::bigint AS passing,
    count(*) FILTER (WHERE passes = false AND checked_at >= $1::timestamptz)::bigint AS failing,
    count(*) FILTER (WHERE passes IS NULL OR checked_at < $1::timestamptz)::bigint AS unknown
FROM policy_membership
`

type DashboardPolicyRowCountsRow struct {
	Passing int64 `db:"passing" json:"passing"`
	Failing int64 `db:"failing" json:"failing"`
	Unknown int64 `db:"unknown" json:"unknown"`
}

func (q *Queries) DashboardPolicyRowCounts(ctx context.Context, staleCutoff time.Time) (DashboardPolicyRowCountsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardPolicyRowCounts, staleCutoff)
	var i DashboardPolicyRowCountsRow
	err := row.Scan(&i.Passing, &i.Failing, &i.Unknown)
	return i, err
}

const dashboardRecentEnrollments = `-- name: DashboardRecentEnrollments :many
SELECT uuid, hostname, display_name, enrolled_at
FROM nodes
ORDER BY enrolled_at DESC
LIMIT $1
`

type DashboardRecentEnrollmentsRow struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Hostname    string    `db:"hostname" json:"hostname"`
	DisplayName string    `db:"display_name" json:"display_name"`
	EnrolledAt  time.Time `db:"enrolled_at" json:"enrolled_at"`
}

func (q *Queries) DashboardRecentEnrollments(ctx context.Context, topN int32) ([]DashboardRecentEnrollmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardRecentEnrollments, topN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRecentEnrollmentsRow
	for rows.Next() {
		var i DashboardRecentEnrollmentsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Hostname,
			&i.DisplayName,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentYaraMatches = `-- name: DashboardRecentYaraMatches :many
SELECT
    yara_scans.uuid AS scan_uuid,
    nodes.uuid AS node_uuid,
    nodes.hostname,
    nodes.display_name,
    yara_scan_matches.path,
    yara_scan_matches.matches,
    yara_scan_matches.created_at
FROM yara_scan_matches
JOIN yara_scans ON yara_scans.id = yara_scan_matches.scan_id
JOIN nodes ON nodes.id = yara_scan_matches.node_id
ORDER BY yara_scan_matches.created_at DESC
LIMIT $1
`

type DashboardRecentYaraMatchesRow struct {
	ScanUuid    uuid.UUID `db:"scan_uuid" json:"scan_uuid"`
	NodeUuid    uuid.UUID `db:"node_uuid" json:"node_uuid"`
	Hostname    string    `db:"hostname" json:"hostname"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Path        string    `db:"path" json:"path"`
	Matches     string    `db:"matches" json:"matches"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) DashboardRecentYaraMatches(ctx context.Context, topN int32) ([]DashboardRecentYaraMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardRecentYaraMatches, topN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRecentYaraMatchesRow
	for rows.Next() {
		var i DashboardRecentYaraMatchesRow
		if err := rows.Scan(
			&i.ScanUuid,
			&i.NodeUuid,
			&i.Hostname,
			&i.DisplayName,
			&i.Path,
			&i.Matches,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTopFailingPolicies = `-- name: DashboardTopFailingPolicies :many
SELECT
    policies.uuid,
    policies.name,
    policies.platform,
    count(*) FILTER (
        WHERE policy_membership.passes = false AND policy_membership.checked_at >= $1::timestamptz
    )::bigint AS failing_count
FROM policies
JOIN policy_membership ON policy_membership.policy_id = policies.id
GROUP BY policies.id, policies.uuid, policies.name, policies.platform
HAVING count(*) FILTER (
    WHERE policy_membership.passes = false AND policy_membership.checked_at >= $1::timestamptz
) > 0
ORDER BY failing_count DESC, policies.name
LIMIT $2
`

type DashboardTopFailingPoliciesParams struct {
	StaleCutoff time.Time `db:"stale_cutoff" json:"stale_cutoff"`
	TopN        int32     `db:"top_n" json:"top_n"`
}

type DashboardTopFailingPoliciesRow struct {
	Uuid         uuid.UUID `db:"uuid" json:"uuid"`
	Name         string    `db:"name" json:"name"`
	Platform     string    `db:"platform" json:"platform"`
	FailingCount int64     `db:"failing_count" json:"failing_count"`
}

func (q *Queries) DashboardTopFailingPolicies(ctx context.Context, arg DashboardTopFailingPoliciesParams) ([]DashboardTopFailingPoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardTopFailingPolicies, arg.StaleCutoff, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardTopFailingPoliciesRow
	for rows.Next() {
		var i DashboardTopFailingPoliciesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Platform,
			&i.FailingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
