// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dashboard.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const dashboardFiringAlerts = `-- name: DashboardFiringAlerts :many
SELECT
    alert_rules.uuid,
    alert_rules.name,
    alert_rules.severity,
    count(*)::bigint AS count,
    max(alert_state.last_seen_at)::timestamptz AS last_seen_at
FROM alert_state
JOIN alert_rules ON alert_rules.id = alert_state.rule_id
WHERE alert_state.status = 'firing' AND alert_rules.enabled = true
GROUP BY alert_rules.uuid, alert_rules.name, alert_rules.severity
ORDER BY
    CASE alert_rules.severity
        WHEN 'critical' THEN 0
        WHEN 'high' THEN 1
        WHEN 'medium' THEN 2
        WHEN 'low' THEN 3
        WHEN 'info' THEN 4
        ELSE 5
    END,
    last_seen_at DESC
LIMIT $1
`

type DashboardFiringAlertsRow struct {
	Uuid       uuid.UUID `db:"uuid" json:"uuid"`
	Name       string    `db:"name" json:"name"`
	Severity   string    `db:"severity" json:"severity"`
	Count      int64     `db:"count" json:"count"`
	LastSeenAt time.Time `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) DashboardFiringAlerts(ctx context.Context, topN int32) ([]DashboardFiringAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardFiringAlerts, topN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardFiringAlertsRow
	for rows.Next() {
		var i DashboardFiringAlertsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Severity,
			&i.Count,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardFiringAlertsBySeverity = `-- name: DashboardFiringAlertsBySeverity :many
SELECT
    alert_rules.severity,
    count(*)::bigint AS count
FROM alert_state
JOIN alert_rules ON alert_rules.id = alert_state.rule_id
WHERE alert_state.status = 'firing' AND alert_rules.enabled = true
GROUP BY alert_rules.severity
`

type DashboardFiringAlertsBySeverityRow struct {
	Severity string `db:"severity" json:"severity"`
	Count    int64  `db:"count" json:"count"`
}

func (q *Queries) DashboardFiringAlertsBySeverity(ctx context.Context) ([]DashboardFiringAlertsBySeverityRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardFiringAlertsBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardFiringAlertsBySeverityRow
	for rows.Next() {
		var i DashboardFiringAlertsBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardLeastCompliantNodes = `-- name: DashboardLeastCompliantNodes :many
WITH per_node AS (
    SELECT
        nodes.id AS node_id,
        count(*) FILTER (WHERE policy_membership.passes = true AND policy_membership.checked_at >= $2::timestamptz)::bigint AS passing,
        count(*) FILTER (WHERE policy_membership.passes = false AND policy_membership.checked_at >= $2::timestamptz)::bigint AS failing,
        count(*)::bigint AS total,
        coalesce(sum(
            CASE policies.severity
                WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
            END
        ) FILTER (WHERE policy_membership.passes = true AND policy_membership.checked_at >= $2::timestamptz), 0)::bigint AS weighted_passing,
        coalesce(sum(
            CASE policies.severity
                WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
            END
        ), 0)::bigint AS weighted_total
    FROM nodes
    JOIN policies ON policies.enabled = true
        AND (
            policies.platform IN ('all', 'any')
            OR policies.platform = nodes.platform
            OR (policies.platform = 'linux' AND nodes.platform NOT IN ('', 'darwin', 'windows'))
            OR (policies.platform = 'posix' AND nodes.platform NOT IN ('', 'windows'))
        )
        AND (
            NOT EXISTS (
                SELECT 1
                FROM policy_groups
                WHERE policy_groups.policy_id = policies.id
            )
            OR EXISTS (
                SELECT 1
                FROM policy_groups
                JOIN group_membership ON group_membership.group_id = policy_groups.group_id
                WHERE policy_groups.policy_id = policies.id
                  AND group_membership.node_id = nodes.id
            )
        )
    LEFT JOIN policy_membership
        ON policy_membership.policy_id = policies.id
       AND policy_membership.node_id = nodes.id
    GROUP BY nodes.id
)
SELECT
    nodes.uuid,
    nodes.hostname,
    nodes.display_name,
    per_node.passing,
    per_node.failing,
    per_node.total,
    per_node.weighted_passing,
    per_node.weighted_total
FROM per_node
JOIN nodes ON nodes.id = per_node.node_id
ORDER BY per_node.weighted_passing::numeric / nullif(per_node.weighted_total, 0) ASC, per_node.failing DESC, nodes.hostname ASC
LIMIT $1
`

type DashboardLeastCompliantNodesParams struct {
	TopN        int32     `db:"top_n" json:"top_n"`
	StaleCutoff time.Time `db:"stale_cutoff" json:"stale_cutoff"`
}

type DashboardLeastCompliantNodesRow struct {
	Uuid            uuid.UUID `db:"uuid" json:"uuid"`
	Hostname        string    `db:"hostname" json:"hostname"`
	DisplayName     string    `db:"display_name" json:"display_name"`
	Passing         int64     `db:"passing" json:"passing"`
	Failing         int64     `db:"failing" json:"failing"`
	Total           int64     `db:"total" json:"total"`
	WeightedPassing int64     `db:"weighted_passing" json:"weighted_passing"`
	WeightedTotal   int64     `db:"weighted_total" json:"weighted_total"`
}

func (q *Queries) DashboardLeastCompliantNodes(ctx context.Context, arg DashboardLeastCompliantNodesParams) ([]DashboardLeastCompliantNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardLeastCompliantNodes, arg.TopN, arg.StaleCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardLeastCompliantNodesRow
	for rows.Next() {
		var i DashboardLeastCompliantNodesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Hostname,
			&i.DisplayName,
			&i.Passing,
			&i.Failing,
			&i.Total,
			&i.WeightedPassing,
			&i.WeightedTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardMostCompliantNodes = `-- name: DashboardMostCompliantNodes :many
WITH per_node AS (
    SELECT
        nodes.id AS node_id,
        count(*) FILTER (WHERE policy_membership.passes = true AND policy_membership.checked_at >= $2::timestamptz)::bigint AS passing,
        count(*) FILTER (WHERE policy_membership.passes = false AND policy_membership.checked_at >= $2::timestamptz)::bigint AS failing,
        count(*)::bigint AS total,
        coalesce(sum(
            CASE policies.severity
                WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
            END
        ) FILTER (WHERE policy_membership.passes = true AND policy_membership.checked_at >= $2::timestamptz), 0)::bigint AS weighted_passing,
        coalesce(sum(
            CASE policies.severity
                WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
            END
        ), 0)::bigint AS weighted_total
    FROM nodes
    JOIN policies ON policies.enabled = true
        AND (
            policies.platform IN ('all', 'any')
            OR policies.platform = nodes.platform
            OR (policies.platform = 'linux' AND nodes.platform NOT IN ('', 'darwin', 'windows'))
            OR (policies.platform = 'posix' AND nodes.platform NOT IN ('', 'windows'))
        )
        AND (
            NOT EXISTS (
                SELECT 1
                FROM policy_groups
                WHERE policy_groups.policy_id = policies.id
            )
            OR EXISTS (
                SELECT 1
                FROM policy_groups
                JOIN group_membership ON group_membership.group_id = policy_groups.group_id
                WHERE policy_groups.policy_id = policies.id
                  AND group_membership.node_id = nodes.id
            )
        )
    LEFT JOIN policy_membership
        ON policy_membership.policy_id = policies.id
       AND policy_membership.node_id = nodes.id
    GROUP BY nodes.id
)
SELECT
    nodes.uuid,
    nodes.hostname,
    nodes.display_name,
    per_node.passing,
    per_node.failing,
    per_node.total,
    per_node.weighted_passing,
    per_node.weighted_total
FROM per_node
JOIN nodes ON nodes.id = per_node.node_id
ORDER BY per_node.weighted_passing::numeric / nullif(per_node.weighted_total, 0) DESC, per_node.failing ASC, nodes.hostname ASC
LIMIT $1
`

type DashboardMostCompliantNodesParams struct {
	TopN        int32     `db:"top_n" json:"top_n"`
	StaleCutoff time.Time `db:"stale_cutoff" json:"stale_cutoff"`
}

type DashboardMostCompliantNodesRow struct {
	Uuid            uuid.UUID `db:"uuid" json:"uuid"`
	Hostname        string    `db:"hostname" json:"hostname"`
	DisplayName     string    `db:"display_name" json:"display_name"`
	Passing         int64     `db:"passing" json:"passing"`
	Failing         int64     `db:"failing" json:"failing"`
	Total           int64     `db:"total" json:"total"`
	WeightedPassing int64     `db:"weighted_passing" json:"weighted_passing"`
	WeightedTotal   int64     `db:"weighted_total" json:"weighted_total"`
}

func (q *Queries) DashboardMostCompliantNodes(ctx context.Context, arg DashboardMostCompliantNodesParams) ([]DashboardMostCompliantNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardMostCompliantNodes, arg.TopN, arg.StaleCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardMostCompliantNodesRow
	for rows.Next() {
		var i DashboardMostCompliantNodesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Hostname,
			&i.DisplayName,
			&i.Passing,
			&i.Failing,
			&i.Total,
			&i.WeightedPassing,
			&i.WeightedTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardNodeCounts = `-- name: DashboardNodeCounts :one
SELECT
    count(*)::bigint AS total,
    count(*) FILTER (
        WHERE last_seen_at IS NOT NULL AND last_seen_at >= $1::timestamptz
    )::bigint AS online,
    count(*) FILTER (WHERE last_seen_at IS NULL)::bigint AS never_reported
FROM nodes
`

type DashboardNodeCountsRow struct {
	Total         int64 `db:"total" json:"total"`
	Online        int64 `db:"online" json:"online"`
	NeverReported int64 `db:"never_reported" json:"never_reported"`
}

func (q *Queries) DashboardNodeCounts(ctx context.Context, onlineCutoff time.Time) (DashboardNodeCountsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardNodeCounts, onlineCutoff)
	var i DashboardNodeCountsRow
	err := row.Scan(&i.Total, &i.Online, &i.NeverReported)
	return i, err
}

const dashboardNodeCountsByPlatform = `-- name: DashboardNodeCountsByPlatform :many
SELECT
    platform,
    count(*)::bigint AS total,
    count(*) FILTER (
        WHERE last_seen_at IS NOT NULL AND last_seen_at >= $1::timestamptz
    )::bigint AS online
FROM nodes
GROUP BY platform
ORDER BY total DESC, platform
`

type DashboardNodeCountsByPlatformRow struct {
	Platform string `db:"platform" json:"platform"`
	Total    int64  `db:"total" json:"total"`
	Online   int64  `db:"online" json:"online"`
}

func (q *Queries) DashboardNodeCountsByPlatform(ctx context.Context, onlineCutoff time.Time) ([]DashboardNodeCountsByPlatformRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardNodeCountsByPlatform, onlineCutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardNodeCountsByPlatformRow
	for rows.Next() {
		var i DashboardNodeCountsByPlatformRow
		if err := rows.Scan(&i.Platform, &i.Total, &i.Online); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardPolicyRowCounts = `-- name: DashboardPolicyRowCounts :one
SELECT
    count(*) FILTER (WHERE passes = true AND checked_at >= $1::timestamptz)::bigint AS passing,
    count(*) FILTER (WHERE passes = false AND checked_at >= $1::timestamptz)::bigint AS failing,
    count(*) FILTER (WHERE passes IS NULL OR checked_at < $1::timestamptz)::bigint AS unknown,
    coalesce(sum(
        CASE policies.severity
            WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
        END
    ) FILTER (WHERE passes = true AND checked_at >= $1::timestamptz), 0)::bigint AS weighted_passing,
    coalesce(sum(
        CASE policies.severity
            WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
        END
    ), 0)::bigint AS weighted_total
FROM policy_membership
JOIN policies ON policies.id = policy_membership.policy_id
`

type DashboardPolicyRowCountsRow struct {
	Passing         int64 `db:"passing" json:"passing"`
	Failing         int64 `db:"failing" json:"failing"`
	Unknown         int64 `db:"unknown" json:"unknown"`
	WeightedPassing int64 `db:"weighted_passing" json:"weighted_passing"`
	WeightedTotal   int64 `db:"weighted_total" json:"weighted_total"`
}

// Fibonacci severity weights
func (q *Queries) DashboardPolicyRowCounts(ctx context.Context, staleCutoff time.Time) (DashboardPolicyRowCountsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardPolicyRowCounts, staleCutoff)
	var i DashboardPolicyRowCountsRow
	err := row.Scan(
		&i.Passing,
		&i.Failing,
		&i.Unknown,
		&i.WeightedPassing,
		&i.WeightedTotal,
	)
	return i, err
}

const dashboardRecentEnrollments = `-- name: DashboardRecentEnrollments :many
SELECT uuid, hostname, display_name, enrolled_at
FROM nodes
ORDER BY enrolled_at DESC
LIMIT $1
`

type DashboardRecentEnrollmentsRow struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Hostname    string    `db:"hostname" json:"hostname"`
	DisplayName string    `db:"display_name" json:"display_name"`
	EnrolledAt  time.Time `db:"enrolled_at" json:"enrolled_at"`
}

func (q *Queries) DashboardRecentEnrollments(ctx context.Context, topN int32) ([]DashboardRecentEnrollmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardRecentEnrollments, topN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRecentEnrollmentsRow
	for rows.Next() {
		var i DashboardRecentEnrollmentsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Hostname,
			&i.DisplayName,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentYaraMatches = `-- name: DashboardRecentYaraMatches :many
SELECT
    yara_scans.uuid AS scan_uuid,
    nodes.uuid AS node_uuid,
    nodes.hostname,
    nodes.display_name,
    yara_scan_matches.path,
    yara_scan_matches.matches,
    yara_scan_matches.created_at
FROM yara_scan_matches
JOIN yara_scans ON yara_scans.id = yara_scan_matches.scan_id
JOIN nodes ON nodes.id = yara_scan_matches.node_id
ORDER BY yara_scan_matches.created_at DESC
LIMIT $1
`

type DashboardRecentYaraMatchesRow struct {
	ScanUuid    uuid.UUID `db:"scan_uuid" json:"scan_uuid"`
	NodeUuid    uuid.UUID `db:"node_uuid" json:"node_uuid"`
	Hostname    string    `db:"hostname" json:"hostname"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Path        string    `db:"path" json:"path"`
	Matches     string    `db:"matches" json:"matches"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) DashboardRecentYaraMatches(ctx context.Context, topN int32) ([]DashboardRecentYaraMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardRecentYaraMatches, topN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRecentYaraMatchesRow
	for rows.Next() {
		var i DashboardRecentYaraMatchesRow
		if err := rows.Scan(
			&i.ScanUuid,
			&i.NodeUuid,
			&i.Hostname,
			&i.DisplayName,
			&i.Path,
			&i.Matches,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTopFailingPolicies = `-- name: DashboardTopFailingPolicies :many
SELECT
    policies.uuid,
    policies.name,
    policies.platform,
    count(*) FILTER (
        WHERE policy_membership.passes = false AND policy_membership.checked_at >= $1::timestamptz
    )::bigint AS failing_count
FROM policies
JOIN policy_membership ON policy_membership.policy_id = policies.id
GROUP BY policies.id, policies.uuid, policies.name, policies.platform
HAVING count(*) FILTER (
    WHERE policy_membership.passes = false AND policy_membership.checked_at >= $1::timestamptz
) > 0
ORDER BY failing_count DESC, policies.name
LIMIT $2
`

type DashboardTopFailingPoliciesParams struct {
	StaleCutoff time.Time `db:"stale_cutoff" json:"stale_cutoff"`
	TopN        int32     `db:"top_n" json:"top_n"`
}

type DashboardTopFailingPoliciesRow struct {
	Uuid         uuid.UUID `db:"uuid" json:"uuid"`
	Name         string    `db:"name" json:"name"`
	Platform     string    `db:"platform" json:"platform"`
	FailingCount int64     `db:"failing_count" json:"failing_count"`
}

func (q *Queries) DashboardTopFailingPolicies(ctx context.Context, arg DashboardTopFailingPoliciesParams) ([]DashboardTopFailingPoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardTopFailingPolicies, arg.StaleCutoff, arg.TopN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardTopFailingPoliciesRow
	for rows.Next() {
		var i DashboardTopFailingPoliciesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Platform,
			&i.FailingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeComplianceScore = `-- name: GetNodeComplianceScore :one
SELECT
    coalesce(sum(
        CASE policies.severity
            WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
        END
    ) FILTER (WHERE policy_membership.passes = true AND policy_membership.checked_at >= $1::timestamptz), 0)::bigint AS weighted_passing,
    coalesce(sum(
        CASE policies.severity
            WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
        END
    ), 0)::bigint AS weighted_total
FROM nodes
LEFT JOIN policies ON policies.enabled = true
    AND (
        policies.platform IN ('all', 'any')
        OR policies.platform = nodes.platform
        OR (policies.platform = 'linux' AND nodes.platform NOT IN ('', 'darwin', 'windows'))
        OR (policies.platform = 'posix' AND nodes.platform NOT IN ('', 'windows'))
    )
    AND (
        NOT EXISTS (
            SELECT 1
            FROM policy_groups
            WHERE policy_groups.policy_id = policies.id
        )
        OR EXISTS (
            SELECT 1
            FROM policy_groups
            JOIN group_membership ON group_membership.group_id = policy_groups.group_id
            WHERE policy_groups.policy_id = policies.id
              AND group_membership.node_id = nodes.id
        )
    )
LEFT JOIN policy_membership
    ON policy_membership.policy_id = policies.id
   AND policy_membership.node_id = nodes.id
WHERE nodes.uuid = $2
GROUP BY nodes.id
`

type GetNodeComplianceScoreParams struct {
	StaleCutoff time.Time `db:"stale_cutoff" json:"stale_cutoff"`
	NodeUuid    uuid.UUID `db:"node_uuid" json:"node_uuid"`
}

type GetNodeComplianceScoreRow struct {
	WeightedPassing int64 `db:"weighted_passing" json:"weighted_passing"`
	WeightedTotal   int64 `db:"weighted_total" json:"weighted_total"`
}

func (q *Queries) GetNodeComplianceScore(ctx context.Context, arg GetNodeComplianceScoreParams) (GetNodeComplianceScoreRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeComplianceScore, arg.StaleCutoff, arg.NodeUuid)
	var i GetNodeComplianceScoreRow
	err := row.Scan(&i.WeightedPassing, &i.WeightedTotal)
	return i, err
}
