// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: enrollment_secrets.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEnrollmentSecret = `-- name: CreateEnrollmentSecret :one
INSERT INTO enrollment_secrets (
    secret_id,
    type,
    owner_user_uuid,
    created_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, uuid, secret_id, type, owner_user_uuid, created_by, revoked_at, revoked_by, created_at
`

type CreateEnrollmentSecretParams struct {
	SecretID      []byte        `db:"secret_id" json:"secret_id"`
	Type          string        `db:"type" json:"type"`
	OwnerUserUuid uuid.NullUUID `db:"owner_user_uuid" json:"owner_user_uuid"`
	CreatedBy     sql.NullInt64 `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateEnrollmentSecret(ctx context.Context, arg CreateEnrollmentSecretParams) (EnrollmentSecret, error) {
	row := q.db.QueryRowContext(ctx, createEnrollmentSecret,
		arg.SecretID,
		arg.Type,
		arg.OwnerUserUuid,
		arg.CreatedBy,
	)
	var i EnrollmentSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SecretID,
		&i.Type,
		&i.OwnerUserUuid,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUnusedOwnedEnrollmentSecrets = `-- name: DeleteUnusedOwnedEnrollmentSecrets :execrows
DELETE FROM enrollment_secrets
WHERE type = 'owned'
  AND created_at < $1::timestamptz
  AND NOT EXISTS (
    SELECT 1 FROM nodes WHERE nodes.enrollment_secret_id = enrollment_secrets.id
  )
`

func (q *Queries) DeleteUnusedOwnedEnrollmentSecrets(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnusedOwnedEnrollmentSecrets, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveAnonymousEnrollmentSecret = `-- name: GetActiveAnonymousEnrollmentSecret :one
SELECT id, uuid, secret_id, type, owner_user_uuid, created_by, revoked_at, revoked_by, created_at FROM enrollment_secrets
WHERE type = 'anonymous' AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveAnonymousEnrollmentSecret(ctx context.Context) (EnrollmentSecret, error) {
	row := q.db.QueryRowContext(ctx, getActiveAnonymousEnrollmentSecret)
	var i EnrollmentSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SecretID,
		&i.Type,
		&i.OwnerUserUuid,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveOwnedEnrollmentSecret = `-- name: GetActiveOwnedEnrollmentSecret :one
SELECT id, uuid, secret_id, type, owner_user_uuid, created_by, revoked_at, revoked_by, created_at FROM enrollment_secrets
WHERE type = 'owned' AND owner_user_uuid = $1 AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveOwnedEnrollmentSecret(ctx context.Context, ownerUserUuid uuid.NullUUID) (EnrollmentSecret, error) {
	row := q.db.QueryRowContext(ctx, getActiveOwnedEnrollmentSecret, ownerUserUuid)
	var i EnrollmentSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SecretID,
		&i.Type,
		&i.OwnerUserUuid,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentSecretBySecretID = `-- name: GetEnrollmentSecretBySecretID :one
SELECT id, uuid, secret_id, type, owner_user_uuid, created_by, revoked_at, revoked_by, created_at FROM enrollment_secrets WHERE secret_id = $1
`

func (q *Queries) GetEnrollmentSecretBySecretID(ctx context.Context, secretID []byte) (EnrollmentSecret, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentSecretBySecretID, secretID)
	var i EnrollmentSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SecretID,
		&i.Type,
		&i.OwnerUserUuid,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentSecretByUUID = `-- name: GetEnrollmentSecretByUUID :one
SELECT id, uuid, secret_id, type, owner_user_uuid, created_by, revoked_at, revoked_by, created_at FROM enrollment_secrets WHERE uuid = $1
`

func (q *Queries) GetEnrollmentSecretByUUID(ctx context.Context, argUuid uuid.UUID) (EnrollmentSecret, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentSecretByUUID, argUuid)
	var i EnrollmentSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SecretID,
		&i.Type,
		&i.OwnerUserUuid,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEnrollmentSecrets = `-- name: ListEnrollmentSecrets :many
SELECT
    enrollment_secrets.id, enrollment_secrets.uuid, enrollment_secrets.secret_id, enrollment_secrets.type, enrollment_secrets.owner_user_uuid, enrollment_secrets.created_by, enrollment_secrets.revoked_at, enrollment_secrets.revoked_by, enrollment_secrets.created_at,
    COALESCE(NULLIF(generator.email, ''), NULLIF(generator.name, ''), generator.username, '') AS generated_by,
    (SELECT count(*) FROM nodes WHERE nodes.enrollment_secret_id = enrollment_secrets.id) AS machine_count
FROM enrollment_secrets
LEFT JOIN users AS generator ON generator.id = enrollment_secrets.created_by
ORDER BY enrollment_secrets.created_at DESC
`

type ListEnrollmentSecretsRow struct {
	ID            int64         `db:"id" json:"id"`
	Uuid          uuid.UUID     `db:"uuid" json:"uuid"`
	SecretID      []byte        `db:"secret_id" json:"secret_id"`
	Type          string        `db:"type" json:"type"`
	OwnerUserUuid uuid.NullUUID `db:"owner_user_uuid" json:"owner_user_uuid"`
	CreatedBy     sql.NullInt64 `db:"created_by" json:"created_by"`
	RevokedAt     sql.NullTime  `db:"revoked_at" json:"revoked_at"`
	RevokedBy     sql.NullInt64 `db:"revoked_by" json:"revoked_by"`
	CreatedAt     time.Time     `db:"created_at" json:"created_at"`
	GeneratedBy   string        `db:"generated_by" json:"generated_by"`
	MachineCount  int64         `db:"machine_count" json:"machine_count"`
}

func (q *Queries) ListEnrollmentSecrets(ctx context.Context) ([]ListEnrollmentSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentSecretsRow
	for rows.Next() {
		var i ListEnrollmentSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.SecretID,
			&i.Type,
			&i.OwnerUserUuid,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.CreatedAt,
			&i.GeneratedBy,
			&i.MachineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByEnrollmentSecretID = `-- name: ListNodesByEnrollmentSecretID :many
SELECT nodes.id, nodes.uuid, nodes.node_key, nodes.host_identifier, nodes.hostname, nodes.platform, nodes.os_name, nodes.os_version, nodes.osquery_version, nodes.hardware_serial, nodes.enrolled_at, nodes.last_seen_at, nodes.last_policy_check_at, nodes.created_at, nodes.updated_at, nodes.display_name, nodes.enrollment_secret_id FROM nodes
JOIN enrollment_secrets ON enrollment_secrets.id = nodes.enrollment_secret_id
WHERE enrollment_secrets.uuid = $1
ORDER BY nodes.created_at DESC
`

func (q *Queries) ListNodesByEnrollmentSecretID(ctx context.Context, argUuid uuid.UUID) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByEnrollmentSecretID, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NodeKey,
			&i.HostIdentifier,
			&i.Hostname,
			&i.Platform,
			&i.OsName,
			&i.OsVersion,
			&i.OsqueryVersion,
			&i.HardwareSerial,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.LastPolicyCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.EnrollmentSecretID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeEnrollmentSecretByID = `-- name: RevokeEnrollmentSecretByID :execrows
UPDATE enrollment_secrets
SET revoked_at = now(), revoked_by = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeEnrollmentSecretByIDParams struct {
	RevokedBy sql.NullInt64 `db:"revoked_by" json:"revoked_by"`
	ID        int64         `db:"id" json:"id"`
}

func (q *Queries) RevokeEnrollmentSecretByID(ctx context.Context, arg RevokeEnrollmentSecretByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeEnrollmentSecretByID, arg.RevokedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeEnrollmentSecretByUUID = `-- name: RevokeEnrollmentSecretByUUID :execrows
UPDATE enrollment_secrets
SET revoked_at = now(), revoked_by = $1
WHERE uuid = $2 AND revoked_at IS NULL
`

type RevokeEnrollmentSecretByUUIDParams struct {
	RevokedBy sql.NullInt64 `db:"revoked_by" json:"revoked_by"`
	Uuid      uuid.UUID     `db:"uuid" json:"uuid"`
}

func (q *Queries) RevokeEnrollmentSecretByUUID(ctx context.Context, arg RevokeEnrollmentSecretByUUIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeEnrollmentSecretByUUID, arg.RevokedBy, arg.Uuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
