// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: groups.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    name,
    description
) VALUES (
    $1, $2
)
RETURNING id, uuid, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupMembership = `-- name: CreateGroupMembership :exec
INSERT INTO group_membership (
    group_id,
    node_id
) VALUES (
    $1, $2
)
ON CONFLICT (group_id, node_id) DO NOTHING
`

type CreateGroupMembershipParams struct {
	GroupID int64 `db:"group_id" json:"group_id"`
	NodeID  int64 `db:"node_id" json:"node_id"`
}

func (q *Queries) CreateGroupMembership(ctx context.Context, arg CreateGroupMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createGroupMembership, arg.GroupID, arg.NodeID)
	return err
}

const createPolicyGroup = `-- name: CreatePolicyGroup :exec
INSERT INTO policy_groups (
    policy_id,
    group_id
) VALUES (
    $1, $2
)
ON CONFLICT (policy_id, group_id) DO NOTHING
`

type CreatePolicyGroupParams struct {
	PolicyID int64 `db:"policy_id" json:"policy_id"`
	GroupID  int64 `db:"group_id" json:"group_id"`
}

func (q *Queries) CreatePolicyGroup(ctx context.Context, arg CreatePolicyGroupParams) error {
	_, err := q.db.ExecContext(ctx, createPolicyGroup, arg.PolicyID, arg.GroupID)
	return err
}

const createScheduleGroup = `-- name: CreateScheduleGroup :exec
INSERT INTO schedule_groups (
    schedule_id,
    group_id
) VALUES (
    $1, $2
)
ON CONFLICT (schedule_id, group_id) DO NOTHING
`

type CreateScheduleGroupParams struct {
	ScheduleID int64 `db:"schedule_id" json:"schedule_id"`
	GroupID    int64 `db:"group_id" json:"group_id"`
}

func (q *Queries) CreateScheduleGroup(ctx context.Context, arg CreateScheduleGroupParams) error {
	_, err := q.db.ExecContext(ctx, createScheduleGroup, arg.ScheduleID, arg.GroupID)
	return err
}

const deleteGroupByUUID = `-- name: DeleteGroupByUUID :execrows
DELETE FROM groups WHERE uuid = $1
`

func (q *Queries) DeleteGroupByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGroupByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteGroupMembershipForNode = `-- name: DeleteGroupMembershipForNode :exec
DELETE FROM group_membership
USING groups, nodes
WHERE group_membership.group_id = groups.id
  AND group_membership.node_id = nodes.id
  AND groups.uuid = $1
  AND nodes.uuid = $2
`

type DeleteGroupMembershipForNodeParams struct {
	GroupUuid uuid.UUID `db:"group_uuid" json:"group_uuid"`
	NodeUuid  uuid.UUID `db:"node_uuid" json:"node_uuid"`
}

func (q *Queries) DeleteGroupMembershipForNode(ctx context.Context, arg DeleteGroupMembershipForNodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMembershipForNode, arg.GroupUuid, arg.NodeUuid)
	return err
}

const deleteGroupMembershipsForNode = `-- name: DeleteGroupMembershipsForNode :exec
DELETE FROM group_membership
USING nodes
WHERE group_membership.node_id = nodes.id
  AND nodes.uuid = $1
`

func (q *Queries) DeleteGroupMembershipsForNode(ctx context.Context, nodeUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMembershipsForNode, nodeUuid)
	return err
}

const deletePolicyGroupsForPolicy = `-- name: DeletePolicyGroupsForPolicy :exec
DELETE FROM policy_groups
USING policies
WHERE policy_groups.policy_id = policies.id
  AND policies.uuid = $1
`

func (q *Queries) DeletePolicyGroupsForPolicy(ctx context.Context, policyUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePolicyGroupsForPolicy, policyUuid)
	return err
}

const deleteScheduleGroupsForSchedule = `-- name: DeleteScheduleGroupsForSchedule :exec
DELETE FROM schedule_groups
USING schedules
WHERE schedule_groups.schedule_id = schedules.id
  AND schedules.uuid = $1
`

func (q *Queries) DeleteScheduleGroupsForSchedule(ctx context.Context, scheduleUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleGroupsForSchedule, scheduleUuid)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, uuid, name, description, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, uuid, name, description, created_at, updated_at FROM groups WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByUUID = `-- name: GetGroupByUUID :one
SELECT id, uuid, name, description, created_at, updated_at FROM groups WHERE uuid = $1
`

func (q *Queries) GetGroupByUUID(ctx context.Context, argUuid uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByUUID, argUuid)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupWithCountsByUUID = `-- name: GetGroupWithCountsByUUID :one
SELECT
    groups.id,
    groups.uuid,
    groups.name,
    groups.description,
    groups.created_at,
    groups.updated_at,
    count(DISTINCT group_membership.node_id)::bigint AS machine_count,
    count(DISTINCT policy_groups.policy_id)::bigint AS policy_count
FROM groups
LEFT JOIN group_membership ON group_membership.group_id = groups.id
LEFT JOIN policy_groups ON policy_groups.group_id = groups.id
WHERE groups.uuid = $1
GROUP BY
    groups.id,
    groups.uuid,
    groups.name,
    groups.description,
    groups.created_at,
    groups.updated_at
`

type GetGroupWithCountsByUUIDRow struct {
	ID           int64     `db:"id" json:"id"`
	Uuid         uuid.UUID `db:"uuid" json:"uuid"`
	Name         string    `db:"name" json:"name"`
	Description  string    `db:"description" json:"description"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
	MachineCount int64     `db:"machine_count" json:"machine_count"`
	PolicyCount  int64     `db:"policy_count" json:"policy_count"`
}

func (q *Queries) GetGroupWithCountsByUUID(ctx context.Context, groupUuid uuid.UUID) (GetGroupWithCountsByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupWithCountsByUUID, groupUuid)
	var i GetGroupWithCountsByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MachineCount,
		&i.PolicyCount,
	)
	return i, err
}

const listGroupsForNode = `-- name: ListGroupsForNode :many
SELECT
    groups.id,
    groups.uuid,
    groups.name,
    groups.description,
    groups.created_at,
    groups.updated_at
FROM groups
JOIN group_membership ON group_membership.group_id = groups.id
JOIN nodes ON nodes.id = group_membership.node_id
WHERE nodes.uuid = $1
ORDER BY groups.name
`

func (q *Queries) ListGroupsForNode(ctx context.Context, nodeUuid uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForNode, nodeUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForPolicy = `-- name: ListGroupsForPolicy :many
SELECT
    groups.id,
    groups.uuid,
    groups.name,
    groups.description,
    groups.created_at,
    groups.updated_at
FROM groups
JOIN policy_groups ON policy_groups.group_id = groups.id
JOIN policies ON policies.id = policy_groups.policy_id
WHERE policies.uuid = $1
ORDER BY groups.name
`

func (q *Queries) ListGroupsForPolicy(ctx context.Context, policyUuid uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForPolicy, policyUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForSchedule = `-- name: ListGroupsForSchedule :many
SELECT
    groups.id,
    groups.uuid,
    groups.name,
    groups.description,
    groups.created_at,
    groups.updated_at
FROM groups
JOIN schedule_groups ON schedule_groups.group_id = groups.id
JOIN schedules ON schedules.id = schedule_groups.schedule_id
WHERE schedules.uuid = $1
ORDER BY groups.name
`

func (q *Queries) ListGroupsForSchedule(ctx context.Context, scheduleUuid uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForSchedule, scheduleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsWithCounts = `-- name: ListGroupsWithCounts :many
WITH filtered AS (
    SELECT id, uuid, name, description, created_at, updated_at
    FROM groups
    WHERE (
        $3::text = ''
        OR name ILIKE '%' || $3::text || '%'
        OR description ILIKE '%' || $3::text || '%'
    )
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT
    filtered.id,
    filtered.uuid,
    filtered.name,
    filtered.description,
    filtered.created_at,
    filtered.updated_at,
    count(DISTINCT group_membership.node_id)::bigint AS machine_count,
    count(DISTINCT policy_groups.policy_id)::bigint AS policy_count,
    total.total_count
FROM filtered
CROSS JOIN total
LEFT JOIN group_membership ON group_membership.group_id = filtered.id
LEFT JOIN policy_groups ON policy_groups.group_id = filtered.id
GROUP BY
    filtered.id,
    filtered.uuid,
    filtered.name,
    filtered.description,
    filtered.created_at,
    filtered.updated_at,
    total.total_count
ORDER BY filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListGroupsWithCountsParams struct {
	OffsetCount int32  `db:"offset_count" json:"offset_count"`
	LimitCount  int32  `db:"limit_count" json:"limit_count"`
	Query       string `db:"query" json:"query"`
}

type ListGroupsWithCountsRow struct {
	ID           int64     `db:"id" json:"id"`
	Uuid         uuid.UUID `db:"uuid" json:"uuid"`
	Name         string    `db:"name" json:"name"`
	Description  string    `db:"description" json:"description"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
	MachineCount int64     `db:"machine_count" json:"machine_count"`
	PolicyCount  int64     `db:"policy_count" json:"policy_count"`
	TotalCount   int64     `db:"total_count" json:"total_count"`
}

func (q *Queries) ListGroupsWithCounts(ctx context.Context, arg ListGroupsWithCountsParams) ([]ListGroupsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsWithCounts, arg.OffsetCount, arg.LimitCount, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsWithCountsRow
	for rows.Next() {
		var i ListGroupsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MachineCount,
			&i.PolicyCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByGroup = `-- name: ListNodesByGroup :many
WITH target_group AS (
    SELECT id, uuid, name, description, created_at, updated_at
    FROM groups
    WHERE groups.uuid = $3
),
filtered AS (
    SELECT
        nodes.id,
        nodes.uuid,
        nodes.node_key,
        nodes.host_identifier,
        nodes.hostname,
        nodes.display_name,
        nodes.platform,
        nodes.os_name,
        nodes.os_version,
        nodes.osquery_version,
        nodes.hardware_serial,
        nodes.enrolled_at,
        nodes.last_seen_at,
        nodes.last_policy_check_at,
        nodes.created_at,
        nodes.updated_at
    FROM target_group
    JOIN group_membership ON group_membership.group_id = target_group.id
    JOIN nodes ON nodes.id = group_membership.node_id
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.uuid, filtered.node_key, filtered.host_identifier, filtered.hostname, filtered.display_name, filtered.platform, filtered.os_name, filtered.os_version, filtered.osquery_version, filtered.hardware_serial, filtered.enrolled_at, filtered.last_seen_at, filtered.last_policy_check_at, filtered.created_at, filtered.updated_at, total.total_count
FROM filtered, total
ORDER BY filtered.hostname, filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListNodesByGroupParams struct {
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
	GroupUuid   uuid.UUID `db:"group_uuid" json:"group_uuid"`
}

type ListNodesByGroupRow struct {
	ID                int64        `db:"id" json:"id"`
	Uuid              uuid.UUID    `db:"uuid" json:"uuid"`
	NodeKey           uuid.UUID    `db:"node_key" json:"node_key"`
	HostIdentifier    string       `db:"host_identifier" json:"host_identifier"`
	Hostname          string       `db:"hostname" json:"hostname"`
	DisplayName       string       `db:"display_name" json:"display_name"`
	Platform          string       `db:"platform" json:"platform"`
	OsName            string       `db:"os_name" json:"os_name"`
	OsVersion         string       `db:"os_version" json:"os_version"`
	OsqueryVersion    string       `db:"osquery_version" json:"osquery_version"`
	HardwareSerial    string       `db:"hardware_serial" json:"hardware_serial"`
	EnrolledAt        time.Time    `db:"enrolled_at" json:"enrolled_at"`
	LastSeenAt        sql.NullTime `db:"last_seen_at" json:"last_seen_at"`
	LastPolicyCheckAt sql.NullTime `db:"last_policy_check_at" json:"last_policy_check_at"`
	CreatedAt         time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time    `db:"updated_at" json:"updated_at"`
	TotalCount        int64        `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNodesByGroup(ctx context.Context, arg ListNodesByGroupParams) ([]ListNodesByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByGroup, arg.OffsetCount, arg.LimitCount, arg.GroupUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesByGroupRow
	for rows.Next() {
		var i ListNodesByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NodeKey,
			&i.HostIdentifier,
			&i.Hostname,
			&i.DisplayName,
			&i.Platform,
			&i.OsName,
			&i.OsVersion,
			&i.OsqueryVersion,
			&i.HardwareSerial,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.LastPolicyCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupByUUID = `-- name: UpdateGroupByUUID :one
UPDATE groups SET
    name = $2,
    description = $3,
    updated_at = now()
WHERE uuid = $1
RETURNING id, uuid, name, description, created_at, updated_at
`

type UpdateGroupByUUIDParams struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
}

func (q *Queries) UpdateGroupByUUID(ctx context.Context, arg UpdateGroupByUUIDParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroupByUUID, arg.Uuid, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
