// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: inventory.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createDeviceOwner = `-- name: CreateDeviceOwner :one
INSERT INTO device_owners (
    display_name,
    email,
    external_id,
    department,
    title,
    phone,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, uuid, display_name, email, external_id, department, title, phone, notes, created_at, updated_at
`

type CreateDeviceOwnerParams struct {
	DisplayName string `db:"display_name" json:"display_name"`
	Email       string `db:"email" json:"email"`
	ExternalID  string `db:"external_id" json:"external_id"`
	Department  string `db:"department" json:"department"`
	Title       string `db:"title" json:"title"`
	Phone       string `db:"phone" json:"phone"`
	Notes       string `db:"notes" json:"notes"`
}

func (q *Queries) CreateDeviceOwner(ctx context.Context, arg CreateDeviceOwnerParams) (DeviceOwner, error) {
	row := q.db.QueryRowContext(ctx, createDeviceOwner,
		arg.DisplayName,
		arg.Email,
		arg.ExternalID,
		arg.Department,
		arg.Title,
		arg.Phone,
		arg.Notes,
	)
	var i DeviceOwner
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DisplayName,
		&i.Email,
		&i.ExternalID,
		&i.Department,
		&i.Title,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeviceOwnerByUUID = `-- name: DeleteDeviceOwnerByUUID :execrows
DELETE FROM device_owners WHERE uuid = $1
`

func (q *Queries) DeleteDeviceOwnerByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDeviceOwnerByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNodeInventoryByNodeUUID = `-- name: DeleteNodeInventoryByNodeUUID :execrows
DELETE FROM node_inventory
USING nodes
WHERE node_inventory.node_id = nodes.id
  AND nodes.uuid = $1
`

func (q *Queries) DeleteNodeInventoryByNodeUUID(ctx context.Context, nodeUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNodeInventoryByNodeUUID, nodeUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeviceOwnerByUUID = `-- name: GetDeviceOwnerByUUID :one
SELECT id, uuid, display_name, email, external_id, department, title, phone, notes, created_at, updated_at FROM device_owners WHERE uuid = $1
`

func (q *Queries) GetDeviceOwnerByUUID(ctx context.Context, argUuid uuid.UUID) (DeviceOwner, error) {
	row := q.db.QueryRowContext(ctx, getDeviceOwnerByUUID, argUuid)
	var i DeviceOwner
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DisplayName,
		&i.Email,
		&i.ExternalID,
		&i.Department,
		&i.Title,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceOwnerWithCountsByUUID = `-- name: GetDeviceOwnerWithCountsByUUID :one
SELECT
    device_owners.id,
    device_owners.uuid,
    device_owners.display_name,
    device_owners.email,
    device_owners.external_id,
    device_owners.department,
    device_owners.title,
    device_owners.phone,
    device_owners.notes,
    device_owners.created_at,
    device_owners.updated_at,
    count(node_inventory.node_id)::bigint AS machine_count
FROM device_owners
LEFT JOIN node_inventory ON node_inventory.owner_id = device_owners.id
WHERE device_owners.uuid = $1
GROUP BY
    device_owners.id,
    device_owners.uuid,
    device_owners.display_name,
    device_owners.email,
    device_owners.external_id,
    device_owners.department,
    device_owners.title,
    device_owners.phone,
    device_owners.notes,
    device_owners.created_at,
    device_owners.updated_at
`

type GetDeviceOwnerWithCountsByUUIDRow struct {
	ID           int64     `db:"id" json:"id"`
	Uuid         uuid.UUID `db:"uuid" json:"uuid"`
	DisplayName  string    `db:"display_name" json:"display_name"`
	Email        string    `db:"email" json:"email"`
	ExternalID   string    `db:"external_id" json:"external_id"`
	Department   string    `db:"department" json:"department"`
	Title        string    `db:"title" json:"title"`
	Phone        string    `db:"phone" json:"phone"`
	Notes        string    `db:"notes" json:"notes"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
	MachineCount int64     `db:"machine_count" json:"machine_count"`
}

func (q *Queries) GetDeviceOwnerWithCountsByUUID(ctx context.Context, ownerUuid uuid.UUID) (GetDeviceOwnerWithCountsByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDeviceOwnerWithCountsByUUID, ownerUuid)
	var i GetDeviceOwnerWithCountsByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DisplayName,
		&i.Email,
		&i.ExternalID,
		&i.Department,
		&i.Title,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MachineCount,
	)
	return i, err
}

const getNodeInventoryByNodeUUID = `-- name: GetNodeInventoryByNodeUUID :one
SELECT
    node_inventory.node_id,
    node_inventory.owner_id,
    node_inventory.internal_tracking_id,
    node_inventory.notes,
    node_inventory.created_at,
    node_inventory.updated_at,
    device_owners.id AS owner_db_id,
    device_owners.uuid AS owner_uuid,
    device_owners.display_name AS owner_display_name,
    device_owners.email AS owner_email,
    device_owners.external_id AS owner_external_id,
    device_owners.department AS owner_department,
    device_owners.title AS owner_title,
    device_owners.phone AS owner_phone,
    device_owners.notes AS owner_notes,
    device_owners.created_at AS owner_created_at,
    device_owners.updated_at AS owner_updated_at
FROM node_inventory
JOIN nodes ON nodes.id = node_inventory.node_id
LEFT JOIN device_owners ON device_owners.id = node_inventory.owner_id
WHERE nodes.uuid = $1
`

type GetNodeInventoryByNodeUUIDRow struct {
	NodeID             int64          `db:"node_id" json:"node_id"`
	OwnerID            sql.NullInt64  `db:"owner_id" json:"owner_id"`
	InternalTrackingID string         `db:"internal_tracking_id" json:"internal_tracking_id"`
	Notes              string         `db:"notes" json:"notes"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time      `db:"updated_at" json:"updated_at"`
	OwnerDbID          sql.NullInt64  `db:"owner_db_id" json:"owner_db_id"`
	OwnerUuid          uuid.NullUUID  `db:"owner_uuid" json:"owner_uuid"`
	OwnerDisplayName   sql.NullString `db:"owner_display_name" json:"owner_display_name"`
	OwnerEmail         sql.NullString `db:"owner_email" json:"owner_email"`
	OwnerExternalID    sql.NullString `db:"owner_external_id" json:"owner_external_id"`
	OwnerDepartment    sql.NullString `db:"owner_department" json:"owner_department"`
	OwnerTitle         sql.NullString `db:"owner_title" json:"owner_title"`
	OwnerPhone         sql.NullString `db:"owner_phone" json:"owner_phone"`
	OwnerNotes         sql.NullString `db:"owner_notes" json:"owner_notes"`
	OwnerCreatedAt     sql.NullTime   `db:"owner_created_at" json:"owner_created_at"`
	OwnerUpdatedAt     sql.NullTime   `db:"owner_updated_at" json:"owner_updated_at"`
}

func (q *Queries) GetNodeInventoryByNodeUUID(ctx context.Context, nodeUuid uuid.UUID) (GetNodeInventoryByNodeUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeInventoryByNodeUUID, nodeUuid)
	var i GetNodeInventoryByNodeUUIDRow
	err := row.Scan(
		&i.NodeID,
		&i.OwnerID,
		&i.InternalTrackingID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerDbID,
		&i.OwnerUuid,
		&i.OwnerDisplayName,
		&i.OwnerEmail,
		&i.OwnerExternalID,
		&i.OwnerDepartment,
		&i.OwnerTitle,
		&i.OwnerPhone,
		&i.OwnerNotes,
		&i.OwnerCreatedAt,
		&i.OwnerUpdatedAt,
	)
	return i, err
}

const listDeviceOwnersWithCounts = `-- name: ListDeviceOwnersWithCounts :many
WITH filtered AS (
    SELECT id, uuid, display_name, email, external_id, department, title, phone, notes, created_at, updated_at
    FROM device_owners
    WHERE (
        $3::text = ''
        OR display_name ILIKE '%' || $3::text || '%'
        OR email ILIKE '%' || $3::text || '%'
    )
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT
    filtered.id,
    filtered.uuid,
    filtered.display_name,
    filtered.email,
    filtered.external_id,
    filtered.department,
    filtered.title,
    filtered.phone,
    filtered.notes,
    filtered.created_at,
    filtered.updated_at,
    count(node_inventory.node_id)::bigint AS machine_count,
    total.total_count
FROM filtered
CROSS JOIN total
LEFT JOIN node_inventory ON node_inventory.owner_id = filtered.id
GROUP BY
    filtered.id,
    filtered.uuid,
    filtered.display_name,
    filtered.email,
    filtered.external_id,
    filtered.department,
    filtered.title,
    filtered.phone,
    filtered.notes,
    filtered.created_at,
    filtered.updated_at,
    total.total_count
ORDER BY filtered.display_name ASC, filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListDeviceOwnersWithCountsParams struct {
	OffsetCount int32  `db:"offset_count" json:"offset_count"`
	LimitCount  int32  `db:"limit_count" json:"limit_count"`
	Query       string `db:"query" json:"query"`
}

type ListDeviceOwnersWithCountsRow struct {
	ID           int64     `db:"id" json:"id"`
	Uuid         uuid.UUID `db:"uuid" json:"uuid"`
	DisplayName  string    `db:"display_name" json:"display_name"`
	Email        string    `db:"email" json:"email"`
	ExternalID   string    `db:"external_id" json:"external_id"`
	Department   string    `db:"department" json:"department"`
	Title        string    `db:"title" json:"title"`
	Phone        string    `db:"phone" json:"phone"`
	Notes        string    `db:"notes" json:"notes"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
	MachineCount int64     `db:"machine_count" json:"machine_count"`
	TotalCount   int64     `db:"total_count" json:"total_count"`
}

func (q *Queries) ListDeviceOwnersWithCounts(ctx context.Context, arg ListDeviceOwnersWithCountsParams) ([]ListDeviceOwnersWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceOwnersWithCounts, arg.OffsetCount, arg.LimitCount, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeviceOwnersWithCountsRow
	for rows.Next() {
		var i ListDeviceOwnersWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DisplayName,
			&i.Email,
			&i.ExternalID,
			&i.Department,
			&i.Title,
			&i.Phone,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MachineCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInventoriesByNodeUUIDs = `-- name: ListNodeInventoriesByNodeUUIDs :many
SELECT
    nodes.uuid AS node_uuid,
    node_inventory.node_id,
    node_inventory.owner_id,
    node_inventory.internal_tracking_id,
    node_inventory.notes,
    node_inventory.created_at,
    node_inventory.updated_at,
    device_owners.id AS owner_db_id,
    device_owners.uuid AS owner_uuid,
    device_owners.display_name AS owner_display_name,
    device_owners.email AS owner_email,
    device_owners.external_id AS owner_external_id,
    device_owners.department AS owner_department,
    device_owners.title AS owner_title,
    device_owners.phone AS owner_phone,
    device_owners.notes AS owner_notes,
    device_owners.created_at AS owner_created_at,
    device_owners.updated_at AS owner_updated_at
FROM nodes
JOIN node_inventory ON node_inventory.node_id = nodes.id
LEFT JOIN device_owners ON device_owners.id = node_inventory.owner_id
WHERE nodes.uuid = ANY($1::uuid[])
`

type ListNodeInventoriesByNodeUUIDsRow struct {
	NodeUuid           uuid.UUID      `db:"node_uuid" json:"node_uuid"`
	NodeID             int64          `db:"node_id" json:"node_id"`
	OwnerID            sql.NullInt64  `db:"owner_id" json:"owner_id"`
	InternalTrackingID string         `db:"internal_tracking_id" json:"internal_tracking_id"`
	Notes              string         `db:"notes" json:"notes"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time      `db:"updated_at" json:"updated_at"`
	OwnerDbID          sql.NullInt64  `db:"owner_db_id" json:"owner_db_id"`
	OwnerUuid          uuid.NullUUID  `db:"owner_uuid" json:"owner_uuid"`
	OwnerDisplayName   sql.NullString `db:"owner_display_name" json:"owner_display_name"`
	OwnerEmail         sql.NullString `db:"owner_email" json:"owner_email"`
	OwnerExternalID    sql.NullString `db:"owner_external_id" json:"owner_external_id"`
	OwnerDepartment    sql.NullString `db:"owner_department" json:"owner_department"`
	OwnerTitle         sql.NullString `db:"owner_title" json:"owner_title"`
	OwnerPhone         sql.NullString `db:"owner_phone" json:"owner_phone"`
	OwnerNotes         sql.NullString `db:"owner_notes" json:"owner_notes"`
	OwnerCreatedAt     sql.NullTime   `db:"owner_created_at" json:"owner_created_at"`
	OwnerUpdatedAt     sql.NullTime   `db:"owner_updated_at" json:"owner_updated_at"`
}

func (q *Queries) ListNodeInventoriesByNodeUUIDs(ctx context.Context, nodeUuids []uuid.UUID) ([]ListNodeInventoriesByNodeUUIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeInventoriesByNodeUUIDs, pq.Array(nodeUuids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeInventoriesByNodeUUIDsRow
	for rows.Next() {
		var i ListNodeInventoriesByNodeUUIDsRow
		if err := rows.Scan(
			&i.NodeUuid,
			&i.NodeID,
			&i.OwnerID,
			&i.InternalTrackingID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerDbID,
			&i.OwnerUuid,
			&i.OwnerDisplayName,
			&i.OwnerEmail,
			&i.OwnerExternalID,
			&i.OwnerDepartment,
			&i.OwnerTitle,
			&i.OwnerPhone,
			&i.OwnerNotes,
			&i.OwnerCreatedAt,
			&i.OwnerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByOwner = `-- name: ListNodesByOwner :many
WITH target_owner AS (
    SELECT id, uuid, display_name, email, external_id, department, title, phone, notes, created_at, updated_at
    FROM device_owners
    WHERE device_owners.uuid = $3
),
filtered AS (
    SELECT
        nodes.id,
        nodes.uuid,
        nodes.node_key,
        nodes.host_identifier,
        nodes.hostname,
        nodes.display_name,
        nodes.platform,
        nodes.os_name,
        nodes.os_version,
        nodes.osquery_version,
        nodes.hardware_serial,
        nodes.enrolled_at,
        nodes.last_seen_at,
        nodes.last_policy_check_at,
        nodes.created_at,
        nodes.updated_at
    FROM target_owner
    JOIN node_inventory ON node_inventory.owner_id = target_owner.id
    JOIN nodes ON nodes.id = node_inventory.node_id
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.uuid, filtered.node_key, filtered.host_identifier, filtered.hostname, filtered.display_name, filtered.platform, filtered.os_name, filtered.os_version, filtered.osquery_version, filtered.hardware_serial, filtered.enrolled_at, filtered.last_seen_at, filtered.last_policy_check_at, filtered.created_at, filtered.updated_at, total.total_count
FROM filtered, total
ORDER BY filtered.hostname, filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListNodesByOwnerParams struct {
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
	OwnerUuid   uuid.UUID `db:"owner_uuid" json:"owner_uuid"`
}

type ListNodesByOwnerRow struct {
	ID                int64        `db:"id" json:"id"`
	Uuid              uuid.UUID    `db:"uuid" json:"uuid"`
	NodeKey           uuid.UUID    `db:"node_key" json:"node_key"`
	HostIdentifier    string       `db:"host_identifier" json:"host_identifier"`
	Hostname          string       `db:"hostname" json:"hostname"`
	DisplayName       string       `db:"display_name" json:"display_name"`
	Platform          string       `db:"platform" json:"platform"`
	OsName            string       `db:"os_name" json:"os_name"`
	OsVersion         string       `db:"os_version" json:"os_version"`
	OsqueryVersion    string       `db:"osquery_version" json:"osquery_version"`
	HardwareSerial    string       `db:"hardware_serial" json:"hardware_serial"`
	EnrolledAt        time.Time    `db:"enrolled_at" json:"enrolled_at"`
	LastSeenAt        sql.NullTime `db:"last_seen_at" json:"last_seen_at"`
	LastPolicyCheckAt sql.NullTime `db:"last_policy_check_at" json:"last_policy_check_at"`
	CreatedAt         time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time    `db:"updated_at" json:"updated_at"`
	TotalCount        int64        `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNodesByOwner(ctx context.Context, arg ListNodesByOwnerParams) ([]ListNodesByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByOwner, arg.OffsetCount, arg.LimitCount, arg.OwnerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesByOwnerRow
	for rows.Next() {
		var i ListNodesByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NodeKey,
			&i.HostIdentifier,
			&i.Hostname,
			&i.DisplayName,
			&i.Platform,
			&i.OsName,
			&i.OsVersion,
			&i.OsqueryVersion,
			&i.HardwareSerial,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.LastPolicyCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceOwnerByUUID = `-- name: UpdateDeviceOwnerByUUID :one
UPDATE device_owners SET
    display_name = $2,
    email = $3,
    external_id = $4,
    department = $5,
    title = $6,
    phone = $7,
    notes = $8,
    updated_at = now()
WHERE uuid = $1
RETURNING id, uuid, display_name, email, external_id, department, title, phone, notes, created_at, updated_at
`

type UpdateDeviceOwnerByUUIDParams struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Email       string    `db:"email" json:"email"`
	ExternalID  string    `db:"external_id" json:"external_id"`
	Department  string    `db:"department" json:"department"`
	Title       string    `db:"title" json:"title"`
	Phone       string    `db:"phone" json:"phone"`
	Notes       string    `db:"notes" json:"notes"`
}

func (q *Queries) UpdateDeviceOwnerByUUID(ctx context.Context, arg UpdateDeviceOwnerByUUIDParams) (DeviceOwner, error) {
	row := q.db.QueryRowContext(ctx, updateDeviceOwnerByUUID,
		arg.Uuid,
		arg.DisplayName,
		arg.Email,
		arg.ExternalID,
		arg.Department,
		arg.Title,
		arg.Phone,
		arg.Notes,
	)
	var i DeviceOwner
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DisplayName,
		&i.Email,
		&i.ExternalID,
		&i.Department,
		&i.Title,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNodeInventory = `-- name: UpsertNodeInventory :one
INSERT INTO node_inventory (
    node_id,
    owner_id,
    internal_tracking_id,
    notes
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (node_id) DO UPDATE SET
    owner_id = EXCLUDED.owner_id,
    internal_tracking_id = EXCLUDED.internal_tracking_id,
    notes = EXCLUDED.notes,
    updated_at = now()
RETURNING node_id, owner_id, internal_tracking_id, notes, created_at, updated_at
`

type UpsertNodeInventoryParams struct {
	NodeID             int64         `db:"node_id" json:"node_id"`
	OwnerID            sql.NullInt64 `db:"owner_id" json:"owner_id"`
	InternalTrackingID string        `db:"internal_tracking_id" json:"internal_tracking_id"`
	Notes              string        `db:"notes" json:"notes"`
}

func (q *Queries) UpsertNodeInventory(ctx context.Context, arg UpsertNodeInventoryParams) (NodeInventory, error) {
	row := q.db.QueryRowContext(ctx, upsertNodeInventory,
		arg.NodeID,
		arg.OwnerID,
		arg.InternalTrackingID,
		arg.Notes,
	)
	var i NodeInventory
	err := row.Scan(
		&i.NodeID,
		&i.OwnerID,
		&i.InternalTrackingID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
