// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: machine_queries.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const completeMachineQueryResult = `-- name: CompleteMachineQueryResult :one
UPDATE machine_query_results
SET status = CASE WHEN $1::text <> '' THEN 'error' ELSE 'complete' END,
    results = $2::text::jsonb,
    error = $1,
    completed_at = now(),
    updated_at = now()
WHERE uuid = $3
RETURNING id, uuid, node_id, query, status, results, error, dispatched_at, completed_at, created_at, updated_at
`

type CompleteMachineQueryResultParams struct {
	Error   string    `db:"error" json:"error"`
	Results string    `db:"results" json:"results"`
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) CompleteMachineQueryResult(ctx context.Context, arg CompleteMachineQueryResultParams) (MachineQueryResult, error) {
	row := q.db.QueryRowContext(ctx, completeMachineQueryResult, arg.Error, arg.Results, arg.Uuid)
	var i MachineQueryResult
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeID,
		&i.Query,
		&i.Status,
		&i.Results,
		&i.Error,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMachineQueryResult = `-- name: CreateMachineQueryResult :one
INSERT INTO machine_query_results (
    uuid,
    node_id,
    query
) VALUES (
    $1, $2, $3
)
RETURNING id, uuid, node_id, query, status, results, error, dispatched_at, completed_at, created_at, updated_at
`

type CreateMachineQueryResultParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	NodeID int64     `db:"node_id" json:"node_id"`
	Query  string    `db:"query" json:"query"`
}

func (q *Queries) CreateMachineQueryResult(ctx context.Context, arg CreateMachineQueryResultParams) (MachineQueryResult, error) {
	row := q.db.QueryRowContext(ctx, createMachineQueryResult, arg.Uuid, arg.NodeID, arg.Query)
	var i MachineQueryResult
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeID,
		&i.Query,
		&i.Status,
		&i.Results,
		&i.Error,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMachineQueryResultByNodeAndUUID = `-- name: DeleteMachineQueryResultByNodeAndUUID :execrows
DELETE FROM machine_query_results
USING nodes
WHERE machine_query_results.node_id = nodes.id
  AND nodes.uuid = $1
  AND machine_query_results.uuid = $2
`

type DeleteMachineQueryResultByNodeAndUUIDParams struct {
	NodeUuid  uuid.UUID `db:"node_uuid" json:"node_uuid"`
	QueryUuid uuid.UUID `db:"query_uuid" json:"query_uuid"`
}

func (q *Queries) DeleteMachineQueryResultByNodeAndUUID(ctx context.Context, arg DeleteMachineQueryResultByNodeAndUUIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMachineQueryResultByNodeAndUUID, arg.NodeUuid, arg.QueryUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listMachineQueryResultsByNodeUUID = `-- name: ListMachineQueryResultsByNodeUUID :many
WITH filtered AS (
    SELECT machine_query_results.id, machine_query_results.uuid, machine_query_results.node_id, machine_query_results.query, machine_query_results.status, machine_query_results.results, machine_query_results.error, machine_query_results.dispatched_at, machine_query_results.completed_at, machine_query_results.created_at, machine_query_results.updated_at
    FROM machine_query_results
    JOIN nodes ON nodes.id = machine_query_results.node_id
    WHERE nodes.uuid = $3
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.uuid, filtered.node_id, filtered.query, filtered.status, filtered.results, filtered.error, filtered.dispatched_at, filtered.completed_at, filtered.created_at, filtered.updated_at, total.total_count
FROM filtered, total
ORDER BY filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListMachineQueryResultsByNodeUUIDParams struct {
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
	NodeUuid    uuid.UUID `db:"node_uuid" json:"node_uuid"`
}

type ListMachineQueryResultsByNodeUUIDRow struct {
	ID           int64                 `db:"id" json:"id"`
	Uuid         uuid.UUID             `db:"uuid" json:"uuid"`
	NodeID       int64                 `db:"node_id" json:"node_id"`
	Query        string                `db:"query" json:"query"`
	Status       string                `db:"status" json:"status"`
	Results      pqtype.NullRawMessage `db:"results" json:"results"`
	Error        string                `db:"error" json:"error"`
	DispatchedAt sql.NullTime          `db:"dispatched_at" json:"dispatched_at"`
	CompletedAt  sql.NullTime          `db:"completed_at" json:"completed_at"`
	CreatedAt    time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time             `db:"updated_at" json:"updated_at"`
	TotalCount   int64                 `db:"total_count" json:"total_count"`
}

func (q *Queries) ListMachineQueryResultsByNodeUUID(ctx context.Context, arg ListMachineQueryResultsByNodeUUIDParams) ([]ListMachineQueryResultsByNodeUUIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMachineQueryResultsByNodeUUID, arg.OffsetCount, arg.LimitCount, arg.NodeUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachineQueryResultsByNodeUUIDRow
	for rows.Next() {
		var i ListMachineQueryResultsByNodeUUIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NodeID,
			&i.Query,
			&i.Status,
			&i.Results,
			&i.Error,
			&i.DispatchedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMachineQueryResults = `-- name: ListPendingMachineQueryResults :many
SELECT id, uuid, node_id, query, status, results, error, dispatched_at, completed_at, created_at, updated_at
FROM machine_query_results
WHERE node_id = $1
  AND status = 'pending'
  AND dispatched_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListPendingMachineQueryResults(ctx context.Context, nodeID int64) ([]MachineQueryResult, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMachineQueryResults, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MachineQueryResult
	for rows.Next() {
		var i MachineQueryResult
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NodeID,
			&i.Query,
			&i.Status,
			&i.Results,
			&i.Error,
			&i.DispatchedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMachineQueryResultsDispatched = `-- name: MarkMachineQueryResultsDispatched :exec
UPDATE machine_query_results
SET dispatched_at = COALESCE(dispatched_at, now()),
    updated_at = now()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkMachineQueryResultsDispatched(ctx context.Context, ids []int64) error {
	_, err := q.db.ExecContext(ctx, markMachineQueryResultsDispatched, pq.Array(ids))
	return err
}
