// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type DeviceOwner struct {
	ID          int64     `db:"id" json:"id"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Email       string    `db:"email" json:"email"`
	ExternalID  string    `db:"external_id" json:"external_id"`
	Department  string    `db:"department" json:"department"`
	Title       string    `db:"title" json:"title"`
	Phone       string    `db:"phone" json:"phone"`
	Notes       string    `db:"notes" json:"notes"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type Group struct {
	ID          int64     `db:"id" json:"id"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type GroupMembership struct {
	GroupID   int64     `db:"group_id" json:"group_id"`
	NodeID    int64     `db:"node_id" json:"node_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type MachineQueryResult struct {
	ID           int64                 `db:"id" json:"id"`
	Uuid         uuid.UUID             `db:"uuid" json:"uuid"`
	NodeID       int64                 `db:"node_id" json:"node_id"`
	Query        string                `db:"query" json:"query"`
	Status       string                `db:"status" json:"status"`
	Results      pqtype.NullRawMessage `db:"results" json:"results"`
	Error        string                `db:"error" json:"error"`
	DispatchedAt sql.NullTime          `db:"dispatched_at" json:"dispatched_at"`
	CompletedAt  sql.NullTime          `db:"completed_at" json:"completed_at"`
	CreatedAt    time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time             `db:"updated_at" json:"updated_at"`
}

type Node struct {
	ID                int64        `db:"id" json:"id"`
	Uuid              uuid.UUID    `db:"uuid" json:"uuid"`
	NodeKey           uuid.UUID    `db:"node_key" json:"node_key"`
	HostIdentifier    string       `db:"host_identifier" json:"host_identifier"`
	Hostname          string       `db:"hostname" json:"hostname"`
	Platform          string       `db:"platform" json:"platform"`
	OsName            string       `db:"os_name" json:"os_name"`
	OsVersion         string       `db:"os_version" json:"os_version"`
	OsqueryVersion    string       `db:"osquery_version" json:"osquery_version"`
	HardwareSerial    string       `db:"hardware_serial" json:"hardware_serial"`
	EnrolledAt        time.Time    `db:"enrolled_at" json:"enrolled_at"`
	LastSeenAt        sql.NullTime `db:"last_seen_at" json:"last_seen_at"`
	LastPolicyCheckAt sql.NullTime `db:"last_policy_check_at" json:"last_policy_check_at"`
	CreatedAt         time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time    `db:"updated_at" json:"updated_at"`
}

type NodeInventory struct {
	NodeID             int64         `db:"node_id" json:"node_id"`
	OwnerID            sql.NullInt64 `db:"owner_id" json:"owner_id"`
	InternalTrackingID string        `db:"internal_tracking_id" json:"internal_tracking_id"`
	Notes              string        `db:"notes" json:"notes"`
	CreatedAt          time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time     `db:"updated_at" json:"updated_at"`
}

type NodeMetric struct {
	NodeID      int64           `db:"node_id" json:"node_id"`
	Kind        string          `db:"kind" json:"kind"`
	Value       json.RawMessage `db:"value" json:"value"`
	CollectedAt time.Time       `db:"collected_at" json:"collected_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
}

type OsqueryStatusLog struct {
	ID           int64        `db:"id" json:"id"`
	Uuid         uuid.UUID    `db:"uuid" json:"uuid"`
	NodeID       int64        `db:"node_id" json:"node_id"`
	CalendarTime string       `db:"calendar_time" json:"calendar_time"`
	FileName     string       `db:"file_name" json:"file_name"`
	Line         int32        `db:"line" json:"line"`
	Message      string       `db:"message" json:"message"`
	Severity     int32        `db:"severity" json:"severity"`
	UnixTime     sql.NullTime `db:"unix_time" json:"unix_time"`
	Version      string       `db:"version" json:"version"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
}

type Policy struct {
	ID          int64     `db:"id" json:"id"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Query       string    `db:"query" json:"query"`
	Description string    `db:"description" json:"description"`
	Resolution  string    `db:"resolution" json:"resolution"`
	Platform    string    `db:"platform" json:"platform"`
	Enabled     bool      `db:"enabled" json:"enabled"`
	IsSystem    bool      `db:"is_system" json:"is_system"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type PolicyGroup struct {
	PolicyID  int64     `db:"policy_id" json:"policy_id"`
	GroupID   int64     `db:"group_id" json:"group_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type PolicyMembership struct {
	PolicyID  int64        `db:"policy_id" json:"policy_id"`
	NodeID    int64        `db:"node_id" json:"node_id"`
	Passes    sql.NullBool `db:"passes" json:"passes"`
	LastError string       `db:"last_error" json:"last_error"`
	CheckedAt time.Time    `db:"checked_at" json:"checked_at"`
	UpdatedAt time.Time    `db:"updated_at" json:"updated_at"`
}

type QuerySchema struct {
	ScheduleUuid     uuid.UUID       `db:"schedule_uuid" json:"schedule_uuid"`
	SqlVersion       int32           `db:"sql_version" json:"sql_version"`
	Columns          json.RawMessage `db:"columns" json:"columns"`
	FirstObservedAt  time.Time       `db:"first_observed_at" json:"first_observed_at"`
	LastObservedAt   time.Time       `db:"last_observed_at" json:"last_observed_at"`
	RowCountEstimate int64           `db:"row_count_estimate" json:"row_count_estimate"`
}

type Schedule struct {
	ID              int64     `db:"id" json:"id"`
	Uuid            uuid.UUID `db:"uuid" json:"uuid"`
	Name            string    `db:"name" json:"name"`
	Sql             string    `db:"sql" json:"sql"`
	Description     string    `db:"description" json:"description"`
	IntervalSeconds int32     `db:"interval_seconds" json:"interval_seconds"`
	Platform        string    `db:"platform" json:"platform"`
	Version         string    `db:"version" json:"version"`
	Shard           int32     `db:"shard" json:"shard"`
	Denylist        bool      `db:"denylist" json:"denylist"`
	Removed         bool      `db:"removed" json:"removed"`
	Snapshot        bool      `db:"snapshot" json:"snapshot"`
	Enabled         bool      `db:"enabled" json:"enabled"`
	IsSystem        bool      `db:"is_system" json:"is_system"`
	SqlVersion      int32     `db:"sql_version" json:"sql_version"`
	RetentionDays   int32     `db:"retention_days" json:"retention_days"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

type ScheduleGroup struct {
	ScheduleID int64     `db:"schedule_id" json:"schedule_id"`
	GroupID    int64     `db:"group_id" json:"group_id"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type YaraScan struct {
	ID             int64         `db:"id" json:"id"`
	Uuid           uuid.UUID     `db:"uuid" json:"uuid"`
	GroupID        sql.NullInt64 `db:"group_id" json:"group_id"`
	Path           string        `db:"path" json:"path"`
	RuleUrls       []string      `db:"rule_urls" json:"rule_urls"`
	Status         string        `db:"status" json:"status"`
	TargetCount    int32         `db:"target_count" json:"target_count"`
	CompletedCount int32         `db:"completed_count" json:"completed_count"`
	MatchCount     int32         `db:"match_count" json:"match_count"`
	Error          string        `db:"error" json:"error"`
	CreatedAt      time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time     `db:"updated_at" json:"updated_at"`
	CompletedAt    sql.NullTime  `db:"completed_at" json:"completed_at"`
}

type YaraScanMatch struct {
	ID        int64     `db:"id" json:"id"`
	ScanID    int64     `db:"scan_id" json:"scan_id"`
	NodeID    int64     `db:"node_id" json:"node_id"`
	Path      string    `db:"path" json:"path"`
	Matches   string    `db:"matches" json:"matches"`
	Count     int32     `db:"count" json:"count"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type YaraScanTarget struct {
	ScanID       int64        `db:"scan_id" json:"scan_id"`
	NodeID       int64        `db:"node_id" json:"node_id"`
	Status       string       `db:"status" json:"status"`
	DispatchedAt sql.NullTime `db:"dispatched_at" json:"dispatched_at"`
	CompletedAt  sql.NullTime `db:"completed_at" json:"completed_at"`
	Error        string       `db:"error" json:"error"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time    `db:"updated_at" json:"updated_at"`
}

type YaraSignatureSource struct {
	ID        int64         `db:"id" json:"id"`
	Uuid      uuid.UUID     `db:"uuid" json:"uuid"`
	GroupID   sql.NullInt64 `db:"group_id" json:"group_id"`
	Url       string        `db:"url" json:"url"`
	Label     string        `db:"label" json:"label"`
	Enabled   bool          `db:"enabled" json:"enabled"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
}
