// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Node struct {
	ID             int32          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	HostIdentifier sql.NullString `db:"host_identifier" json:"host_identifier"`
	OsName         sql.NullString `db:"os_name" json:"os_name"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
}

type OsVersionInfo struct {
	ID           int32          `db:"id" json:"id"`
	OsID         sql.NullString `db:"os_id" json:"os_id"`
	Codename     sql.NullString `db:"codename" json:"codename"`
	Major        sql.NullString `db:"major" json:"major"`
	Minor        sql.NullString `db:"minor" json:"minor"`
	Name         sql.NullString `db:"name" json:"name"`
	Patch        sql.NullString `db:"patch" json:"patch"`
	Platform     sql.NullString `db:"platform" json:"platform"`
	PlatformLike sql.NullString `db:"platform_like" json:"platform_like"`
	Version      sql.NullString `db:"version" json:"version"`
	NodeFk       int32          `db:"node_fk" json:"node_fk"`
}

type OsqueryInfo struct {
	ID            int32          `db:"id" json:"id"`
	BuildDistro   sql.NullString `db:"build_distro" json:"build_distro"`
	BuildPlatform sql.NullString `db:"build_platform" json:"build_platform"`
	ConfigHash    sql.NullString `db:"config_hash" json:"config_hash"`
	ConfigValid   sql.NullString `db:"config_valid" json:"config_valid"`
	Extensions    sql.NullString `db:"extensions" json:"extensions"`
	InstanceID    sql.NullString `db:"instance_id" json:"instance_id"`
	Pid           sql.NullString `db:"pid" json:"pid"`
	StartTime     sql.NullString `db:"start_time" json:"start_time"`
	Uuid          string         `db:"uuid" json:"uuid"`
	Version       sql.NullString `db:"version" json:"version"`
	Watcher       sql.NullString `db:"watcher" json:"watcher"`
	NodeFk        int32          `db:"node_fk" json:"node_fk"`
}

type PlatformInfo struct {
	ID         int32          `db:"id" json:"id"`
	Address    sql.NullString `db:"address" json:"address"`
	Date       sql.NullString `db:"date" json:"date"`
	Extra      sql.NullString `db:"extra" json:"extra"`
	Revision   sql.NullString `db:"revision" json:"revision"`
	Size       sql.NullString `db:"size" json:"size"`
	Vendor     sql.NullString `db:"vendor" json:"vendor"`
	Version    sql.NullString `db:"version" json:"version"`
	VolumeSize sql.NullString `db:"volume_size" json:"volume_size"`
	NodeFk     int32          `db:"node_fk" json:"node_fk"`
}

type SystemInfo struct {
	ID               int32          `db:"id" json:"id"`
	ComputerName     sql.NullString `db:"computer_name" json:"computer_name"`
	CpuBrand         sql.NullString `db:"cpu_brand" json:"cpu_brand"`
	CpuLogicalCores  sql.NullString `db:"cpu_logical_cores" json:"cpu_logical_cores"`
	CpuPhysicalCores sql.NullString `db:"cpu_physical_cores" json:"cpu_physical_cores"`
	CpuSubtype       sql.NullString `db:"cpu_subtype" json:"cpu_subtype"`
	CpuType          sql.NullString `db:"cpu_type" json:"cpu_type"`
	HardwareModel    sql.NullString `db:"hardware_model" json:"hardware_model"`
	HardwareSerial   sql.NullString `db:"hardware_serial" json:"hardware_serial"`
	HardwareVendor   sql.NullString `db:"hardware_vendor" json:"hardware_vendor"`
	HardwareVersion  sql.NullString `db:"hardware_version" json:"hardware_version"`
	Hostname         sql.NullString `db:"hostname" json:"hostname"`
	LocalHostname    sql.NullString `db:"local_hostname" json:"local_hostname"`
	PhysicalMemory   sql.NullString `db:"physical_memory" json:"physical_memory"`
	Uuid             string         `db:"uuid" json:"uuid"`
	NodeFk           int32          `db:"node_fk" json:"node_fk"`
}
