// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Node struct {
	ID             int64        `db:"id" json:"id"`
	Uuid           uuid.UUID    `db:"uuid" json:"uuid"`
	NodeKey        uuid.UUID    `db:"node_key" json:"node_key"`
	HostIdentifier string       `db:"host_identifier" json:"host_identifier"`
	Hostname       string       `db:"hostname" json:"hostname"`
	Platform       string       `db:"platform" json:"platform"`
	OsName         string       `db:"os_name" json:"os_name"`
	OsVersion      string       `db:"os_version" json:"os_version"`
	OsqueryVersion string       `db:"osquery_version" json:"osquery_version"`
	HardwareSerial string       `db:"hardware_serial" json:"hardware_serial"`
	EnrolledAt     time.Time    `db:"enrolled_at" json:"enrolled_at"`
	LastSeenAt     sql.NullTime `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt      time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time    `db:"updated_at" json:"updated_at"`
}

type OsqueryResultBatch struct {
	ID           int64        `db:"id" json:"id"`
	Uuid         uuid.UUID    `db:"uuid" json:"uuid"`
	NodeID       int64        `db:"node_id" json:"node_id"`
	ScheduleName string       `db:"schedule_name" json:"schedule_name"`
	Action       string       `db:"action" json:"action"`
	CalendarTime string       `db:"calendar_time" json:"calendar_time"`
	Counter      int64        `db:"counter" json:"counter"`
	Epoch        int64        `db:"epoch" json:"epoch"`
	Numerics     bool         `db:"numerics" json:"numerics"`
	UnixTime     sql.NullTime `db:"unix_time" json:"unix_time"`
	IsSystem     bool         `db:"is_system" json:"is_system"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
}

type OsqueryResultCell struct {
	ID         int64  `db:"id" json:"id"`
	RowID      int64  `db:"row_id" json:"row_id"`
	ColumnName string `db:"column_name" json:"column_name"`
	ValueText  string `db:"value_text" json:"value_text"`
}

type OsqueryResultRow struct {
	ID       int64 `db:"id" json:"id"`
	BatchID  int64 `db:"batch_id" json:"batch_id"`
	RowIndex int32 `db:"row_index" json:"row_index"`
}

type OsqueryStatusLog struct {
	ID           int64        `db:"id" json:"id"`
	Uuid         uuid.UUID    `db:"uuid" json:"uuid"`
	NodeID       int64        `db:"node_id" json:"node_id"`
	CalendarTime string       `db:"calendar_time" json:"calendar_time"`
	FileName     string       `db:"file_name" json:"file_name"`
	Line         int32        `db:"line" json:"line"`
	Message      string       `db:"message" json:"message"`
	Severity     int32        `db:"severity" json:"severity"`
	UnixTime     sql.NullTime `db:"unix_time" json:"unix_time"`
	Version      string       `db:"version" json:"version"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
}

type Query struct {
	ID          int64     `db:"id" json:"id"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Sql         string    `db:"sql" json:"sql"`
	Description string    `db:"description" json:"description"`
	IsSystem    bool      `db:"is_system" json:"is_system"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type Schedule struct {
	ID              int64     `db:"id" json:"id"`
	Uuid            uuid.UUID `db:"uuid" json:"uuid"`
	QueryID         int64     `db:"query_id" json:"query_id"`
	Name            string    `db:"name" json:"name"`
	IntervalSeconds int32     `db:"interval_seconds" json:"interval_seconds"`
	Platform        string    `db:"platform" json:"platform"`
	Version         string    `db:"version" json:"version"`
	Shard           int32     `db:"shard" json:"shard"`
	Denylist        bool      `db:"denylist" json:"denylist"`
	Removed         bool      `db:"removed" json:"removed"`
	Snapshot        bool      `db:"snapshot" json:"snapshot"`
	Enabled         bool      `db:"enabled" json:"enabled"`
	IsSystem        bool      `db:"is_system" json:"is_system"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}
