// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: nodes.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (
    host_identifier,
    hostname,
    platform,
    os_name,
    os_version,
    osquery_version,
    hardware_serial
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (host_identifier) DO UPDATE SET
    hostname = EXCLUDED.hostname,
    platform = EXCLUDED.platform,
    os_name = EXCLUDED.os_name,
    os_version = EXCLUDED.os_version,
    osquery_version = EXCLUDED.osquery_version,
    hardware_serial = EXCLUDED.hardware_serial,
    last_seen_at = now(),
    updated_at = now()
RETURNING id, uuid, node_key, host_identifier, hostname, platform, os_name, os_version, osquery_version, hardware_serial, enrolled_at, last_seen_at, last_policy_check_at, created_at, updated_at, display_name
`

type CreateNodeParams struct {
	HostIdentifier string `db:"host_identifier" json:"host_identifier"`
	Hostname       string `db:"hostname" json:"hostname"`
	Platform       string `db:"platform" json:"platform"`
	OsName         string `db:"os_name" json:"os_name"`
	OsVersion      string `db:"os_version" json:"os_version"`
	OsqueryVersion string `db:"osquery_version" json:"osquery_version"`
	HardwareSerial string `db:"hardware_serial" json:"hardware_serial"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.HostIdentifier,
		arg.Hostname,
		arg.Platform,
		arg.OsName,
		arg.OsVersion,
		arg.OsqueryVersion,
		arg.HardwareSerial,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeKey,
		&i.HostIdentifier,
		&i.Hostname,
		&i.Platform,
		&i.OsName,
		&i.OsVersion,
		&i.OsqueryVersion,
		&i.HardwareSerial,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.LastPolicyCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const deleteNodeByUUID = `-- name: DeleteNodeByUUID :execrows
DELETE FROM nodes WHERE uuid = $1
`

func (q *Queries) DeleteNodeByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNodeByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, uuid, node_key, host_identifier, hostname, platform, os_name, os_version, osquery_version, hardware_serial, enrolled_at, last_seen_at, last_policy_check_at, created_at, updated_at, display_name FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeKey,
		&i.HostIdentifier,
		&i.Hostname,
		&i.Platform,
		&i.OsName,
		&i.OsVersion,
		&i.OsqueryVersion,
		&i.HardwareSerial,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.LastPolicyCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const getNodeByKey = `-- name: GetNodeByKey :one
SELECT id, uuid, node_key, host_identifier, hostname, platform, os_name, os_version, osquery_version, hardware_serial, enrolled_at, last_seen_at, last_policy_check_at, created_at, updated_at, display_name FROM nodes WHERE node_key = $1
`

func (q *Queries) GetNodeByKey(ctx context.Context, nodeKey uuid.UUID) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByKey, nodeKey)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeKey,
		&i.HostIdentifier,
		&i.Hostname,
		&i.Platform,
		&i.OsName,
		&i.OsVersion,
		&i.OsqueryVersion,
		&i.HardwareSerial,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.LastPolicyCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const getNodeByUUID = `-- name: GetNodeByUUID :one
SELECT id, uuid, node_key, host_identifier, hostname, platform, os_name, os_version, osquery_version, hardware_serial, enrolled_at, last_seen_at, last_policy_check_at, created_at, updated_at, display_name FROM nodes WHERE uuid = $1
`

func (q *Queries) GetNodeByUUID(ctx context.Context, argUuid uuid.UUID) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByUUID, argUuid)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeKey,
		&i.HostIdentifier,
		&i.Hostname,
		&i.Platform,
		&i.OsName,
		&i.OsVersion,
		&i.OsqueryVersion,
		&i.HardwareSerial,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.LastPolicyCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
WITH filtered AS (
    SELECT
        nodes.id,
        nodes.uuid,
        nodes.node_key,
        nodes.host_identifier,
        nodes.hostname,
        nodes.display_name,
        nodes.platform,
        nodes.os_name,
        nodes.os_version,
        nodes.osquery_version,
        nodes.hardware_serial,
        nodes.enrolled_at,
        nodes.last_seen_at,
        nodes.last_policy_check_at,
        nodes.created_at,
        nodes.updated_at,
        device_owners.display_name AS owner_display_name,
        device_owners.email AS owner_email
    FROM nodes
    LEFT JOIN node_inventory ON node_inventory.node_id = nodes.id
    LEFT JOIN device_owners ON device_owners.id = node_inventory.owner_id
    WHERE (
        $6::text = ''
        OR nodes.hostname ILIKE '%' || $6::text || '%'
        OR nodes.display_name ILIKE '%' || $6::text || '%'
        OR nodes.host_identifier ILIKE '%' || $6::text || '%'
        OR node_inventory.internal_tracking_id ILIKE '%' || $6::text || '%'
        OR device_owners.display_name ILIKE '%' || $6::text || '%'
        OR device_owners.email ILIKE '%' || $6::text || '%'
    )
      AND (
        $7::text = ''
        OR nodes.platform = $7::text
    )
      AND (
        $8::text = ''
        OR device_owners.uuid::text = $8::text
    )
      AND (
        $9::text = ''
        OR ($9::text = 'assigned' AND node_inventory.owner_id IS NOT NULL)
        OR ($9::text = 'unassigned' AND node_inventory.owner_id IS NULL)
    )
      AND (
        $10::text = ''
        OR lower(trim(device_owners.email)) = lower(trim($10::text))
    )
),
scored AS (
    SELECT
        filtered.id, filtered.uuid, filtered.node_key, filtered.host_identifier, filtered.hostname, filtered.display_name, filtered.platform, filtered.os_name, filtered.os_version, filtered.osquery_version, filtered.hardware_serial, filtered.enrolled_at, filtered.last_seen_at, filtered.last_policy_check_at, filtered.created_at, filtered.updated_at, filtered.owner_display_name, filtered.owner_email,
        coalesce(score.weighted_passing, 0)::bigint AS weighted_passing,
        coalesce(score.weighted_total, 0)::bigint AS weighted_total
    FROM filtered
    LEFT JOIN LATERAL (
        SELECT
            coalesce(sum(
                CASE policies.severity
                    WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
                END
            ) FILTER (WHERE policy_membership.passes = true AND policy_membership.checked_at >= $11::timestamptz), 0)::bigint AS weighted_passing,
            coalesce(sum(
                CASE policies.severity
                    WHEN 'critical' THEN 8 WHEN 'high' THEN 5 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 WHEN 'info' THEN 1 ELSE 3
                END
            ), 0)::bigint AS weighted_total
        FROM policies
        LEFT JOIN policy_membership
            ON policy_membership.policy_id = policies.id
           AND policy_membership.node_id = filtered.id
        WHERE policies.enabled = true
            AND (
                policies.platform IN ('all', 'any')
                OR policies.platform = filtered.platform
                OR (policies.platform = 'linux' AND filtered.platform NOT IN ('', 'darwin', 'windows'))
                OR (policies.platform = 'posix' AND filtered.platform NOT IN ('', 'windows'))
            )
            AND (
                NOT EXISTS (
                    SELECT 1
                    FROM policy_groups
                    WHERE policy_groups.policy_id = policies.id
                )
                OR EXISTS (
                    SELECT 1
                    FROM policy_groups
                    JOIN group_membership ON group_membership.group_id = policy_groups.group_id
                    WHERE policy_groups.policy_id = policies.id
                      AND group_membership.node_id = filtered.id
                )
            )
    ) score ON true
)
SELECT
    scored.id, scored.uuid, scored.node_key, scored.host_identifier, scored.hostname, scored.display_name, scored.platform, scored.os_name, scored.os_version, scored.osquery_version, scored.hardware_serial, scored.enrolled_at, scored.last_seen_at, scored.last_policy_check_at, scored.created_at, scored.updated_at, scored.owner_display_name, scored.owner_email, scored.weighted_passing, scored.weighted_total,
    count(*) OVER () AS total_count
FROM scored
ORDER BY
    CASE WHEN $1::text = 'name' AND $2::text = 'asc'
        THEN lower(COALESCE(NULLIF(scored.display_name, ''), scored.hostname)) END ASC NULLS LAST,
    CASE WHEN $1::text = 'name' AND $2::text = 'desc'
        THEN lower(COALESCE(NULLIF(scored.display_name, ''), scored.hostname)) END DESC NULLS LAST,
    CASE WHEN $1::text = 'owner' AND $2::text = 'asc'
        THEN lower(COALESCE(NULLIF(scored.owner_display_name, ''), scored.owner_email)) END ASC NULLS LAST,
    CASE WHEN $1::text = 'owner' AND $2::text = 'desc'
        THEN lower(COALESCE(NULLIF(scored.owner_display_name, ''), scored.owner_email)) END DESC NULLS LAST,
    CASE WHEN $1::text = 'score' AND $2::text = 'asc'
        THEN (CASE WHEN scored.weighted_total > 0 THEN scored.weighted_passing::float / scored.weighted_total ELSE NULL END) END ASC NULLS LAST,
    CASE WHEN $1::text = 'score' AND $2::text = 'desc'
        THEN (CASE WHEN scored.weighted_total > 0 THEN scored.weighted_passing::float / scored.weighted_total ELSE NULL END) END DESC NULLS LAST,
    CASE WHEN $1::text = 'status' AND $2::text = 'asc'
        THEN (CASE WHEN scored.last_seen_at IS NULL AND scored.enrolled_at IS NULL THEN 2 WHEN COALESCE(scored.last_seen_at, scored.enrolled_at) >= $3::timestamptz THEN 0 ELSE 1 END) END ASC NULLS LAST,
    CASE WHEN $1::text = 'status' AND $2::text = 'desc'
        THEN (CASE WHEN scored.last_seen_at IS NULL AND scored.enrolled_at IS NULL THEN 2 WHEN COALESCE(scored.last_seen_at, scored.enrolled_at) >= $3::timestamptz THEN 0 ELSE 1 END) END DESC NULLS LAST,
    scored.created_at DESC, scored.uuid
LIMIT $5 OFFSET $4
`

type ListNodesParams struct {
	SortBy       string    `db:"sort_by" json:"sort_by"`
	SortDir      string    `db:"sort_dir" json:"sort_dir"`
	OnlineCutoff time.Time `db:"online_cutoff" json:"online_cutoff"`
	OffsetCount  int32     `db:"offset_count" json:"offset_count"`
	LimitCount   int32     `db:"limit_count" json:"limit_count"`
	Query        string    `db:"query" json:"query"`
	Platform     string    `db:"platform" json:"platform"`
	OwnerUuid    string    `db:"owner_uuid" json:"owner_uuid"`
	Assigned     string    `db:"assigned" json:"assigned"`
	OwnerEmail   string    `db:"owner_email" json:"owner_email"`
	StaleCutoff  time.Time `db:"stale_cutoff" json:"stale_cutoff"`
}

type ListNodesRow struct {
	ID                int64          `db:"id" json:"id"`
	Uuid              uuid.UUID      `db:"uuid" json:"uuid"`
	NodeKey           uuid.UUID      `db:"node_key" json:"node_key"`
	HostIdentifier    string         `db:"host_identifier" json:"host_identifier"`
	Hostname          string         `db:"hostname" json:"hostname"`
	DisplayName       string         `db:"display_name" json:"display_name"`
	Platform          string         `db:"platform" json:"platform"`
	OsName            string         `db:"os_name" json:"os_name"`
	OsVersion         string         `db:"os_version" json:"os_version"`
	OsqueryVersion    string         `db:"osquery_version" json:"osquery_version"`
	HardwareSerial    string         `db:"hardware_serial" json:"hardware_serial"`
	EnrolledAt        time.Time      `db:"enrolled_at" json:"enrolled_at"`
	LastSeenAt        sql.NullTime   `db:"last_seen_at" json:"last_seen_at"`
	LastPolicyCheckAt sql.NullTime   `db:"last_policy_check_at" json:"last_policy_check_at"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
	OwnerDisplayName  sql.NullString `db:"owner_display_name" json:"owner_display_name"`
	OwnerEmail        sql.NullString `db:"owner_email" json:"owner_email"`
	WeightedPassing   int64          `db:"weighted_passing" json:"weighted_passing"`
	WeightedTotal     int64          `db:"weighted_total" json:"weighted_total"`
	TotalCount        int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]ListNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodes,
		arg.SortBy,
		arg.SortDir,
		arg.OnlineCutoff,
		arg.OffsetCount,
		arg.LimitCount,
		arg.Query,
		arg.Platform,
		arg.OwnerUuid,
		arg.Assigned,
		arg.OwnerEmail,
		arg.StaleCutoff,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesRow
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NodeKey,
			&i.HostIdentifier,
			&i.Hostname,
			&i.DisplayName,
			&i.Platform,
			&i.OsName,
			&i.OsVersion,
			&i.OsqueryVersion,
			&i.HardwareSerial,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.LastPolicyCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerDisplayName,
			&i.OwnerEmail,
			&i.WeightedPassing,
			&i.WeightedTotal,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByIDs = `-- name: ListNodesByIDs :many
SELECT id, uuid, COALESCE(NULLIF(display_name, ''), hostname) AS hostname FROM nodes WHERE id = ANY($1::bigint[])
`

type ListNodesByIDsRow struct {
	ID       int64     `db:"id" json:"id"`
	Uuid     uuid.UUID `db:"uuid" json:"uuid"`
	Hostname string    `db:"hostname" json:"hostname"`
}

func (q *Queries) ListNodesByIDs(ctx context.Context, ids []int64) ([]ListNodesByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesByIDsRow
	for rows.Next() {
		var i ListNodesByIDsRow
		if err := rows.Scan(&i.ID, &i.Uuid, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchNodesByIdentityPattern = `-- name: MatchNodesByIdentityPattern :many
SELECT id, uuid::text AS uuid, hostname
FROM nodes
WHERE hostname ILIKE '%' || $1::text || '%' ESCAPE '\'
   OR display_name ILIKE '%' || $1::text || '%' ESCAPE '\'
   OR uuid::text ILIKE '%' || $1::text || '%' ESCAPE '\'
   OR host_identifier ILIKE '%' || $1::text || '%' ESCAPE '\'
ORDER BY hostname ASC
LIMIT $2::int
`

type MatchNodesByIdentityPatternParams struct {
	Pattern  string `db:"pattern" json:"pattern"`
	MaxCount int32  `db:"max_count" json:"max_count"`
}

type MatchNodesByIdentityPatternRow struct {
	ID       int64  `db:"id" json:"id"`
	Uuid     string `db:"uuid" json:"uuid"`
	Hostname string `db:"hostname" json:"hostname"`
}

// @pattern is expected to be pre-escaped against LIKE wildcards by the caller.
func (q *Queries) MatchNodesByIdentityPattern(ctx context.Context, arg MatchNodesByIdentityPatternParams) ([]MatchNodesByIdentityPatternRow, error) {
	rows, err := q.db.QueryContext(ctx, matchNodesByIdentityPattern, arg.Pattern, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchNodesByIdentityPatternRow
	for rows.Next() {
		var i MatchNodesByIdentityPatternRow
		if err := rows.Scan(&i.ID, &i.Uuid, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchNode = `-- name: TouchNode :exec
UPDATE nodes SET last_seen_at = now(), updated_at = now() WHERE node_key = $1
`

func (q *Queries) TouchNode(ctx context.Context, nodeKey uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchNode, nodeKey)
	return err
}

const updateNodeDisplayNameByUUID = `-- name: UpdateNodeDisplayNameByUUID :one
UPDATE nodes SET
    display_name = $1,
    updated_at = now()
WHERE uuid = $2
RETURNING id, uuid, node_key, host_identifier, hostname, platform, os_name, os_version, osquery_version, hardware_serial, enrolled_at, last_seen_at, last_policy_check_at, created_at, updated_at, display_name
`

type UpdateNodeDisplayNameByUUIDParams struct {
	DisplayName string    `db:"display_name" json:"display_name"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) UpdateNodeDisplayNameByUUID(ctx context.Context, arg UpdateNodeDisplayNameByUUIDParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNodeDisplayNameByUUID, arg.DisplayName, arg.Uuid)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeKey,
		&i.HostIdentifier,
		&i.Hostname,
		&i.Platform,
		&i.OsName,
		&i.OsVersion,
		&i.OsqueryVersion,
		&i.HardwareSerial,
		&i.EnrolledAt,
		&i.LastSeenAt,
		&i.LastPolicyCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const updateNodeSystemInfo = `-- name: UpdateNodeSystemInfo :exec
UPDATE nodes SET
    platform        = COALESCE(NULLIF($1::text, ''), platform),
    os_name         = COALESCE(NULLIF($2::text, ''), os_name),
    os_version      = COALESCE(NULLIF($3::text, ''), os_version),
    osquery_version = COALESCE(NULLIF($4::text, ''), osquery_version),
    hardware_serial = COALESCE(NULLIF($5::text, ''), hardware_serial),
    updated_at      = now()
WHERE id = $6
`

type UpdateNodeSystemInfoParams struct {
	Platform       string `db:"platform" json:"platform"`
	OsName         string `db:"os_name" json:"os_name"`
	OsVersion      string `db:"os_version" json:"os_version"`
	OsqueryVersion string `db:"osquery_version" json:"osquery_version"`
	HardwareSerial string `db:"hardware_serial" json:"hardware_serial"`
	NodeID         int64  `db:"node_id" json:"node_id"`
}

func (q *Queries) UpdateNodeSystemInfo(ctx context.Context, arg UpdateNodeSystemInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeSystemInfo,
		arg.Platform,
		arg.OsName,
		arg.OsVersion,
		arg.OsqueryVersion,
		arg.HardwareSerial,
		arg.NodeID,
	)
	return err
}
