// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_metrics.sql

package repo

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const listNodeMetricsByNodeUUID = `-- name: ListNodeMetricsByNodeUUID :many
SELECT m.kind, m.value, m.collected_at, m.updated_at
FROM node_metrics m
JOIN nodes n ON n.id = m.node_id
WHERE n.uuid = $1
ORDER BY m.kind
`

type ListNodeMetricsByNodeUUIDRow struct {
	Kind        string          `db:"kind" json:"kind"`
	Value       json.RawMessage `db:"value" json:"value"`
	CollectedAt time.Time       `db:"collected_at" json:"collected_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListNodeMetricsByNodeUUID(ctx context.Context, argUuid uuid.UUID) ([]ListNodeMetricsByNodeUUIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeMetricsByNodeUUID, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeMetricsByNodeUUIDRow
	for rows.Next() {
		var i ListNodeMetricsByNodeUUIDRow
		if err := rows.Scan(
			&i.Kind,
			&i.Value,
			&i.CollectedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNodeMetric = `-- name: UpsertNodeMetric :exec
INSERT INTO node_metrics (node_id, kind, value, collected_at, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (node_id, kind) DO UPDATE SET
    value = EXCLUDED.value,
    collected_at = EXCLUDED.collected_at,
    updated_at = now()
`

type UpsertNodeMetricParams struct {
	NodeID      int64           `db:"node_id" json:"node_id"`
	Kind        string          `db:"kind" json:"kind"`
	Value       json.RawMessage `db:"value" json:"value"`
	CollectedAt time.Time       `db:"collected_at" json:"collected_at"`
}

func (q *Queries) UpsertNodeMetric(ctx context.Context, arg UpsertNodeMetricParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeMetric,
		arg.NodeID,
		arg.Kind,
		arg.Value,
		arg.CollectedAt,
	)
	return err
}
