// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: node.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addNode = `-- name: AddNode :one
INSERT INTO
    nodes (host_identifier, os_name)
VALUES
    ($1, $2) RETURNING id, uuid, host_identifier, os_name, created_at
`

type AddNodeParams struct {
	HostIdentifier sql.NullString `db:"host_identifier" json:"host_identifier"`
	OsName         sql.NullString `db:"os_name" json:"os_name"`
}

func (q *Queries) AddNode(ctx context.Context, arg AddNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, addNode, arg.HostIdentifier, arg.OsName)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.HostIdentifier,
		&i.OsName,
		&i.CreatedAt,
	)
	return i, err
}

const addOSQueryInfo = `-- name: AddOSQueryInfo :one
INSERT INTO
    osquery_info (
        build_distro,
        build_platform,
        config_hash,
        config_valid,
        extensions,
        instance_id,
        pid,
        start_time,
        uuid,
        version,
        watcher,
        node_fk
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, uuid, build_distro, build_platform, config_hash, config_valid, extensions, instance_id, pid, start_time, version, watcher, node_fk
`

type AddOSQueryInfoParams struct {
	BuildDistro   sql.NullString `db:"build_distro" json:"build_distro"`
	BuildPlatform sql.NullString `db:"build_platform" json:"build_platform"`
	ConfigHash    sql.NullString `db:"config_hash" json:"config_hash"`
	ConfigValid   sql.NullString `db:"config_valid" json:"config_valid"`
	Extensions    sql.NullString `db:"extensions" json:"extensions"`
	InstanceID    sql.NullString `db:"instance_id" json:"instance_id"`
	Pid           sql.NullString `db:"pid" json:"pid"`
	StartTime     sql.NullString `db:"start_time" json:"start_time"`
	Uuid          uuid.UUID      `db:"uuid" json:"uuid"`
	Version       sql.NullString `db:"version" json:"version"`
	Watcher       sql.NullString `db:"watcher" json:"watcher"`
	NodeFk        int32          `db:"node_fk" json:"node_fk"`
}

func (q *Queries) AddOSQueryInfo(ctx context.Context, arg AddOSQueryInfoParams) (OsqueryInfo, error) {
	row := q.db.QueryRowContext(ctx, addOSQueryInfo,
		arg.BuildDistro,
		arg.BuildPlatform,
		arg.ConfigHash,
		arg.ConfigValid,
		arg.Extensions,
		arg.InstanceID,
		arg.Pid,
		arg.StartTime,
		arg.Uuid,
		arg.Version,
		arg.Watcher,
		arg.NodeFk,
	)
	var i OsqueryInfo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.BuildDistro,
		&i.BuildPlatform,
		&i.ConfigHash,
		&i.ConfigValid,
		&i.Extensions,
		&i.InstanceID,
		&i.Pid,
		&i.StartTime,
		&i.Version,
		&i.Watcher,
		&i.NodeFk,
	)
	return i, err
}

const addOSVersionInfo = `-- name: AddOSVersionInfo :one
INSERT INTO
    os_version_info (
        os_id,
        codename,
        major,
        minor,
        name,
        patch,
        platform,
        platform_like,
        version,
        node_fk
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, uuid, os_id, codename, major, minor, name, patch, platform, platform_like, version, node_fk
`

type AddOSVersionInfoParams struct {
	OsID         sql.NullString `db:"os_id" json:"os_id"`
	Codename     sql.NullString `db:"codename" json:"codename"`
	Major        sql.NullString `db:"major" json:"major"`
	Minor        sql.NullString `db:"minor" json:"minor"`
	Name         sql.NullString `db:"name" json:"name"`
	Patch        sql.NullString `db:"patch" json:"patch"`
	Platform     sql.NullString `db:"platform" json:"platform"`
	PlatformLike sql.NullString `db:"platform_like" json:"platform_like"`
	Version      sql.NullString `db:"version" json:"version"`
	NodeFk       int32          `db:"node_fk" json:"node_fk"`
}

func (q *Queries) AddOSVersionInfo(ctx context.Context, arg AddOSVersionInfoParams) (OsVersionInfo, error) {
	row := q.db.QueryRowContext(ctx, addOSVersionInfo,
		arg.OsID,
		arg.Codename,
		arg.Major,
		arg.Minor,
		arg.Name,
		arg.Patch,
		arg.Platform,
		arg.PlatformLike,
		arg.Version,
		arg.NodeFk,
	)
	var i OsVersionInfo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OsID,
		&i.Codename,
		&i.Major,
		&i.Minor,
		&i.Name,
		&i.Patch,
		&i.Platform,
		&i.PlatformLike,
		&i.Version,
		&i.NodeFk,
	)
	return i, err
}

const addPlatformInfo = `-- name: AddPlatformInfo :one
INSERT INTO
    platform_info (
        address,
        date,
        extra,
        revision,
        size,
        vendor,
        version,
        volume_size,
        node_fk
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, uuid, address, date, extra, revision, size, vendor, version, volume_size, node_fk
`

type AddPlatformInfoParams struct {
	Address    sql.NullString `db:"address" json:"address"`
	Date       sql.NullString `db:"date" json:"date"`
	Extra      sql.NullString `db:"extra" json:"extra"`
	Revision   sql.NullString `db:"revision" json:"revision"`
	Size       sql.NullString `db:"size" json:"size"`
	Vendor     sql.NullString `db:"vendor" json:"vendor"`
	Version    sql.NullString `db:"version" json:"version"`
	VolumeSize sql.NullString `db:"volume_size" json:"volume_size"`
	NodeFk     int32          `db:"node_fk" json:"node_fk"`
}

func (q *Queries) AddPlatformInfo(ctx context.Context, arg AddPlatformInfoParams) (PlatformInfo, error) {
	row := q.db.QueryRowContext(ctx, addPlatformInfo,
		arg.Address,
		arg.Date,
		arg.Extra,
		arg.Revision,
		arg.Size,
		arg.Vendor,
		arg.Version,
		arg.VolumeSize,
		arg.NodeFk,
	)
	var i PlatformInfo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Address,
		&i.Date,
		&i.Extra,
		&i.Revision,
		&i.Size,
		&i.Vendor,
		&i.Version,
		&i.VolumeSize,
		&i.NodeFk,
	)
	return i, err
}

const addSystemInfo = `-- name: AddSystemInfo :one
INSERT INTO
    system_info (
        computer_name,
        cpu_brand,
        cpu_logical_cores,
        cpu_physical_cores,
        cpu_subtype,
        cpu_type,
        hardware_model,
        hardware_serial,
        hardware_vendor,
        hardware_version,
        hostname,
        local_hostname,
        physical_memory,
        uuid,
        node_fk
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING id, uuid, computer_name, cpu_brand, cpu_logical_cores, cpu_physical_cores, cpu_subtype, cpu_type, hardware_model, hardware_serial, hardware_vendor, hardware_version, hostname, local_hostname, physical_memory, node_fk
`

type AddSystemInfoParams struct {
	ComputerName     sql.NullString `db:"computer_name" json:"computer_name"`
	CpuBrand         sql.NullString `db:"cpu_brand" json:"cpu_brand"`
	CpuLogicalCores  sql.NullString `db:"cpu_logical_cores" json:"cpu_logical_cores"`
	CpuPhysicalCores sql.NullString `db:"cpu_physical_cores" json:"cpu_physical_cores"`
	CpuSubtype       sql.NullString `db:"cpu_subtype" json:"cpu_subtype"`
	CpuType          sql.NullString `db:"cpu_type" json:"cpu_type"`
	HardwareModel    sql.NullString `db:"hardware_model" json:"hardware_model"`
	HardwareSerial   sql.NullString `db:"hardware_serial" json:"hardware_serial"`
	HardwareVendor   sql.NullString `db:"hardware_vendor" json:"hardware_vendor"`
	HardwareVersion  sql.NullString `db:"hardware_version" json:"hardware_version"`
	Hostname         sql.NullString `db:"hostname" json:"hostname"`
	LocalHostname    sql.NullString `db:"local_hostname" json:"local_hostname"`
	PhysicalMemory   sql.NullString `db:"physical_memory" json:"physical_memory"`
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
	NodeFk           int32          `db:"node_fk" json:"node_fk"`
}

func (q *Queries) AddSystemInfo(ctx context.Context, arg AddSystemInfoParams) (SystemInfo, error) {
	row := q.db.QueryRowContext(ctx, addSystemInfo,
		arg.ComputerName,
		arg.CpuBrand,
		arg.CpuLogicalCores,
		arg.CpuPhysicalCores,
		arg.CpuSubtype,
		arg.CpuType,
		arg.HardwareModel,
		arg.HardwareSerial,
		arg.HardwareVendor,
		arg.HardwareVersion,
		arg.Hostname,
		arg.LocalHostname,
		arg.PhysicalMemory,
		arg.Uuid,
		arg.NodeFk,
	)
	var i SystemInfo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ComputerName,
		&i.CpuBrand,
		&i.CpuLogicalCores,
		&i.CpuPhysicalCores,
		&i.CpuSubtype,
		&i.CpuType,
		&i.HardwareModel,
		&i.HardwareSerial,
		&i.HardwareVendor,
		&i.HardwareVersion,
		&i.Hostname,
		&i.LocalHostname,
		&i.PhysicalMemory,
		&i.NodeFk,
	)
	return i, err
}

const getNodeByUUID = `-- name: GetNodeByUUID :one
WITH node AS (
    SELECT
        id, uuid, host_identifier, os_name, created_at
    FROM
        nodes
    WHERE
        nodes.uuid = $1
) SELECT
    node.id, node.uuid, node.host_identifier, node.os_name, node.created_at,
    os_version_info.os_id,
    os_version_info.codename,
    os_version_info.major,
    os_version_info.minor,
    os_version_info.platform,
    os_version_info.platform_like,
    os_version_info.version,
    system_info.computer_name,
    system_info.cpu_logical_cores,
    system_info.cpu_physical_cores,
    system_info.hostname,
    system_info.local_hostname,
    system_info.physical_memory
    FROM
        node, os_version_info, osquery_info, system_info
    WHERE
        node.id = os_version_info.node_fk
        AND node.id = osquery_info.node_fk
        AND node.id = system_info.node_fk
`

type GetNodeByUUIDRow struct {
	ID               int32          `db:"id" json:"id"`
	Uuid             uuid.UUID      `db:"uuid" json:"uuid"`
	HostIdentifier   sql.NullString `db:"host_identifier" json:"host_identifier"`
	OsName           sql.NullString `db:"os_name" json:"os_name"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	OsID             sql.NullString `db:"os_id" json:"os_id"`
	Codename         sql.NullString `db:"codename" json:"codename"`
	Major            sql.NullString `db:"major" json:"major"`
	Minor            sql.NullString `db:"minor" json:"minor"`
	Platform         sql.NullString `db:"platform" json:"platform"`
	PlatformLike     sql.NullString `db:"platform_like" json:"platform_like"`
	Version          sql.NullString `db:"version" json:"version"`
	ComputerName     sql.NullString `db:"computer_name" json:"computer_name"`
	CpuLogicalCores  sql.NullString `db:"cpu_logical_cores" json:"cpu_logical_cores"`
	CpuPhysicalCores sql.NullString `db:"cpu_physical_cores" json:"cpu_physical_cores"`
	Hostname         sql.NullString `db:"hostname" json:"hostname"`
	LocalHostname    sql.NullString `db:"local_hostname" json:"local_hostname"`
	PhysicalMemory   sql.NullString `db:"physical_memory" json:"physical_memory"`
}

func (q *Queries) GetNodeByUUID(ctx context.Context, argUuid uuid.UUID) (GetNodeByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeByUUID, argUuid)
	var i GetNodeByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.HostIdentifier,
		&i.OsName,
		&i.CreatedAt,
		&i.OsID,
		&i.Codename,
		&i.Major,
		&i.Minor,
		&i.Platform,
		&i.PlatformLike,
		&i.Version,
		&i.ComputerName,
		&i.CpuLogicalCores,
		&i.CpuPhysicalCores,
		&i.Hostname,
		&i.LocalHostname,
		&i.PhysicalMemory,
	)
	return i, err
}

const getOSQueryInfoByNode = `-- name: GetOSQueryInfoByNode :one
SELECT id, uuid, build_distro, build_platform, config_hash, config_valid, extensions, instance_id, pid, start_time, version, watcher, node_fk FROM osquery_info WHERE node_fk = $1
`

func (q *Queries) GetOSQueryInfoByNode(ctx context.Context, nodeFk int32) (OsqueryInfo, error) {
	row := q.db.QueryRowContext(ctx, getOSQueryInfoByNode, nodeFk)
	var i OsqueryInfo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.BuildDistro,
		&i.BuildPlatform,
		&i.ConfigHash,
		&i.ConfigValid,
		&i.Extensions,
		&i.InstanceID,
		&i.Pid,
		&i.StartTime,
		&i.Version,
		&i.Watcher,
		&i.NodeFk,
	)
	return i, err
}

const getOSVersionInfoByNode = `-- name: GetOSVersionInfoByNode :one
SELECT id, uuid, os_id, codename, major, minor, name, patch, platform, platform_like, version, node_fk FROM os_version_info WHERE node_fk = $1
`

func (q *Queries) GetOSVersionInfoByNode(ctx context.Context, nodeFk int32) (OsVersionInfo, error) {
	row := q.db.QueryRowContext(ctx, getOSVersionInfoByNode, nodeFk)
	var i OsVersionInfo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OsID,
		&i.Codename,
		&i.Major,
		&i.Minor,
		&i.Name,
		&i.Patch,
		&i.Platform,
		&i.PlatformLike,
		&i.Version,
		&i.NodeFk,
	)
	return i, err
}

const getPlatformInfoByNode = `-- name: GetPlatformInfoByNode :one
SELECT id, uuid, address, date, extra, revision, size, vendor, version, volume_size, node_fk FROM platform_info WHERE node_fk = $1
`

func (q *Queries) GetPlatformInfoByNode(ctx context.Context, nodeFk int32) (PlatformInfo, error) {
	row := q.db.QueryRowContext(ctx, getPlatformInfoByNode, nodeFk)
	var i PlatformInfo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Address,
		&i.Date,
		&i.Extra,
		&i.Revision,
		&i.Size,
		&i.Vendor,
		&i.Version,
		&i.VolumeSize,
		&i.NodeFk,
	)
	return i, err
}

const getSystemInfoByNode = `-- name: GetSystemInfoByNode :one
SELECT id, uuid, computer_name, cpu_brand, cpu_logical_cores, cpu_physical_cores, cpu_subtype, cpu_type, hardware_model, hardware_serial, hardware_vendor, hardware_version, hostname, local_hostname, physical_memory, node_fk FROM system_info WHERE node_fk = $1
`

func (q *Queries) GetSystemInfoByNode(ctx context.Context, nodeFk int32) (SystemInfo, error) {
	row := q.db.QueryRowContext(ctx, getSystemInfoByNode, nodeFk)
	var i SystemInfo
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ComputerName,
		&i.CpuBrand,
		&i.CpuLogicalCores,
		&i.CpuPhysicalCores,
		&i.CpuSubtype,
		&i.CpuType,
		&i.HardwareModel,
		&i.HardwareSerial,
		&i.HardwareVendor,
		&i.HardwareVersion,
		&i.Hostname,
		&i.LocalHostname,
		&i.PhysicalMemory,
		&i.NodeFk,
	)
	return i, err
}
