// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: osquery_logs.sql

package repo

import (
	"context"
	"database/sql"
)

const createResultBatch = `-- name: CreateResultBatch :one
INSERT INTO osquery_result_batches (
    node_id,
    schedule_name,
    action,
    calendar_time,
    counter,
    epoch,
    numerics,
    unix_time,
    is_system
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, uuid, node_id, schedule_name, action, calendar_time, counter, epoch, numerics, unix_time, is_system, created_at
`

type CreateResultBatchParams struct {
	NodeID       int64        `db:"node_id" json:"node_id"`
	ScheduleName string       `db:"schedule_name" json:"schedule_name"`
	Action       string       `db:"action" json:"action"`
	CalendarTime string       `db:"calendar_time" json:"calendar_time"`
	Counter      int64        `db:"counter" json:"counter"`
	Epoch        int64        `db:"epoch" json:"epoch"`
	Numerics     bool         `db:"numerics" json:"numerics"`
	UnixTime     sql.NullTime `db:"unix_time" json:"unix_time"`
	IsSystem     bool         `db:"is_system" json:"is_system"`
}

func (q *Queries) CreateResultBatch(ctx context.Context, arg CreateResultBatchParams) (OsqueryResultBatch, error) {
	row := q.db.QueryRowContext(ctx, createResultBatch,
		arg.NodeID,
		arg.ScheduleName,
		arg.Action,
		arg.CalendarTime,
		arg.Counter,
		arg.Epoch,
		arg.Numerics,
		arg.UnixTime,
		arg.IsSystem,
	)
	var i OsqueryResultBatch
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeID,
		&i.ScheduleName,
		&i.Action,
		&i.CalendarTime,
		&i.Counter,
		&i.Epoch,
		&i.Numerics,
		&i.UnixTime,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createResultCell = `-- name: CreateResultCell :exec
INSERT INTO osquery_result_cells (row_id, column_name, value_text)
VALUES ($1, $2, $3)
`

type CreateResultCellParams struct {
	RowID      int64  `db:"row_id" json:"row_id"`
	ColumnName string `db:"column_name" json:"column_name"`
	ValueText  string `db:"value_text" json:"value_text"`
}

func (q *Queries) CreateResultCell(ctx context.Context, arg CreateResultCellParams) error {
	_, err := q.db.ExecContext(ctx, createResultCell, arg.RowID, arg.ColumnName, arg.ValueText)
	return err
}

const createResultRow = `-- name: CreateResultRow :one
INSERT INTO osquery_result_rows (batch_id, row_index)
VALUES ($1, $2)
RETURNING id, batch_id, row_index
`

type CreateResultRowParams struct {
	BatchID  int64 `db:"batch_id" json:"batch_id"`
	RowIndex int32 `db:"row_index" json:"row_index"`
}

func (q *Queries) CreateResultRow(ctx context.Context, arg CreateResultRowParams) (OsqueryResultRow, error) {
	row := q.db.QueryRowContext(ctx, createResultRow, arg.BatchID, arg.RowIndex)
	var i OsqueryResultRow
	err := row.Scan(&i.ID, &i.BatchID, &i.RowIndex)
	return i, err
}

const createStatusLog = `-- name: CreateStatusLog :one
INSERT INTO osquery_status_logs (
    node_id,
    calendar_time,
    file_name,
    line,
    message,
    severity,
    unix_time,
    version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, uuid, node_id, calendar_time, file_name, line, message, severity, unix_time, version, created_at
`

type CreateStatusLogParams struct {
	NodeID       int64        `db:"node_id" json:"node_id"`
	CalendarTime string       `db:"calendar_time" json:"calendar_time"`
	FileName     string       `db:"file_name" json:"file_name"`
	Line         int32        `db:"line" json:"line"`
	Message      string       `db:"message" json:"message"`
	Severity     int32        `db:"severity" json:"severity"`
	UnixTime     sql.NullTime `db:"unix_time" json:"unix_time"`
	Version      string       `db:"version" json:"version"`
}

func (q *Queries) CreateStatusLog(ctx context.Context, arg CreateStatusLogParams) (OsqueryStatusLog, error) {
	row := q.db.QueryRowContext(ctx, createStatusLog,
		arg.NodeID,
		arg.CalendarTime,
		arg.FileName,
		arg.Line,
		arg.Message,
		arg.Severity,
		arg.UnixTime,
		arg.Version,
	)
	var i OsqueryStatusLog
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeID,
		&i.CalendarTime,
		&i.FileName,
		&i.Line,
		&i.Message,
		&i.Severity,
		&i.UnixTime,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
