// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: osquery_logs.sql

package repo

import (
	"context"
	"database/sql"
)

const createStatusLog = `-- name: CreateStatusLog :one
INSERT INTO osquery_status_logs (
    node_id,
    calendar_time,
    file_name,
    line,
    message,
    severity,
    unix_time,
    version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, uuid, node_id, calendar_time, file_name, line, message, severity, unix_time, version, created_at
`

type CreateStatusLogParams struct {
	NodeID       int64        `db:"node_id" json:"node_id"`
	CalendarTime string       `db:"calendar_time" json:"calendar_time"`
	FileName     string       `db:"file_name" json:"file_name"`
	Line         int32        `db:"line" json:"line"`
	Message      string       `db:"message" json:"message"`
	Severity     int32        `db:"severity" json:"severity"`
	UnixTime     sql.NullTime `db:"unix_time" json:"unix_time"`
	Version      string       `db:"version" json:"version"`
}

func (q *Queries) CreateStatusLog(ctx context.Context, arg CreateStatusLogParams) (OsqueryStatusLog, error) {
	row := q.db.QueryRowContext(ctx, createStatusLog,
		arg.NodeID,
		arg.CalendarTime,
		arg.FileName,
		arg.Line,
		arg.Message,
		arg.Severity,
		arg.UnixTime,
		arg.Version,
	)
	var i OsqueryStatusLog
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NodeID,
		&i.CalendarTime,
		&i.FileName,
		&i.Line,
		&i.Message,
		&i.Severity,
		&i.UnixTime,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
