// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (
    name,
    query,
    description,
    resolution,
    platform,
    enabled,
    is_system
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, uuid, name, query, description, resolution, platform, enabled, is_system, created_at, updated_at
`

type CreatePolicyParams struct {
	Name        string `db:"name" json:"name"`
	Query       string `db:"query" json:"query"`
	Description string `db:"description" json:"description"`
	Resolution  string `db:"resolution" json:"resolution"`
	Platform    string `db:"platform" json:"platform"`
	Enabled     bool   `db:"enabled" json:"enabled"`
	IsSystem    bool   `db:"is_system" json:"is_system"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, createPolicy,
		arg.Name,
		arg.Query,
		arg.Description,
		arg.Resolution,
		arg.Platform,
		arg.Enabled,
		arg.IsSystem,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Query,
		&i.Description,
		&i.Resolution,
		&i.Platform,
		&i.Enabled,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePolicyByUUID = `-- name: DeletePolicyByUUID :execrows
DELETE FROM policies WHERE uuid = $1 AND is_system = false
`

func (q *Queries) DeletePolicyByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePolicyByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT id, uuid, name, query, description, resolution, platform, enabled, is_system, created_at, updated_at FROM policies WHERE id = $1
`

func (q *Queries) GetPolicyByID(ctx context.Context, id int64) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicyByID, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Query,
		&i.Description,
		&i.Resolution,
		&i.Platform,
		&i.Enabled,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyByUUID = `-- name: GetPolicyByUUID :one
SELECT id, uuid, name, query, description, resolution, platform, enabled, is_system, created_at, updated_at FROM policies WHERE uuid = $1
`

func (q *Queries) GetPolicyByUUID(ctx context.Context, argUuid uuid.UUID) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicyByUUID, argUuid)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Query,
		&i.Description,
		&i.Resolution,
		&i.Platform,
		&i.Enabled,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPoliciesForNode = `-- name: ListEnabledPoliciesForNode :many
SELECT id, uuid, name, query, description, resolution, platform, enabled, is_system, created_at, updated_at
FROM policies
WHERE enabled = true
  AND (
    platform IN ('all', 'any')
    OR platform = $1
    OR (platform = 'linux' AND $1 NOT IN ('', 'darwin', 'windows'))
    OR (platform = 'posix' AND $1 NOT IN ('', 'windows'))
  )
  AND (
    NOT EXISTS (
        SELECT 1
        FROM policy_groups
        WHERE policy_groups.policy_id = policies.id
    )
    OR EXISTS (
        SELECT 1
        FROM policy_groups
        JOIN group_membership ON group_membership.group_id = policy_groups.group_id
        WHERE policy_groups.policy_id = policies.id
          AND group_membership.node_id = $2
    )
  )
ORDER BY name
`

type ListEnabledPoliciesForNodeParams struct {
	NodePlatform string `db:"node_platform" json:"node_platform"`
	NodeID       int64  `db:"node_id" json:"node_id"`
}

func (q *Queries) ListEnabledPoliciesForNode(ctx context.Context, arg ListEnabledPoliciesForNodeParams) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPoliciesForNode, arg.NodePlatform, arg.NodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Query,
			&i.Description,
			&i.Resolution,
			&i.Platform,
			&i.Enabled,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByPolicyResponse = `-- name: ListNodesByPolicyResponse :many
WITH target_policy AS (
    SELECT id, uuid, name, query, description, resolution, platform, enabled, is_system, created_at, updated_at
    FROM policies
    WHERE policies.uuid = $3
),
filtered AS (
    SELECT
        nodes.id,
        nodes.uuid,
        nodes.node_key,
        nodes.host_identifier,
        nodes.hostname,
        nodes.platform,
        nodes.os_name,
        nodes.os_version,
        nodes.osquery_version,
        nodes.hardware_serial,
        nodes.enrolled_at,
        nodes.last_seen_at,
        nodes.last_policy_check_at,
        nodes.created_at,
        nodes.updated_at,
        CASE
            WHEN policy_membership.policy_id IS NULL THEN 'unknown'
            WHEN policy_membership.checked_at < now() - $4::text::interval THEN 'unknown'
            WHEN policy_membership.passes = true THEN 'passing'
            WHEN policy_membership.passes = false THEN 'failing'
            ELSE 'unknown'
        END::text AS response,
        policy_membership.checked_at,
        policy_membership.last_error,
        COALESCE(policy_membership.checked_at < now() - $4::text::interval, false)::boolean AS stale
    FROM target_policy
    JOIN nodes ON (
        target_policy.platform IN ('all', 'any')
        OR target_policy.platform = nodes.platform
        OR (target_policy.platform = 'linux' AND nodes.platform NOT IN ('', 'darwin', 'windows'))
        OR (target_policy.platform = 'posix' AND nodes.platform NOT IN ('', 'windows'))
    )
    LEFT JOIN policy_membership
        ON policy_membership.policy_id = target_policy.id
       AND policy_membership.node_id = nodes.id
    WHERE (
        NOT EXISTS (
            SELECT 1
            FROM policy_groups
            WHERE policy_groups.policy_id = target_policy.id
        )
        OR EXISTS (
            SELECT 1
            FROM policy_groups
            JOIN group_membership ON group_membership.group_id = policy_groups.group_id
            WHERE policy_groups.policy_id = target_policy.id
              AND group_membership.node_id = nodes.id
        )
    )
),
response_filtered AS (
    SELECT id, uuid, node_key, host_identifier, hostname, platform, os_name, os_version, osquery_version, hardware_serial, enrolled_at, last_seen_at, last_policy_check_at, created_at, updated_at, response, checked_at, last_error, stale
    FROM filtered
    WHERE $5::text = ''
       OR response = $5::text
),
total AS (
    SELECT count(*) AS total_count FROM response_filtered
)
SELECT response_filtered.id, response_filtered.uuid, response_filtered.node_key, response_filtered.host_identifier, response_filtered.hostname, response_filtered.platform, response_filtered.os_name, response_filtered.os_version, response_filtered.osquery_version, response_filtered.hardware_serial, response_filtered.enrolled_at, response_filtered.last_seen_at, response_filtered.last_policy_check_at, response_filtered.created_at, response_filtered.updated_at, response_filtered.response, response_filtered.checked_at, response_filtered.last_error, response_filtered.stale, total.total_count
FROM response_filtered, total
ORDER BY response_filtered.hostname, response_filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListNodesByPolicyResponseParams struct {
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
	PolicyUuid  uuid.UUID `db:"policy_uuid" json:"policy_uuid"`
	StaleAfter  string    `db:"stale_after" json:"stale_after"`
	Response    string    `db:"response" json:"response"`
}

type ListNodesByPolicyResponseRow struct {
	ID                int64          `db:"id" json:"id"`
	Uuid              uuid.UUID      `db:"uuid" json:"uuid"`
	NodeKey           uuid.UUID      `db:"node_key" json:"node_key"`
	HostIdentifier    string         `db:"host_identifier" json:"host_identifier"`
	Hostname          string         `db:"hostname" json:"hostname"`
	Platform          string         `db:"platform" json:"platform"`
	OsName            string         `db:"os_name" json:"os_name"`
	OsVersion         string         `db:"os_version" json:"os_version"`
	OsqueryVersion    string         `db:"osquery_version" json:"osquery_version"`
	HardwareSerial    string         `db:"hardware_serial" json:"hardware_serial"`
	EnrolledAt        time.Time      `db:"enrolled_at" json:"enrolled_at"`
	LastSeenAt        sql.NullTime   `db:"last_seen_at" json:"last_seen_at"`
	LastPolicyCheckAt sql.NullTime   `db:"last_policy_check_at" json:"last_policy_check_at"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
	Response          string         `db:"response" json:"response"`
	CheckedAt         sql.NullTime   `db:"checked_at" json:"checked_at"`
	LastError         sql.NullString `db:"last_error" json:"last_error"`
	Stale             bool           `db:"stale" json:"stale"`
	TotalCount        int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNodesByPolicyResponse(ctx context.Context, arg ListNodesByPolicyResponseParams) ([]ListNodesByPolicyResponseRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByPolicyResponse,
		arg.OffsetCount,
		arg.LimitCount,
		arg.PolicyUuid,
		arg.StaleAfter,
		arg.Response,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesByPolicyResponseRow
	for rows.Next() {
		var i ListNodesByPolicyResponseRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NodeKey,
			&i.HostIdentifier,
			&i.Hostname,
			&i.Platform,
			&i.OsName,
			&i.OsVersion,
			&i.OsqueryVersion,
			&i.HardwareSerial,
			&i.EnrolledAt,
			&i.LastSeenAt,
			&i.LastPolicyCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Response,
			&i.CheckedAt,
			&i.LastError,
			&i.Stale,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesForNode = `-- name: ListPoliciesForNode :many
WITH target_node AS (
    SELECT id, uuid, node_key, host_identifier, hostname, platform, os_name, os_version, osquery_version, hardware_serial, enrolled_at, last_seen_at, created_at, updated_at, last_policy_check_at
    FROM nodes
    WHERE nodes.uuid = $2
)
SELECT
    policies.id,
    policies.uuid,
    policies.name,
    policies.query,
    policies.description,
    policies.resolution,
    policies.platform,
    policies.enabled,
    policies.is_system,
    policies.created_at,
    policies.updated_at,
    CASE
        WHEN policy_membership.policy_id IS NULL THEN 'unknown'
        WHEN policy_membership.checked_at < now() - $1::text::interval THEN 'unknown'
        WHEN policy_membership.passes = true THEN 'passing'
        WHEN policy_membership.passes = false THEN 'failing'
        ELSE 'unknown'
    END::text AS response,
    policy_membership.checked_at,
    policy_membership.last_error,
    COALESCE(policy_membership.checked_at < now() - $1::text::interval, false)::boolean AS stale
FROM target_node
JOIN policies ON policies.enabled = true
    AND (
        policies.platform IN ('all', 'any')
        OR policies.platform = target_node.platform
        OR (policies.platform = 'linux' AND target_node.platform NOT IN ('', 'darwin', 'windows'))
        OR (policies.platform = 'posix' AND target_node.platform NOT IN ('', 'windows'))
    )
    AND (
        NOT EXISTS (
            SELECT 1
            FROM policy_groups
            WHERE policy_groups.policy_id = policies.id
        )
        OR EXISTS (
            SELECT 1
            FROM policy_groups
            JOIN group_membership ON group_membership.group_id = policy_groups.group_id
            WHERE policy_groups.policy_id = policies.id
              AND group_membership.node_id = target_node.id
        )
    )
LEFT JOIN policy_membership
    ON policy_membership.policy_id = policies.id
   AND policy_membership.node_id = target_node.id
ORDER BY policies.name
`

type ListPoliciesForNodeParams struct {
	StaleAfter string    `db:"stale_after" json:"stale_after"`
	NodeUuid   uuid.UUID `db:"node_uuid" json:"node_uuid"`
}

type ListPoliciesForNodeRow struct {
	ID          int64          `db:"id" json:"id"`
	Uuid        uuid.UUID      `db:"uuid" json:"uuid"`
	Name        string         `db:"name" json:"name"`
	Query       string         `db:"query" json:"query"`
	Description string         `db:"description" json:"description"`
	Resolution  string         `db:"resolution" json:"resolution"`
	Platform    string         `db:"platform" json:"platform"`
	Enabled     bool           `db:"enabled" json:"enabled"`
	IsSystem    bool           `db:"is_system" json:"is_system"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
	Response    string         `db:"response" json:"response"`
	CheckedAt   sql.NullTime   `db:"checked_at" json:"checked_at"`
	LastError   sql.NullString `db:"last_error" json:"last_error"`
	Stale       bool           `db:"stale" json:"stale"`
}

func (q *Queries) ListPoliciesForNode(ctx context.Context, arg ListPoliciesForNodeParams) ([]ListPoliciesForNodeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPoliciesForNode, arg.StaleAfter, arg.NodeUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesForNodeRow
	for rows.Next() {
		var i ListPoliciesForNodeRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Query,
			&i.Description,
			&i.Resolution,
			&i.Platform,
			&i.Enabled,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Response,
			&i.CheckedAt,
			&i.LastError,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesWithCounts = `-- name: ListPoliciesWithCounts :many
WITH filtered AS (
    SELECT id, uuid, name, query, description, resolution, platform, enabled, is_system, created_at, updated_at
    FROM policies
),
effective_targets AS (
    SELECT
        filtered.id AS policy_id,
        nodes.id AS node_id
    FROM filtered
    JOIN nodes ON (
        filtered.platform IN ('all', 'any')
        OR filtered.platform = nodes.platform
        OR (filtered.platform = 'linux' AND nodes.platform NOT IN ('', 'darwin', 'windows'))
        OR (filtered.platform = 'posix' AND nodes.platform NOT IN ('', 'windows'))
    )
    WHERE (
        NOT EXISTS (
            SELECT 1
            FROM policy_groups
            WHERE policy_groups.policy_id = filtered.id
        )
        OR EXISTS (
            SELECT 1
            FROM policy_groups
            JOIN group_membership ON group_membership.group_id = policy_groups.group_id
            WHERE policy_groups.policy_id = filtered.id
              AND group_membership.node_id = nodes.id
        )
    )
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT
    filtered.id,
    filtered.uuid,
    filtered.name,
    filtered.query,
    filtered.description,
    filtered.resolution,
    filtered.platform,
    filtered.enabled,
    filtered.is_system,
    filtered.created_at,
    filtered.updated_at,
    count(effective_targets.node_id) FILTER (
        WHERE policy_membership.passes = true
          AND policy_membership.checked_at >= now() - $1::text::interval
    )::bigint AS passing_count,
    count(effective_targets.node_id) FILTER (
        WHERE policy_membership.passes = false
          AND policy_membership.checked_at >= now() - $1::text::interval
    )::bigint AS failing_count,
    count(effective_targets.node_id) FILTER (
        WHERE effective_targets.node_id IS NOT NULL
          AND (
            policy_membership.policy_id IS NULL
            OR policy_membership.passes IS NULL
            OR policy_membership.checked_at < now() - $1::text::interval
          )
    )::bigint AS unknown_count,
    max(policy_membership.updated_at) AS last_count_updated_at,
    total.total_count
FROM filtered
CROSS JOIN total
LEFT JOIN effective_targets ON effective_targets.policy_id = filtered.id
LEFT JOIN policy_membership
    ON policy_membership.policy_id = filtered.id
   AND policy_membership.node_id = effective_targets.node_id
GROUP BY
    filtered.id,
    filtered.uuid,
    filtered.name,
    filtered.query,
    filtered.description,
    filtered.resolution,
    filtered.platform,
    filtered.enabled,
    filtered.is_system,
    filtered.created_at,
    filtered.updated_at,
    total.total_count
ORDER BY filtered.created_at DESC
LIMIT $3 OFFSET $2
`

type ListPoliciesWithCountsParams struct {
	StaleAfter  string `db:"stale_after" json:"stale_after"`
	OffsetCount int32  `db:"offset_count" json:"offset_count"`
	LimitCount  int32  `db:"limit_count" json:"limit_count"`
}

type ListPoliciesWithCountsRow struct {
	ID                 int64       `db:"id" json:"id"`
	Uuid               uuid.UUID   `db:"uuid" json:"uuid"`
	Name               string      `db:"name" json:"name"`
	Query              string      `db:"query" json:"query"`
	Description        string      `db:"description" json:"description"`
	Resolution         string      `db:"resolution" json:"resolution"`
	Platform           string      `db:"platform" json:"platform"`
	Enabled            bool        `db:"enabled" json:"enabled"`
	IsSystem           bool        `db:"is_system" json:"is_system"`
	CreatedAt          time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time   `db:"updated_at" json:"updated_at"`
	PassingCount       int64       `db:"passing_count" json:"passing_count"`
	FailingCount       int64       `db:"failing_count" json:"failing_count"`
	UnknownCount       int64       `db:"unknown_count" json:"unknown_count"`
	LastCountUpdatedAt interface{} `db:"last_count_updated_at" json:"last_count_updated_at"`
	TotalCount         int64       `db:"total_count" json:"total_count"`
}

func (q *Queries) ListPoliciesWithCounts(ctx context.Context, arg ListPoliciesWithCountsParams) ([]ListPoliciesWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPoliciesWithCounts, arg.StaleAfter, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesWithCountsRow
	for rows.Next() {
		var i ListPoliciesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Query,
			&i.Description,
			&i.Resolution,
			&i.Platform,
			&i.Enabled,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PassingCount,
			&i.FailingCount,
			&i.UnknownCount,
			&i.LastCountUpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeLastPolicyCheckAt = `-- name: UpdateNodeLastPolicyCheckAt :exec
UPDATE nodes SET last_policy_check_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateNodeLastPolicyCheckAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateNodeLastPolicyCheckAt, id)
	return err
}

const updatePolicyByUUID = `-- name: UpdatePolicyByUUID :one
UPDATE policies SET
    name = $2,
    query = $3,
    description = $4,
    resolution = $5,
    platform = $6,
    enabled = $7,
    updated_at = now()
WHERE uuid = $1 AND is_system = false
RETURNING id, uuid, name, query, description, resolution, platform, enabled, is_system, created_at, updated_at
`

type UpdatePolicyByUUIDParams struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Query       string    `db:"query" json:"query"`
	Description string    `db:"description" json:"description"`
	Resolution  string    `db:"resolution" json:"resolution"`
	Platform    string    `db:"platform" json:"platform"`
	Enabled     bool      `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdatePolicyByUUID(ctx context.Context, arg UpdatePolicyByUUIDParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, updatePolicyByUUID,
		arg.Uuid,
		arg.Name,
		arg.Query,
		arg.Description,
		arg.Resolution,
		arg.Platform,
		arg.Enabled,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Query,
		&i.Description,
		&i.Resolution,
		&i.Platform,
		&i.Enabled,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPolicyMembership = `-- name: UpsertPolicyMembership :exec
INSERT INTO policy_membership (
    policy_id,
    node_id,
    passes,
    last_error,
    checked_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, now(), now()
)
ON CONFLICT (policy_id, node_id) DO UPDATE SET
    passes = EXCLUDED.passes,
    last_error = EXCLUDED.last_error,
    checked_at = EXCLUDED.checked_at,
    updated_at = now()
`

type UpsertPolicyMembershipParams struct {
	PolicyID  int64        `db:"policy_id" json:"policy_id"`
	NodeID    int64        `db:"node_id" json:"node_id"`
	Passes    sql.NullBool `db:"passes" json:"passes"`
	LastError string       `db:"last_error" json:"last_error"`
}

func (q *Queries) UpsertPolicyMembership(ctx context.Context, arg UpsertPolicyMembershipParams) error {
	_, err := q.db.ExecContext(ctx, upsertPolicyMembership,
		arg.PolicyID,
		arg.NodeID,
		arg.Passes,
		arg.LastError,
	)
	return err
}
