// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createQuery = `-- name: CreateQuery :one
INSERT INTO queries (name, sql, description, is_system)
VALUES ($1, $2, $3, $4)
RETURNING id, uuid, name, sql, description, is_system, created_at, updated_at
`

type CreateQueryParams struct {
	Name        string `db:"name" json:"name"`
	Sql         string `db:"sql" json:"sql"`
	Description string `db:"description" json:"description"`
	IsSystem    bool   `db:"is_system" json:"is_system"`
}

func (q *Queries) CreateQuery(ctx context.Context, arg CreateQueryParams) (Query, error) {
	row := q.db.QueryRowContext(ctx, createQuery,
		arg.Name,
		arg.Sql,
		arg.Description,
		arg.IsSystem,
	)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Sql,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQueryByUUID = `-- name: DeleteQueryByUUID :execrows
DELETE FROM queries WHERE uuid = $1 AND is_system = false
`

func (q *Queries) DeleteQueryByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQueryByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getQueryByID = `-- name: GetQueryByID :one
SELECT id, uuid, name, sql, description, is_system, created_at, updated_at FROM queries WHERE id = $1
`

func (q *Queries) GetQueryByID(ctx context.Context, id int64) (Query, error) {
	row := q.db.QueryRowContext(ctx, getQueryByID, id)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Sql,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueryByUUID = `-- name: GetQueryByUUID :one
SELECT id, uuid, name, sql, description, is_system, created_at, updated_at FROM queries WHERE uuid = $1
`

func (q *Queries) GetQueryByUUID(ctx context.Context, argUuid uuid.UUID) (Query, error) {
	row := q.db.QueryRowContext(ctx, getQueryByUUID, argUuid)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Sql,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQueries = `-- name: ListQueries :many
WITH filtered AS (
    SELECT id, uuid, name, sql, description, is_system, created_at, updated_at FROM queries
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.uuid, filtered.name, filtered.sql, filtered.description, filtered.is_system, filtered.created_at, filtered.updated_at, total.total_count
FROM filtered, total
ORDER BY filtered.created_at DESC
LIMIT $1 OFFSET $2
`

type ListQueriesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListQueriesRow struct {
	ID          int64     `db:"id" json:"id"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Sql         string    `db:"sql" json:"sql"`
	Description string    `db:"description" json:"description"`
	IsSystem    bool      `db:"is_system" json:"is_system"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
	TotalCount  int64     `db:"total_count" json:"total_count"`
}

func (q *Queries) ListQueries(ctx context.Context, arg ListQueriesParams) ([]ListQueriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueriesRow
	for rows.Next() {
		var i ListQueriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Sql,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQueryByUUID = `-- name: UpdateQueryByUUID :one
UPDATE queries SET
    name = $2,
    sql = $3,
    description = $4,
    updated_at = now()
WHERE uuid = $1 AND is_system = false
RETURNING id, uuid, name, sql, description, is_system, created_at, updated_at
`

type UpdateQueryByUUIDParams struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Sql         string    `db:"sql" json:"sql"`
	Description string    `db:"description" json:"description"`
}

func (q *Queries) UpdateQueryByUUID(ctx context.Context, arg UpdateQueryByUUIDParams) (Query, error) {
	row := q.db.QueryRowContext(ctx, updateQueryByUUID,
		arg.Uuid,
		arg.Name,
		arg.Sql,
		arg.Description,
	)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Sql,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
