// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"context"
)

type Querier interface {
	AddNode(ctx context.Context, arg AddNodeParams) (Node, error)
	AddOSQueryInfo(ctx context.Context, arg AddOSQueryInfoParams) (OsqueryInfo, error)
	AddOSVersionInfo(ctx context.Context, arg AddOSVersionInfoParams) (OsVersionInfo, error)
	AddPlatformInfo(ctx context.Context, arg AddPlatformInfoParams) (PlatformInfo, error)
	AddSystemInfo(ctx context.Context, arg AddSystemInfoParams) (SystemInfo, error)
}

var _ Querier = (*Queries)(nil)
