// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateQuery(ctx context.Context, arg CreateQueryParams) (Query, error)
	CreateResultBatch(ctx context.Context, arg CreateResultBatchParams) (OsqueryResultBatch, error)
	CreateResultCell(ctx context.Context, arg CreateResultCellParams) error
	CreateResultRow(ctx context.Context, arg CreateResultRowParams) (OsqueryResultRow, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateStatusLog(ctx context.Context, arg CreateStatusLogParams) (OsqueryStatusLog, error)
	DeleteQueryByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	DeleteScheduleByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	GetNodeByKey(ctx context.Context, nodeKey uuid.UUID) (Node, error)
	GetQueryByID(ctx context.Context, id int64) (Query, error)
	GetQueryByUUID(ctx context.Context, argUuid uuid.UUID) (Query, error)
	GetScheduleByUUID(ctx context.Context, argUuid uuid.UUID) (Schedule, error)
	GetScheduleWithQueryByUUID(ctx context.Context, argUuid uuid.UUID) (GetScheduleWithQueryByUUIDRow, error)
	ListEnabledSchedulesWithQueries(ctx context.Context, limit int32) ([]ListEnabledSchedulesWithQueriesRow, error)
	ListNodes(ctx context.Context, arg ListNodesParams) ([]ListNodesRow, error)
	ListQueries(ctx context.Context, arg ListQueriesParams) ([]ListQueriesRow, error)
	ListSchedulesWithQueries(ctx context.Context, arg ListSchedulesWithQueriesParams) ([]ListSchedulesWithQueriesRow, error)
	ListSystemScheduleNames(ctx context.Context) ([]string, error)
	TouchNode(ctx context.Context, nodeKey uuid.UUID) error
	UpdateQueryByUUID(ctx context.Context, arg UpdateQueryByUUIDParams) (Query, error)
	UpdateScheduleByUUID(ctx context.Context, arg UpdateScheduleByUUIDParams) (Schedule, error)
}

var _ Querier = (*Queries)(nil)
