// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query_runs.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createQueryRun = `-- name: CreateQueryRun :one
INSERT INTO query_runs (
    uuid,
    query,
    targets,
    created_by
) VALUES (
    $1, $2, $4::text::jsonb, $3
)
RETURNING id, uuid, query, targets, created_by, created_at, updated_at
`

type CreateQueryRunParams struct {
	Uuid      uuid.UUID     `db:"uuid" json:"uuid"`
	Query     string        `db:"query" json:"query"`
	CreatedBy sql.NullInt64 `db:"created_by" json:"created_by"`
	Targets   string        `db:"targets" json:"targets"`
}

func (q *Queries) CreateQueryRun(ctx context.Context, arg CreateQueryRunParams) (QueryRun, error) {
	row := q.db.QueryRowContext(ctx, createQueryRun,
		arg.Uuid,
		arg.Query,
		arg.CreatedBy,
		arg.Targets,
	)
	var i QueryRun
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Query,
		&i.Targets,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQueryRunByUUID = `-- name: DeleteQueryRunByUUID :execrows
DELETE FROM query_runs WHERE uuid = $1
`

func (q *Queries) DeleteQueryRunByUUID(ctx context.Context, runUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQueryRunByUUID, runUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getQueryRunByUUID = `-- name: GetQueryRunByUUID :one
SELECT id, uuid, query, targets, created_by, created_at, updated_at FROM query_runs WHERE uuid = $1
`

func (q *Queries) GetQueryRunByUUID(ctx context.Context, argUuid uuid.UUID) (QueryRun, error) {
	row := q.db.QueryRowContext(ctx, getQueryRunByUUID, argUuid)
	var i QueryRun
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Query,
		&i.Targets,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMachineQueryResultsByRunUUID = `-- name: ListMachineQueryResultsByRunUUID :many
SELECT
    machine_query_results.id, machine_query_results.uuid, machine_query_results.node_id,
    machine_query_results.query, machine_query_results.status, machine_query_results.error,
    machine_query_results.row_count, machine_query_results.dispatched_at,
    machine_query_results.completed_at, machine_query_results.created_at,
    machine_query_results.updated_at, machine_query_results.run_id,
    nodes.uuid AS node_uuid,
    COALESCE(NULLIF(nodes.display_name, ''), nodes.hostname) AS hostname,
    nodes.platform AS platform
FROM machine_query_results
JOIN query_runs ON query_runs.id = machine_query_results.run_id
JOIN nodes ON nodes.id = machine_query_results.node_id
WHERE query_runs.uuid = $1
ORDER BY COALESCE(NULLIF(nodes.display_name, ''), nodes.hostname) ASC, nodes.uuid ASC
`

type ListMachineQueryResultsByRunUUIDRow struct {
	ID           int64         `db:"id" json:"id"`
	Uuid         uuid.UUID     `db:"uuid" json:"uuid"`
	NodeID       int64         `db:"node_id" json:"node_id"`
	Query        string        `db:"query" json:"query"`
	Status       string        `db:"status" json:"status"`
	Error        string        `db:"error" json:"error"`
	RowCount     int32         `db:"row_count" json:"row_count"`
	DispatchedAt sql.NullTime  `db:"dispatched_at" json:"dispatched_at"`
	CompletedAt  sql.NullTime  `db:"completed_at" json:"completed_at"`
	CreatedAt    time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time     `db:"updated_at" json:"updated_at"`
	RunID        sql.NullInt64 `db:"run_id" json:"run_id"`
	NodeUuid     uuid.UUID     `db:"node_uuid" json:"node_uuid"`
	Hostname     string        `db:"hostname" json:"hostname"`
	Platform     string        `db:"platform" json:"platform"`
}

func (q *Queries) ListMachineQueryResultsByRunUUID(ctx context.Context, runUuid uuid.UUID) ([]ListMachineQueryResultsByRunUUIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMachineQueryResultsByRunUUID, runUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachineQueryResultsByRunUUIDRow
	for rows.Next() {
		var i ListMachineQueryResultsByRunUUIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NodeID,
			&i.Query,
			&i.Status,
			&i.Error,
			&i.RowCount,
			&i.DispatchedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunID,
			&i.NodeUuid,
			&i.Hostname,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeIDsByGroupUUIDs = `-- name: ListNodeIDsByGroupUUIDs :many
SELECT DISTINCT group_membership.node_id AS id
FROM group_membership
JOIN groups ON groups.id = group_membership.group_id
WHERE groups.uuid = ANY($1::uuid[])
`

func (q *Queries) ListNodeIDsByGroupUUIDs(ctx context.Context, groupUuids []uuid.UUID) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listNodeIDsByGroupUUIDs, pq.Array(groupUuids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeIDsByPlatforms = `-- name: ListNodeIDsByPlatforms :many
SELECT id FROM nodes
WHERE 'all' = ANY($1::text[])
   OR 'any' = ANY($1::text[])
   OR platform = ANY($1::text[])
   OR ('posix' = ANY($1::text[]) AND platform NOT IN ('', 'windows'))
   OR ('linux' = ANY($1::text[]) AND platform NOT IN ('', 'darwin', 'windows'))
`

// Mirrors the platform semantics in ListEnabledPoliciesForNode: 'all'/'any'
// match everything, 'posix' matches non-windows, 'linux' matches non-darwin/windows.
func (q *Queries) ListNodeIDsByPlatforms(ctx context.Context, platforms []string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listNodeIDsByPlatforms, pq.Array(platforms))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeIDsByUUIDs = `-- name: ListNodeIDsByUUIDs :many
SELECT id FROM nodes WHERE uuid = ANY($1::uuid[])
`

func (q *Queries) ListNodeIDsByUUIDs(ctx context.Context, uuids []uuid.UUID) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listNodeIDsByUUIDs, pq.Array(uuids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueryRuns = `-- name: ListQueryRuns :many
WITH filtered AS (
    SELECT query_runs.id, query_runs.uuid, query_runs.query, query_runs.targets, query_runs.created_by, query_runs.created_at, query_runs.updated_at
    FROM query_runs
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT
    filtered.id, filtered.uuid, filtered.query, filtered.targets, filtered.created_by, filtered.created_at, filtered.updated_at,
    total.total_count,
    (SELECT count(*) FROM machine_query_results m WHERE m.run_id = filtered.id) AS host_count,
    (SELECT count(*) FROM machine_query_results m WHERE m.run_id = filtered.id AND m.status = 'pending') AS pending_count,
    (SELECT count(*) FROM machine_query_results m WHERE m.run_id = filtered.id AND m.status = 'complete') AS complete_count,
    (SELECT count(*) FROM machine_query_results m WHERE m.run_id = filtered.id AND m.status = 'error') AS error_count
FROM filtered, total
ORDER BY filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListQueryRunsParams struct {
	OffsetCount int32 `db:"offset_count" json:"offset_count"`
	LimitCount  int32 `db:"limit_count" json:"limit_count"`
}

type ListQueryRunsRow struct {
	ID            int64           `db:"id" json:"id"`
	Uuid          uuid.UUID       `db:"uuid" json:"uuid"`
	Query         string          `db:"query" json:"query"`
	Targets       json.RawMessage `db:"targets" json:"targets"`
	CreatedBy     sql.NullInt64   `db:"created_by" json:"created_by"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time       `db:"updated_at" json:"updated_at"`
	TotalCount    int64           `db:"total_count" json:"total_count"`
	HostCount     int64           `db:"host_count" json:"host_count"`
	PendingCount  int64           `db:"pending_count" json:"pending_count"`
	CompleteCount int64           `db:"complete_count" json:"complete_count"`
	ErrorCount    int64           `db:"error_count" json:"error_count"`
}

func (q *Queries) ListQueryRuns(ctx context.Context, arg ListQueryRunsParams) ([]ListQueryRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueryRuns, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueryRunsRow
	for rows.Next() {
		var i ListQueryRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Query,
			&i.Targets,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
			&i.HostCount,
			&i.PendingCount,
			&i.CompleteCount,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
