// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_schemas.sql

package repo

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteQuerySchema = `-- name: DeleteQuerySchema :exec
DELETE FROM query_schemas
WHERE source_uuid = $1 AND sql_version = $2
`

type DeleteQuerySchemaParams struct {
	SourceUuid uuid.UUID `db:"source_uuid" json:"source_uuid"`
	SqlVersion int32     `db:"sql_version" json:"sql_version"`
}

func (q *Queries) DeleteQuerySchema(ctx context.Context, arg DeleteQuerySchemaParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuerySchema, arg.SourceUuid, arg.SqlVersion)
	return err
}

const deleteQuerySchemasForSource = `-- name: DeleteQuerySchemasForSource :exec
DELETE FROM query_schemas
WHERE source_uuid = $1
`

func (q *Queries) DeleteQuerySchemasForSource(ctx context.Context, sourceUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuerySchemasForSource, sourceUuid)
	return err
}

const getQuerySchema = `-- name: GetQuerySchema :one
SELECT source_uuid, sql_version, columns, first_observed_at, last_observed_at, row_count_estimate, kind
FROM query_schemas
WHERE source_uuid = $1 AND sql_version = $2
`

type GetQuerySchemaParams struct {
	SourceUuid uuid.UUID `db:"source_uuid" json:"source_uuid"`
	SqlVersion int32     `db:"sql_version" json:"sql_version"`
}

func (q *Queries) GetQuerySchema(ctx context.Context, arg GetQuerySchemaParams) (QuerySchema, error) {
	row := q.db.QueryRowContext(ctx, getQuerySchema, arg.SourceUuid, arg.SqlVersion)
	var i QuerySchema
	err := row.Scan(
		&i.SourceUuid,
		&i.SqlVersion,
		&i.Columns,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.RowCountEstimate,
		&i.Kind,
	)
	return i, err
}

const listAllQuerySchemas = `-- name: ListAllQuerySchemas :many
SELECT source_uuid, sql_version, kind
FROM query_schemas
ORDER BY source_uuid, sql_version
`

type ListAllQuerySchemasRow struct {
	SourceUuid uuid.UUID `db:"source_uuid" json:"source_uuid"`
	SqlVersion int32     `db:"sql_version" json:"sql_version"`
	Kind       string    `db:"kind" json:"kind"`
}

func (q *Queries) ListAllQuerySchemas(ctx context.Context) ([]ListAllQuerySchemasRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllQuerySchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllQuerySchemasRow
	for rows.Next() {
		var i ListAllQuerySchemasRow
		if err := rows.Scan(&i.SourceUuid, &i.SqlVersion, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuerySchemasForSource = `-- name: ListQuerySchemasForSource :many
SELECT source_uuid, sql_version, columns, first_observed_at, last_observed_at, row_count_estimate, kind
FROM query_schemas
WHERE source_uuid = $1
ORDER BY sql_version DESC
`

func (q *Queries) ListQuerySchemasForSource(ctx context.Context, sourceUuid uuid.UUID) ([]QuerySchema, error) {
	rows, err := q.db.QueryContext(ctx, listQuerySchemasForSource, sourceUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuerySchema
	for rows.Next() {
		var i QuerySchema
		if err := rows.Scan(
			&i.SourceUuid,
			&i.SqlVersion,
			&i.Columns,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.RowCountEstimate,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuerySchemaRowCount = `-- name: UpdateQuerySchemaRowCount :exec
UPDATE query_schemas
SET row_count_estimate = $3,
    last_observed_at = now()
WHERE source_uuid = $1 AND sql_version = $2
`

type UpdateQuerySchemaRowCountParams struct {
	SourceUuid       uuid.UUID `db:"source_uuid" json:"source_uuid"`
	SqlVersion       int32     `db:"sql_version" json:"sql_version"`
	RowCountEstimate int64     `db:"row_count_estimate" json:"row_count_estimate"`
}

func (q *Queries) UpdateQuerySchemaRowCount(ctx context.Context, arg UpdateQuerySchemaRowCountParams) error {
	_, err := q.db.ExecContext(ctx, updateQuerySchemaRowCount, arg.SourceUuid, arg.SqlVersion, arg.RowCountEstimate)
	return err
}

const upsertQuerySchema = `-- name: UpsertQuerySchema :one
INSERT INTO query_schemas (source_uuid, sql_version, columns, kind)
VALUES ($1, $2, $3, $4)
ON CONFLICT (source_uuid, sql_version) DO UPDATE
SET columns = query_schemas.columns || (
        SELECT COALESCE(jsonb_agg(c), '[]'::jsonb)
        FROM jsonb_array_elements_text(EXCLUDED.columns) AS c
        WHERE NOT (query_schemas.columns ? c)
    ),
    last_observed_at = now()
RETURNING source_uuid, sql_version, columns, first_observed_at, last_observed_at, row_count_estimate, kind
`

type UpsertQuerySchemaParams struct {
	SourceUuid uuid.UUID       `db:"source_uuid" json:"source_uuid"`
	SqlVersion int32           `db:"sql_version" json:"sql_version"`
	Columns    json.RawMessage `db:"columns" json:"columns"`
	Kind       string          `db:"kind" json:"kind"`
}

// Atomically merges new columns into the persisted set. Concurrent writers
// observing different new columns for the same (source_uuid, sql_version)
// would otherwise overwrite each other's column lists; doing the merge in
// a single UPDATE keeps the additions strictly cumulative because the
// statement reads the current row value under the row lock acquired by
// ON CONFLICT DO UPDATE.
func (q *Queries) UpsertQuerySchema(ctx context.Context, arg UpsertQuerySchemaParams) (QuerySchema, error) {
	row := q.db.QueryRowContext(ctx, upsertQuerySchema,
		arg.SourceUuid,
		arg.SqlVersion,
		arg.Columns,
		arg.Kind,
	)
	var i QuerySchema
	err := row.Scan(
		&i.SourceUuid,
		&i.SqlVersion,
		&i.Columns,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.RowCountEstimate,
		&i.Kind,
	)
	return i, err
}
