// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_schemas.sql

package repo

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteQuerySchema = `-- name: DeleteQuerySchema :exec
DELETE FROM query_schemas
WHERE schedule_uuid = $1 AND sql_version = $2
`

type DeleteQuerySchemaParams struct {
	ScheduleUuid uuid.UUID `db:"schedule_uuid" json:"schedule_uuid"`
	SqlVersion   int32     `db:"sql_version" json:"sql_version"`
}

func (q *Queries) DeleteQuerySchema(ctx context.Context, arg DeleteQuerySchemaParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuerySchema, arg.ScheduleUuid, arg.SqlVersion)
	return err
}

const deleteQuerySchemasForSchedule = `-- name: DeleteQuerySchemasForSchedule :exec
DELETE FROM query_schemas
WHERE schedule_uuid = $1
`

func (q *Queries) DeleteQuerySchemasForSchedule(ctx context.Context, scheduleUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuerySchemasForSchedule, scheduleUuid)
	return err
}

const getQuerySchema = `-- name: GetQuerySchema :one
SELECT schedule_uuid, sql_version, columns, first_observed_at, last_observed_at, row_count_estimate
FROM query_schemas
WHERE schedule_uuid = $1 AND sql_version = $2
`

type GetQuerySchemaParams struct {
	ScheduleUuid uuid.UUID `db:"schedule_uuid" json:"schedule_uuid"`
	SqlVersion   int32     `db:"sql_version" json:"sql_version"`
}

func (q *Queries) GetQuerySchema(ctx context.Context, arg GetQuerySchemaParams) (QuerySchema, error) {
	row := q.db.QueryRowContext(ctx, getQuerySchema, arg.ScheduleUuid, arg.SqlVersion)
	var i QuerySchema
	err := row.Scan(
		&i.ScheduleUuid,
		&i.SqlVersion,
		&i.Columns,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.RowCountEstimate,
	)
	return i, err
}

const listAllQuerySchemas = `-- name: ListAllQuerySchemas :many
SELECT schedule_uuid, sql_version
FROM query_schemas
ORDER BY schedule_uuid, sql_version
`

type ListAllQuerySchemasRow struct {
	ScheduleUuid uuid.UUID `db:"schedule_uuid" json:"schedule_uuid"`
	SqlVersion   int32     `db:"sql_version" json:"sql_version"`
}

func (q *Queries) ListAllQuerySchemas(ctx context.Context) ([]ListAllQuerySchemasRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllQuerySchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllQuerySchemasRow
	for rows.Next() {
		var i ListAllQuerySchemasRow
		if err := rows.Scan(&i.ScheduleUuid, &i.SqlVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuerySchemasForSchedule = `-- name: ListQuerySchemasForSchedule :many
SELECT schedule_uuid, sql_version, columns, first_observed_at, last_observed_at, row_count_estimate
FROM query_schemas
WHERE schedule_uuid = $1
ORDER BY sql_version DESC
`

func (q *Queries) ListQuerySchemasForSchedule(ctx context.Context, scheduleUuid uuid.UUID) ([]QuerySchema, error) {
	rows, err := q.db.QueryContext(ctx, listQuerySchemasForSchedule, scheduleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuerySchema
	for rows.Next() {
		var i QuerySchema
		if err := rows.Scan(
			&i.ScheduleUuid,
			&i.SqlVersion,
			&i.Columns,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.RowCountEstimate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuerySchemaRowCount = `-- name: UpdateQuerySchemaRowCount :exec
UPDATE query_schemas
SET row_count_estimate = $3,
    last_observed_at = now()
WHERE schedule_uuid = $1 AND sql_version = $2
`

type UpdateQuerySchemaRowCountParams struct {
	ScheduleUuid     uuid.UUID `db:"schedule_uuid" json:"schedule_uuid"`
	SqlVersion       int32     `db:"sql_version" json:"sql_version"`
	RowCountEstimate int64     `db:"row_count_estimate" json:"row_count_estimate"`
}

func (q *Queries) UpdateQuerySchemaRowCount(ctx context.Context, arg UpdateQuerySchemaRowCountParams) error {
	_, err := q.db.ExecContext(ctx, updateQuerySchemaRowCount, arg.ScheduleUuid, arg.SqlVersion, arg.RowCountEstimate)
	return err
}

const upsertQuerySchema = `-- name: UpsertQuerySchema :one
INSERT INTO query_schemas (schedule_uuid, sql_version, columns)
VALUES ($1, $2, $3)
ON CONFLICT (schedule_uuid, sql_version) DO UPDATE
SET columns = query_schemas.columns || (
        SELECT COALESCE(jsonb_agg(c), '[]'::jsonb)
        FROM jsonb_array_elements_text(EXCLUDED.columns) AS c
        WHERE NOT (query_schemas.columns ? c)
    ),
    last_observed_at = now()
RETURNING schedule_uuid, sql_version, columns, first_observed_at, last_observed_at, row_count_estimate
`

type UpsertQuerySchemaParams struct {
	ScheduleUuid uuid.UUID       `db:"schedule_uuid" json:"schedule_uuid"`
	SqlVersion   int32           `db:"sql_version" json:"sql_version"`
	Columns      json.RawMessage `db:"columns" json:"columns"`
}

// Atomically merges new columns into the persisted set. Concurrent writers
// observing different new columns for the same (schedule_uuid, sql_version)
// would otherwise overwrite each other's column lists; doing the merge in
// a single UPDATE keeps the additions strictly cumulative because the
// statement reads the current row value under the row lock acquired by
// ON CONFLICT DO UPDATE.
func (q *Queries) UpsertQuerySchema(ctx context.Context, arg UpsertQuerySchemaParams) (QuerySchema, error) {
	row := q.db.QueryRowContext(ctx, upsertQuerySchema, arg.ScheduleUuid, arg.SqlVersion, arg.Columns)
	var i QuerySchema
	err := row.Scan(
		&i.ScheduleUuid,
		&i.SqlVersion,
		&i.Columns,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.RowCountEstimate,
	)
	return i, err
}
