// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_bindings.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRoleBinding = `-- name: CreateRoleBinding :one
INSERT INTO role_bindings (
    user_id,
    user_group_id,
    role,
    scope_group_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, uuid, user_id, user_group_id, role, scope_group_id, created_at
`

type CreateRoleBindingParams struct {
	UserID       sql.NullInt64 `db:"user_id" json:"user_id"`
	UserGroupID  sql.NullInt64 `db:"user_group_id" json:"user_group_id"`
	Role         string        `db:"role" json:"role"`
	ScopeGroupID sql.NullInt64 `db:"scope_group_id" json:"scope_group_id"`
}

func (q *Queries) CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) (RoleBinding, error) {
	row := q.db.QueryRowContext(ctx, createRoleBinding,
		arg.UserID,
		arg.UserGroupID,
		arg.Role,
		arg.ScopeGroupID,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.UserGroupID,
		&i.Role,
		&i.ScopeGroupID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoleBindingByUUID = `-- name: DeleteRoleBindingByUUID :execrows
DELETE FROM role_bindings WHERE uuid = $1
`

func (q *Queries) DeleteRoleBindingByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRoleBindingByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findRoleBinding = `-- name: FindRoleBinding :one
SELECT id, uuid, user_id, user_group_id, role, scope_group_id, created_at FROM role_bindings
WHERE user_id IS NOT DISTINCT FROM $1
  AND user_group_id IS NOT DISTINCT FROM $2
  AND role = $3
  AND scope_group_id IS NOT DISTINCT FROM $4
LIMIT 1
`

type FindRoleBindingParams struct {
	UserID       sql.NullInt64 `db:"user_id" json:"user_id"`
	UserGroupID  sql.NullInt64 `db:"user_group_id" json:"user_group_id"`
	Role         string        `db:"role" json:"role"`
	ScopeGroupID sql.NullInt64 `db:"scope_group_id" json:"scope_group_id"`
}

func (q *Queries) FindRoleBinding(ctx context.Context, arg FindRoleBindingParams) (RoleBinding, error) {
	row := q.db.QueryRowContext(ctx, findRoleBinding,
		arg.UserID,
		arg.UserGroupID,
		arg.Role,
		arg.ScopeGroupID,
	)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.UserGroupID,
		&i.Role,
		&i.ScopeGroupID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleBindingByUUID = `-- name: GetRoleBindingByUUID :one
SELECT id, uuid, user_id, user_group_id, role, scope_group_id, created_at FROM role_bindings WHERE uuid = $1
`

func (q *Queries) GetRoleBindingByUUID(ctx context.Context, argUuid uuid.UUID) (RoleBinding, error) {
	row := q.db.QueryRowContext(ctx, getRoleBindingByUUID, argUuid)
	var i RoleBinding
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.UserGroupID,
		&i.Role,
		&i.ScopeGroupID,
		&i.CreatedAt,
	)
	return i, err
}

const listAllRoleBindings = `-- name: ListAllRoleBindings :many
SELECT
    role_bindings.uuid,
    role_bindings.role,
    (CASE WHEN users.uuid IS NOT NULL THEN 'user' ELSE 'usergroup' END)::text AS subject_type,
    COALESCE(users.uuid, user_groups.uuid) AS subject_uuid,
    groups.uuid AS scope_group_uuid
FROM role_bindings
LEFT JOIN users ON users.id = role_bindings.user_id
LEFT JOIN user_groups ON user_groups.id = role_bindings.user_group_id
LEFT JOIN groups ON groups.id = role_bindings.scope_group_id
WHERE users.uuid IS NOT NULL OR user_groups.uuid IS NOT NULL
ORDER BY role_bindings.id
`

type ListAllRoleBindingsRow struct {
	Uuid           uuid.UUID     `db:"uuid" json:"uuid"`
	Role           string        `db:"role" json:"role"`
	SubjectType    string        `db:"subject_type" json:"subject_type"`
	SubjectUuid    uuid.UUID     `db:"subject_uuid" json:"subject_uuid"`
	ScopeGroupUuid uuid.NullUUID `db:"scope_group_uuid" json:"scope_group_uuid"`
}

func (q *Queries) ListAllRoleBindings(ctx context.Context) ([]ListAllRoleBindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRoleBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRoleBindingsRow
	for rows.Next() {
		var i ListAllRoleBindingsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Role,
			&i.SubjectType,
			&i.SubjectUuid,
			&i.ScopeGroupUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalRolesForUser = `-- name: ListGlobalRolesForUser :many
SELECT DISTINCT role FROM role_bindings
WHERE user_id = $1 AND scope_group_id IS NULL
`

func (q *Queries) ListGlobalRolesForUser(ctx context.Context, userID sql.NullInt64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalRolesForUserGroups = `-- name: ListGlobalRolesForUserGroups :many
SELECT DISTINCT role_bindings.role
FROM role_bindings
JOIN user_group_members ON user_group_members.user_group_id = role_bindings.user_group_id
WHERE user_group_members.user_id = $1 AND role_bindings.scope_group_id IS NULL
`

func (q *Queries) ListGlobalRolesForUserGroups(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalRolesForUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsForUser = `-- name: ListRoleBindingsForUser :many
SELECT
    role_bindings.id,
    role_bindings.uuid,
    role_bindings.role,
    role_bindings.created_at,
    groups.uuid AS scope_group_uuid,
    groups.name AS scope_group_name
FROM role_bindings
LEFT JOIN groups ON groups.id = role_bindings.scope_group_id
WHERE role_bindings.user_id = $1
ORDER BY role_bindings.created_at DESC
`

type ListRoleBindingsForUserRow struct {
	ID             int64          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	Role           string         `db:"role" json:"role"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	ScopeGroupUuid uuid.NullUUID  `db:"scope_group_uuid" json:"scope_group_uuid"`
	ScopeGroupName sql.NullString `db:"scope_group_name" json:"scope_group_name"`
}

func (q *Queries) ListRoleBindingsForUser(ctx context.Context, userID sql.NullInt64) ([]ListRoleBindingsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoleBindingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoleBindingsForUserRow
	for rows.Next() {
		var i ListRoleBindingsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Role,
			&i.CreatedAt,
			&i.ScopeGroupUuid,
			&i.ScopeGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsForUserGroup = `-- name: ListRoleBindingsForUserGroup :many
SELECT
    role_bindings.id,
    role_bindings.uuid,
    role_bindings.role,
    role_bindings.created_at,
    groups.uuid AS scope_group_uuid,
    groups.name AS scope_group_name
FROM role_bindings
LEFT JOIN groups ON groups.id = role_bindings.scope_group_id
WHERE role_bindings.user_group_id = $1
ORDER BY role_bindings.created_at DESC
`

type ListRoleBindingsForUserGroupRow struct {
	ID             int64          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	Role           string         `db:"role" json:"role"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	ScopeGroupUuid uuid.NullUUID  `db:"scope_group_uuid" json:"scope_group_uuid"`
	ScopeGroupName sql.NullString `db:"scope_group_name" json:"scope_group_name"`
}

func (q *Queries) ListRoleBindingsForUserGroup(ctx context.Context, userGroupID sql.NullInt64) ([]ListRoleBindingsForUserGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoleBindingsForUserGroup, userGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoleBindingsForUserGroupRow
	for rows.Next() {
		var i ListRoleBindingsForUserGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Role,
			&i.CreatedAt,
			&i.ScopeGroupUuid,
			&i.ScopeGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
