// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: saved_queries.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countSavedQueries = `-- name: CountSavedQueries :one
SELECT count(*)
FROM saved_queries
WHERE (visibility = 'public' OR created_by = $1)
  AND (
    $2::text = ''
    OR name ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%'
)
`

type CountSavedQueriesParams struct {
	ViewerID sql.NullInt64 `db:"viewer_id" json:"viewer_id"`
	Query    string        `db:"query" json:"query"`
}

func (q *Queries) CountSavedQueries(ctx context.Context, arg CountSavedQueriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSavedQueries, arg.ViewerID, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSavedQuery = `-- name: CreateSavedQuery :one
INSERT INTO saved_queries (
    name,
    description,
    query,
    targets,
    visibility,
    created_by
) VALUES (
    $1, $2, $3, $6::text::jsonb, $4, $5
)
RETURNING id, uuid, name, description, query, targets, visibility, created_by, created_at, updated_at
`

type CreateSavedQueryParams struct {
	Name        string        `db:"name" json:"name"`
	Description string        `db:"description" json:"description"`
	Query       string        `db:"query" json:"query"`
	Visibility  string        `db:"visibility" json:"visibility"`
	CreatedBy   sql.NullInt64 `db:"created_by" json:"created_by"`
	Targets     string        `db:"targets" json:"targets"`
}

func (q *Queries) CreateSavedQuery(ctx context.Context, arg CreateSavedQueryParams) (SavedQuery, error) {
	row := q.db.QueryRowContext(ctx, createSavedQuery,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.Visibility,
		arg.CreatedBy,
		arg.Targets,
	)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Targets,
		&i.Visibility,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSavedQueryByUUID = `-- name: DeleteSavedQueryByUUID :execrows
DELETE FROM saved_queries WHERE uuid = $1
`

func (q *Queries) DeleteSavedQueryByUUID(ctx context.Context, savedQueryUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSavedQueryByUUID, savedQueryUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSavedQueryByUUID = `-- name: GetSavedQueryByUUID :one
SELECT saved_queries.id, saved_queries.uuid, saved_queries.name, saved_queries.description, saved_queries.query, saved_queries.targets, saved_queries.visibility, saved_queries.created_by, saved_queries.created_at, saved_queries.updated_at, users.name AS creator_name
FROM saved_queries
LEFT JOIN users ON users.id = saved_queries.created_by
WHERE saved_queries.uuid = $1
`

type GetSavedQueryByUUIDRow struct {
	ID          int64           `db:"id" json:"id"`
	Uuid        uuid.UUID       `db:"uuid" json:"uuid"`
	Name        string          `db:"name" json:"name"`
	Description string          `db:"description" json:"description"`
	Query       string          `db:"query" json:"query"`
	Targets     json.RawMessage `db:"targets" json:"targets"`
	Visibility  string          `db:"visibility" json:"visibility"`
	CreatedBy   sql.NullInt64   `db:"created_by" json:"created_by"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
	CreatorName sql.NullString  `db:"creator_name" json:"creator_name"`
}

func (q *Queries) GetSavedQueryByUUID(ctx context.Context, argUuid uuid.UUID) (GetSavedQueryByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSavedQueryByUUID, argUuid)
	var i GetSavedQueryByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Targets,
		&i.Visibility,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorName,
	)
	return i, err
}

const listSavedQueries = `-- name: ListSavedQueries :many
SELECT saved_queries.id, saved_queries.uuid, saved_queries.name, saved_queries.description, saved_queries.query, saved_queries.targets, saved_queries.visibility, saved_queries.created_by, saved_queries.created_at, saved_queries.updated_at, users.name AS creator_name
FROM saved_queries
LEFT JOIN users ON users.id = saved_queries.created_by
WHERE (saved_queries.visibility = 'public' OR saved_queries.created_by = $1)
  AND (
    $2::text = ''
    OR saved_queries.name ILIKE '%' || $2::text || '%'
    OR saved_queries.description ILIKE '%' || $2::text || '%'
)
ORDER BY saved_queries.created_at DESC
LIMIT $4 OFFSET $3
`

type ListSavedQueriesParams struct {
	ViewerID    sql.NullInt64 `db:"viewer_id" json:"viewer_id"`
	Query       string        `db:"query" json:"query"`
	OffsetCount int32         `db:"offset_count" json:"offset_count"`
	LimitCount  int32         `db:"limit_count" json:"limit_count"`
}

type ListSavedQueriesRow struct {
	ID          int64           `db:"id" json:"id"`
	Uuid        uuid.UUID       `db:"uuid" json:"uuid"`
	Name        string          `db:"name" json:"name"`
	Description string          `db:"description" json:"description"`
	Query       string          `db:"query" json:"query"`
	Targets     json.RawMessage `db:"targets" json:"targets"`
	Visibility  string          `db:"visibility" json:"visibility"`
	CreatedBy   sql.NullInt64   `db:"created_by" json:"created_by"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
	CreatorName sql.NullString  `db:"creator_name" json:"creator_name"`
}

func (q *Queries) ListSavedQueries(ctx context.Context, arg ListSavedQueriesParams) ([]ListSavedQueriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSavedQueries,
		arg.ViewerID,
		arg.Query,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedQueriesRow
	for rows.Next() {
		var i ListSavedQueriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Targets,
			&i.Visibility,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedQueryByUUID = `-- name: UpdateSavedQueryByUUID :one
UPDATE saved_queries
SET
    name = $2,
    description = $3,
    query = $4,
    targets = $6::text::jsonb,
    visibility = $5,
    updated_at = now()
WHERE uuid = $1
RETURNING id, uuid, name, description, query, targets, visibility, created_by, created_at, updated_at
`

type UpdateSavedQueryByUUIDParams struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	Query       string    `db:"query" json:"query"`
	Visibility  string    `db:"visibility" json:"visibility"`
	Targets     string    `db:"targets" json:"targets"`
}

func (q *Queries) UpdateSavedQueryByUUID(ctx context.Context, arg UpdateSavedQueryByUUIDParams) (SavedQuery, error) {
	row := q.db.QueryRowContext(ctx, updateSavedQueryByUUID,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.Visibility,
		arg.Targets,
	)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Targets,
		&i.Visibility,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
