// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bumpScheduleVersion = `-- name: BumpScheduleVersion :one
UPDATE schedules
SET sql_version = sql_version + 1, updated_at = now()
WHERE id = $1
RETURNING id, uuid, name, sql_version
`

type BumpScheduleVersionRow struct {
	ID         int64     `db:"id" json:"id"`
	Uuid       uuid.UUID `db:"uuid" json:"uuid"`
	Name       string    `db:"name" json:"name"`
	SqlVersion int32     `db:"sql_version" json:"sql_version"`
}

func (q *Queries) BumpScheduleVersion(ctx context.Context, id int64) (BumpScheduleVersionRow, error) {
	row := q.db.QueryRowContext(ctx, bumpScheduleVersion, id)
	var i BumpScheduleVersionRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.SqlVersion,
	)
	return i, err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    name,
    sql,
    description,
    interval_seconds,
    platform,
    version,
    shard,
    denylist,
    removed,
    snapshot,
    enabled,
    is_system
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, uuid, name, sql, description, interval_seconds, platform, version, shard, denylist, removed, snapshot, enabled, is_system, sql_version, retention_days, created_at, updated_at
`

type CreateScheduleParams struct {
	Name            string `db:"name" json:"name"`
	Sql             string `db:"sql" json:"sql"`
	Description     string `db:"description" json:"description"`
	IntervalSeconds int32  `db:"interval_seconds" json:"interval_seconds"`
	Platform        string `db:"platform" json:"platform"`
	Version         string `db:"version" json:"version"`
	Shard           int32  `db:"shard" json:"shard"`
	Denylist        bool   `db:"denylist" json:"denylist"`
	Removed         bool   `db:"removed" json:"removed"`
	Snapshot        bool   `db:"snapshot" json:"snapshot"`
	Enabled         bool   `db:"enabled" json:"enabled"`
	IsSystem        bool   `db:"is_system" json:"is_system"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.Name,
		arg.Sql,
		arg.Description,
		arg.IntervalSeconds,
		arg.Platform,
		arg.Version,
		arg.Shard,
		arg.Denylist,
		arg.Removed,
		arg.Snapshot,
		arg.Enabled,
		arg.IsSystem,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Sql,
		&i.Description,
		&i.IntervalSeconds,
		&i.Platform,
		&i.Version,
		&i.Shard,
		&i.Denylist,
		&i.Removed,
		&i.Snapshot,
		&i.Enabled,
		&i.IsSystem,
		&i.SqlVersion,
		&i.RetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduleByUUID = `-- name: DeleteScheduleByUUID :execrows
DELETE FROM schedules WHERE uuid = $1 AND is_system = false
`

func (q *Queries) DeleteScheduleByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScheduleByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScheduleByName = `-- name: GetScheduleByName :one
SELECT id, uuid, name, sql, description, interval_seconds, platform, version, shard, denylist, removed, snapshot, enabled, is_system, sql_version, retention_days, created_at, updated_at FROM schedules WHERE name = $1
`

func (q *Queries) GetScheduleByName(ctx context.Context, name string) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByName, name)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Sql,
		&i.Description,
		&i.IntervalSeconds,
		&i.Platform,
		&i.Version,
		&i.Shard,
		&i.Denylist,
		&i.Removed,
		&i.Snapshot,
		&i.Enabled,
		&i.IsSystem,
		&i.SqlVersion,
		&i.RetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleByUUID = `-- name: GetScheduleByUUID :one
SELECT id, uuid, name, sql, description, interval_seconds, platform, version, shard, denylist, removed, snapshot, enabled, is_system, sql_version, retention_days, created_at, updated_at FROM schedules WHERE uuid = $1
`

func (q *Queries) GetScheduleByUUID(ctx context.Context, argUuid uuid.UUID) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByUUID, argUuid)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Sql,
		&i.Description,
		&i.IntervalSeconds,
		&i.Platform,
		&i.Version,
		&i.Shard,
		&i.Denylist,
		&i.Removed,
		&i.Snapshot,
		&i.Enabled,
		&i.IsSystem,
		&i.SqlVersion,
		&i.RetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT id, uuid, name, sql, description, interval_seconds, platform, version, shard, denylist, removed, snapshot, enabled, is_system, sql_version, retention_days, created_at, updated_at FROM schedules
WHERE enabled = true
ORDER BY name
LIMIT $1
`

func (q *Queries) ListEnabledSchedules(ctx context.Context, limit int32) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedules, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Sql,
			&i.Description,
			&i.IntervalSeconds,
			&i.Platform,
			&i.Version,
			&i.Shard,
			&i.Denylist,
			&i.Removed,
			&i.Snapshot,
			&i.Enabled,
			&i.IsSystem,
			&i.SqlVersion,
			&i.RetentionDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledSchedulesForNode = `-- name: ListEnabledSchedulesForNode :many
SELECT schedules.id, schedules.uuid, schedules.name, schedules.sql, schedules.description, schedules.interval_seconds, schedules.platform, schedules.version, schedules.shard, schedules.denylist, schedules.removed, schedules.snapshot, schedules.enabled, schedules.is_system, schedules.sql_version, schedules.retention_days, schedules.created_at, schedules.updated_at FROM schedules
WHERE schedules.enabled = true
  AND (
    NOT EXISTS (
        SELECT 1
        FROM schedule_groups
        WHERE schedule_groups.schedule_id = schedules.id
    )
    OR EXISTS (
        SELECT 1
        FROM schedule_groups
        JOIN group_membership ON group_membership.group_id = schedule_groups.group_id
        WHERE schedule_groups.schedule_id = schedules.id
          AND group_membership.node_id = $1
    )
  )
ORDER BY schedules.name
LIMIT $2
`

type ListEnabledSchedulesForNodeParams struct {
	NodeID     int64 `db:"node_id" json:"node_id"`
	LimitCount int32 `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListEnabledSchedulesForNode(ctx context.Context, arg ListEnabledSchedulesForNodeParams) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedulesForNode, arg.NodeID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Sql,
			&i.Description,
			&i.IntervalSeconds,
			&i.Platform,
			&i.Version,
			&i.Shard,
			&i.Denylist,
			&i.Removed,
			&i.Snapshot,
			&i.Enabled,
			&i.IsSystem,
			&i.SqlVersion,
			&i.RetentionDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRetentions = `-- name: ListScheduleRetentions :many
SELECT uuid, retention_days FROM schedules
`

type ListScheduleRetentionsRow struct {
	Uuid          uuid.UUID `db:"uuid" json:"uuid"`
	RetentionDays int32     `db:"retention_days" json:"retention_days"`
}

func (q *Queries) ListScheduleRetentions(ctx context.Context) ([]ListScheduleRetentionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleRetentions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleRetentionsRow
	for rows.Next() {
		var i ListScheduleRetentionsRow
		if err := rows.Scan(&i.Uuid, &i.RetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
WITH filtered AS (
    SELECT id, uuid, name, sql, description, interval_seconds, platform, version, shard, denylist, removed, snapshot, enabled, is_system, sql_version, retention_days, created_at, updated_at FROM schedules
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.uuid, filtered.name, filtered.sql, filtered.description, filtered.interval_seconds, filtered.platform, filtered.version, filtered.shard, filtered.denylist, filtered.removed, filtered.snapshot, filtered.enabled, filtered.is_system, filtered.sql_version, filtered.retention_days, filtered.created_at, filtered.updated_at, total.total_count
FROM filtered, total
ORDER BY filtered.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSchedulesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListSchedulesRow struct {
	ID              int64     `db:"id" json:"id"`
	Uuid            uuid.UUID `db:"uuid" json:"uuid"`
	Name            string    `db:"name" json:"name"`
	Sql             string    `db:"sql" json:"sql"`
	Description     string    `db:"description" json:"description"`
	IntervalSeconds int32     `db:"interval_seconds" json:"interval_seconds"`
	Platform        string    `db:"platform" json:"platform"`
	Version         string    `db:"version" json:"version"`
	Shard           int32     `db:"shard" json:"shard"`
	Denylist        bool      `db:"denylist" json:"denylist"`
	Removed         bool      `db:"removed" json:"removed"`
	Snapshot        bool      `db:"snapshot" json:"snapshot"`
	Enabled         bool      `db:"enabled" json:"enabled"`
	IsSystem        bool      `db:"is_system" json:"is_system"`
	SqlVersion      int32     `db:"sql_version" json:"sql_version"`
	RetentionDays   int32     `db:"retention_days" json:"retention_days"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
	TotalCount      int64     `db:"total_count" json:"total_count"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]ListSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesRow
	for rows.Next() {
		var i ListSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Sql,
			&i.Description,
			&i.IntervalSeconds,
			&i.Platform,
			&i.Version,
			&i.Shard,
			&i.Denylist,
			&i.Removed,
			&i.Snapshot,
			&i.Enabled,
			&i.IsSystem,
			&i.SqlVersion,
			&i.RetentionDays,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByNames = `-- name: ListSchedulesByNames :many
SELECT id, uuid, name, sql, description, interval_seconds, platform, version, shard, denylist, removed, snapshot, enabled, is_system, sql_version, retention_days, created_at, updated_at FROM schedules WHERE name = ANY($1::text[])
`

func (q *Queries) ListSchedulesByNames(ctx context.Context, names []string) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByNames, pq.Array(names))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Sql,
			&i.Description,
			&i.IntervalSeconds,
			&i.Platform,
			&i.Version,
			&i.Shard,
			&i.Denylist,
			&i.Removed,
			&i.Snapshot,
			&i.Enabled,
			&i.IsSystem,
			&i.SqlVersion,
			&i.RetentionDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleByUUID = `-- name: UpdateScheduleByUUID :one
UPDATE schedules SET
    name = $2,
    sql = $3,
    description = $4,
    interval_seconds = $5,
    platform = $6,
    version = $7,
    shard = $8,
    denylist = $9,
    removed = $10,
    snapshot = $11,
    enabled = $12,
    retention_days = $13,
    updated_at = now()
WHERE uuid = $1 AND is_system = false
RETURNING id, uuid, name, sql, description, interval_seconds, platform, version, shard, denylist, removed, snapshot, enabled, is_system, sql_version, retention_days, created_at, updated_at
`

type UpdateScheduleByUUIDParams struct {
	Uuid            uuid.UUID `db:"uuid" json:"uuid"`
	Name            string    `db:"name" json:"name"`
	Sql             string    `db:"sql" json:"sql"`
	Description     string    `db:"description" json:"description"`
	IntervalSeconds int32     `db:"interval_seconds" json:"interval_seconds"`
	Platform        string    `db:"platform" json:"platform"`
	Version         string    `db:"version" json:"version"`
	Shard           int32     `db:"shard" json:"shard"`
	Denylist        bool      `db:"denylist" json:"denylist"`
	Removed         bool      `db:"removed" json:"removed"`
	Snapshot        bool      `db:"snapshot" json:"snapshot"`
	Enabled         bool      `db:"enabled" json:"enabled"`
	RetentionDays   int32     `db:"retention_days" json:"retention_days"`
}

func (q *Queries) UpdateScheduleByUUID(ctx context.Context, arg UpdateScheduleByUUIDParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, updateScheduleByUUID,
		arg.Uuid,
		arg.Name,
		arg.Sql,
		arg.Description,
		arg.IntervalSeconds,
		arg.Platform,
		arg.Version,
		arg.Shard,
		arg.Denylist,
		arg.Removed,
		arg.Snapshot,
		arg.Enabled,
		arg.RetentionDays,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Sql,
		&i.Description,
		&i.IntervalSeconds,
		&i.Platform,
		&i.Version,
		&i.Shard,
		&i.Denylist,
		&i.Removed,
		&i.Snapshot,
		&i.Enabled,
		&i.IsSystem,
		&i.SqlVersion,
		&i.RetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
