// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    name,
    email,
    password_hash,
    login_type,
    disabled
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, uuid, username, name, email, password_hash, login_type, disabled, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Username     string         `db:"username" json:"username"`
	Name         string         `db:"name" json:"name"`
	Email        string         `db:"email" json:"email"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
	LoginType    string         `db:"login_type" json:"login_type"`
	Disabled     bool           `db:"disabled" json:"disabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.LoginType,
		arg.Disabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.LoginType,
		&i.Disabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByUUID = `-- name: DeleteUserByUUID :execrows
DELETE FROM users WHERE uuid = $1
`

func (q *Queries) DeleteUserByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, username, name, email, password_hash, login_type, disabled, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.LoginType,
		&i.Disabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, username, name, email, password_hash, login_type, disabled, last_login_at, created_at, updated_at FROM users WHERE uuid = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.LoginType,
		&i.Disabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, username, name, email, password_hash, login_type, disabled, last_login_at, created_at, updated_at FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.LoginType,
		&i.Disabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
WITH filtered AS (
    SELECT id, uuid, username, name, email, password_hash, login_type, disabled, last_login_at, created_at, updated_at FROM users
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.uuid, filtered.username, filtered.name, filtered.email, filtered.password_hash, filtered.login_type, filtered.disabled, filtered.last_login_at, filtered.created_at, filtered.updated_at, total.total_count
FROM filtered CROSS JOIN total
ORDER BY filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	OffsetCount int32 `db:"offset_count" json:"offset_count"`
	LimitCount  int32 `db:"limit_count" json:"limit_count"`
}

type ListUsersRow struct {
	ID           int64          `db:"id" json:"id"`
	Uuid         uuid.UUID      `db:"uuid" json:"uuid"`
	Username     string         `db:"username" json:"username"`
	Name         string         `db:"name" json:"name"`
	Email        string         `db:"email" json:"email"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
	LoginType    string         `db:"login_type" json:"login_type"`
	Disabled     bool           `db:"disabled" json:"disabled"`
	LastLoginAt  sql.NullTime   `db:"last_login_at" json:"last_login_at"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	TotalCount   int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Username,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.LoginType,
			&i.Disabled,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserLastLoginByID = `-- name: SetUserLastLoginByID :exec
UPDATE users SET
    last_login_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) SetUserLastLoginByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setUserLastLoginByID, id)
	return err
}

const setUserPasswordHashByID = `-- name: SetUserPasswordHashByID :exec
UPDATE users SET
    password_hash = $2,
    updated_at = now()
WHERE id = $1
`

type SetUserPasswordHashByIDParams struct {
	ID           int64          `db:"id" json:"id"`
	PasswordHash sql.NullString `db:"password_hash" json:"password_hash"`
}

func (q *Queries) SetUserPasswordHashByID(ctx context.Context, arg SetUserPasswordHashByIDParams) error {
	_, err := q.db.ExecContext(ctx, setUserPasswordHashByID, arg.ID, arg.PasswordHash)
	return err
}

const updateUserByUUID = `-- name: UpdateUserByUUID :one
UPDATE users SET
    name = $2,
    email = $3,
    disabled = $4,
    updated_at = now()
WHERE uuid = $1
RETURNING id, uuid, username, name, email, password_hash, login_type, disabled, last_login_at, created_at, updated_at
`

type UpdateUserByUUIDParams struct {
	Uuid     uuid.UUID `db:"uuid" json:"uuid"`
	Name     string    `db:"name" json:"name"`
	Email    string    `db:"email" json:"email"`
	Disabled bool      `db:"disabled" json:"disabled"`
}

func (q *Queries) UpdateUserByUUID(ctx context.Context, arg UpdateUserByUUIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserByUUID,
		arg.Uuid,
		arg.Name,
		arg.Email,
		arg.Disabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.LoginType,
		&i.Disabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
