// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_groups.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addUserGroupMemberManual = `-- name: AddUserGroupMemberManual :exec
INSERT INTO user_group_members (
    user_group_id,
    user_id,
    source
) VALUES (
    $1, $2, 'manual'
)
ON CONFLICT (user_group_id, user_id) DO UPDATE SET source = 'manual'
`

type AddUserGroupMemberManualParams struct {
	UserGroupID int64 `db:"user_group_id" json:"user_group_id"`
	UserID      int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) AddUserGroupMemberManual(ctx context.Context, arg AddUserGroupMemberManualParams) error {
	_, err := q.db.ExecContext(ctx, addUserGroupMemberManual, arg.UserGroupID, arg.UserID)
	return err
}

const createUserGroup = `-- name: CreateUserGroup :one
INSERT INTO user_groups (
    name,
    description,
    oidc_claim_value
) VALUES (
    $1, $2, $3
)
RETURNING id, uuid, name, description, oidc_claim_value, created_at, updated_at
`

type CreateUserGroupParams struct {
	Name           string `db:"name" json:"name"`
	Description    string `db:"description" json:"description"`
	OidcClaimValue string `db:"oidc_claim_value" json:"oidc_claim_value"`
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) (UserGroup, error) {
	row := q.db.QueryRowContext(ctx, createUserGroup, arg.Name, arg.Description, arg.OidcClaimValue)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.OidcClaimValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllOIDCMembersForUser = `-- name: DeleteAllOIDCMembersForUser :exec
DELETE FROM user_group_members
WHERE user_id = $1 AND source = 'oidc'
`

func (q *Queries) DeleteAllOIDCMembersForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllOIDCMembersForUser, userID)
	return err
}

const deleteStaleOIDCMembers = `-- name: DeleteStaleOIDCMembers :exec
DELETE FROM user_group_members
WHERE user_id = $1
  AND source = 'oidc'
  AND NOT (user_group_id = ANY($2::bigint[]))
`

type DeleteStaleOIDCMembersParams struct {
	UserID       int64   `db:"user_id" json:"user_id"`
	KeepGroupIds []int64 `db:"keep_group_ids" json:"keep_group_ids"`
}

func (q *Queries) DeleteStaleOIDCMembers(ctx context.Context, arg DeleteStaleOIDCMembersParams) error {
	_, err := q.db.ExecContext(ctx, deleteStaleOIDCMembers, arg.UserID, pq.Array(arg.KeepGroupIds))
	return err
}

const deleteUserGroupByUUID = `-- name: DeleteUserGroupByUUID :execrows
DELETE FROM user_groups WHERE uuid = $1
`

func (q *Queries) DeleteUserGroupByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserGroupByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserGroupByID = `-- name: GetUserGroupByID :one
SELECT id, uuid, name, description, oidc_claim_value, created_at, updated_at FROM user_groups WHERE id = $1
`

func (q *Queries) GetUserGroupByID(ctx context.Context, id int64) (UserGroup, error) {
	row := q.db.QueryRowContext(ctx, getUserGroupByID, id)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.OidcClaimValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGroupByUUID = `-- name: GetUserGroupByUUID :one
SELECT id, uuid, name, description, oidc_claim_value, created_at, updated_at FROM user_groups WHERE uuid = $1
`

func (q *Queries) GetUserGroupByUUID(ctx context.Context, argUuid uuid.UUID) (UserGroup, error) {
	row := q.db.QueryRowContext(ctx, getUserGroupByUUID, argUuid)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.OidcClaimValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserGroupMembers = `-- name: ListUserGroupMembers :many
SELECT
    users.id,
    users.uuid,
    users.username,
    users.name,
    users.email,
    users.login_type,
    users.disabled,
    user_group_members.source,
    user_group_members.created_at AS member_since
FROM user_group_members
JOIN users ON users.id = user_group_members.user_id
WHERE user_group_members.user_group_id = $1
ORDER BY users.username
`

type ListUserGroupMembersRow struct {
	ID          int64     `db:"id" json:"id"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Username    string    `db:"username" json:"username"`
	Name        string    `db:"name" json:"name"`
	Email       string    `db:"email" json:"email"`
	LoginType   string    `db:"login_type" json:"login_type"`
	Disabled    bool      `db:"disabled" json:"disabled"`
	Source      string    `db:"source" json:"source"`
	MemberSince time.Time `db:"member_since" json:"member_since"`
}

func (q *Queries) ListUserGroupMembers(ctx context.Context, userGroupID int64) ([]ListUserGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroupMembers, userGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupMembersRow
	for rows.Next() {
		var i ListUserGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Username,
			&i.Name,
			&i.Email,
			&i.LoginType,
			&i.Disabled,
			&i.Source,
			&i.MemberSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
WITH filtered AS (
    SELECT id, uuid, name, description, oidc_claim_value, created_at, updated_at FROM user_groups
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT
    filtered.id, filtered.uuid, filtered.name, filtered.description, filtered.oidc_claim_value, filtered.created_at, filtered.updated_at,
    total.total_count,
    count(DISTINCT user_group_members.user_id)::bigint AS member_count
FROM filtered
CROSS JOIN total
LEFT JOIN user_group_members ON user_group_members.user_group_id = filtered.id
GROUP BY
    filtered.id,
    filtered.uuid,
    filtered.name,
    filtered.description,
    filtered.oidc_claim_value,
    filtered.created_at,
    filtered.updated_at,
    total.total_count
ORDER BY filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListUserGroupsParams struct {
	OffsetCount int32 `db:"offset_count" json:"offset_count"`
	LimitCount  int32 `db:"limit_count" json:"limit_count"`
}

type ListUserGroupsRow struct {
	ID             int64     `db:"id" json:"id"`
	Uuid           uuid.UUID `db:"uuid" json:"uuid"`
	Name           string    `db:"name" json:"name"`
	Description    string    `db:"description" json:"description"`
	OidcClaimValue string    `db:"oidc_claim_value" json:"oidc_claim_value"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	TotalCount     int64     `db:"total_count" json:"total_count"`
	MemberCount    int64     `db:"member_count" json:"member_count"`
}

func (q *Queries) ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]ListUserGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.OidcClaimValue,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupsByClaimValues = `-- name: ListUserGroupsByClaimValues :many
SELECT id, uuid, name, description, oidc_claim_value, created_at, updated_at FROM user_groups
WHERE length(trim(oidc_claim_value)) > 0
  AND lower(oidc_claim_value) = ANY($1::text[])
`

func (q *Queries) ListUserGroupsByClaimValues(ctx context.Context, claimValues []string) ([]UserGroup, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroupsByClaimValues, pq.Array(claimValues))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.OidcClaimValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupsForUser = `-- name: ListUserGroupsForUser :many
SELECT user_groups.id, user_groups.uuid, user_groups.name, user_groups.description, user_groups.oidc_claim_value, user_groups.created_at, user_groups.updated_at
FROM user_groups
JOIN user_group_members ON user_group_members.user_group_id = user_groups.id
WHERE user_group_members.user_id = $1
ORDER BY user_groups.name
`

func (q *Queries) ListUserGroupsForUser(ctx context.Context, userID int64) ([]UserGroup, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.OidcClaimValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserGroupMember = `-- name: RemoveUserGroupMember :exec
DELETE FROM user_group_members
WHERE user_group_id = $1 AND user_id = $2
`

type RemoveUserGroupMemberParams struct {
	UserGroupID int64 `db:"user_group_id" json:"user_group_id"`
	UserID      int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveUserGroupMember(ctx context.Context, arg RemoveUserGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeUserGroupMember, arg.UserGroupID, arg.UserID)
	return err
}

const updateUserGroupByUUID = `-- name: UpdateUserGroupByUUID :one
UPDATE user_groups SET
    name = $2,
    description = $3,
    oidc_claim_value = $4,
    updated_at = now()
WHERE uuid = $1
RETURNING id, uuid, name, description, oidc_claim_value, created_at, updated_at
`

type UpdateUserGroupByUUIDParams struct {
	Uuid           uuid.UUID `db:"uuid" json:"uuid"`
	Name           string    `db:"name" json:"name"`
	Description    string    `db:"description" json:"description"`
	OidcClaimValue string    `db:"oidc_claim_value" json:"oidc_claim_value"`
}

func (q *Queries) UpdateUserGroupByUUID(ctx context.Context, arg UpdateUserGroupByUUIDParams) (UserGroup, error) {
	row := q.db.QueryRowContext(ctx, updateUserGroupByUUID,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.OidcClaimValue,
	)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.OidcClaimValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserGroupMemberOIDC = `-- name: UpsertUserGroupMemberOIDC :exec
INSERT INTO user_group_members (
    user_group_id,
    user_id,
    source
) VALUES (
    $1, $2, 'oidc'
)
ON CONFLICT (user_group_id, user_id) DO NOTHING
`

type UpsertUserGroupMemberOIDCParams struct {
	UserGroupID int64 `db:"user_group_id" json:"user_group_id"`
	UserID      int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) UpsertUserGroupMemberOIDC(ctx context.Context, arg UpsertUserGroupMemberOIDCParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserGroupMemberOIDC, arg.UserGroupID, arg.UserID)
	return err
}
