// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: yara.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const completeYaraScanTarget = `-- name: CompleteYaraScanTarget :exec
UPDATE yara_scan_targets
SET status = 'complete',
    error = '',
    completed_at = now(),
    updated_at = now()
WHERE scan_id = $1
  AND node_id = $2
`

type CompleteYaraScanTargetParams struct {
	ScanID int64 `db:"scan_id" json:"scan_id"`
	NodeID int64 `db:"node_id" json:"node_id"`
}

func (q *Queries) CompleteYaraScanTarget(ctx context.Context, arg CompleteYaraScanTargetParams) error {
	_, err := q.db.ExecContext(ctx, completeYaraScanTarget, arg.ScanID, arg.NodeID)
	return err
}

const createYaraScan = `-- name: CreateYaraScan :one
INSERT INTO yara_scans (
    group_id,
    paths,
    rule_urls,
    target_count
) VALUES (
    $1, $2::text[], $3::text[], $4
)
RETURNING id, uuid, group_id, paths, rule_urls, status, target_count, completed_count, match_count, error, created_at, updated_at, completed_at
`

type CreateYaraScanParams struct {
	GroupID     sql.NullInt64 `db:"group_id" json:"group_id"`
	Paths       []string      `db:"paths" json:"paths"`
	RuleUrls    []string      `db:"rule_urls" json:"rule_urls"`
	TargetCount int32         `db:"target_count" json:"target_count"`
}

func (q *Queries) CreateYaraScan(ctx context.Context, arg CreateYaraScanParams) (YaraScan, error) {
	row := q.db.QueryRowContext(ctx, createYaraScan,
		arg.GroupID,
		pq.Array(arg.Paths),
		pq.Array(arg.RuleUrls),
		arg.TargetCount,
	)
	var i YaraScan
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GroupID,
		pq.Array(&i.Paths),
		pq.Array(&i.RuleUrls),
		&i.Status,
		&i.TargetCount,
		&i.CompletedCount,
		&i.MatchCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createYaraScanTarget = `-- name: CreateYaraScanTarget :exec
INSERT INTO yara_scan_targets (
    scan_id,
    node_id
) VALUES (
    $1, $2
)
ON CONFLICT (scan_id, node_id) DO NOTHING
`

type CreateYaraScanTargetParams struct {
	ScanID int64 `db:"scan_id" json:"scan_id"`
	NodeID int64 `db:"node_id" json:"node_id"`
}

func (q *Queries) CreateYaraScanTarget(ctx context.Context, arg CreateYaraScanTargetParams) error {
	_, err := q.db.ExecContext(ctx, createYaraScanTarget, arg.ScanID, arg.NodeID)
	return err
}

const createYaraSignatureSource = `-- name: CreateYaraSignatureSource :one
INSERT INTO yara_signature_sources (
    group_id,
    url,
    label,
    enabled
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, uuid, group_id, url, label, enabled, created_at, updated_at
`

type CreateYaraSignatureSourceParams struct {
	GroupID sql.NullInt64 `db:"group_id" json:"group_id"`
	Url     string        `db:"url" json:"url"`
	Label   string        `db:"label" json:"label"`
	Enabled bool          `db:"enabled" json:"enabled"`
}

func (q *Queries) CreateYaraSignatureSource(ctx context.Context, arg CreateYaraSignatureSourceParams) (YaraSignatureSource, error) {
	row := q.db.QueryRowContext(ctx, createYaraSignatureSource,
		arg.GroupID,
		arg.Url,
		arg.Label,
		arg.Enabled,
	)
	var i YaraSignatureSource
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GroupID,
		&i.Url,
		&i.Label,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteYaraSignatureSourceByUUID = `-- name: DeleteYaraSignatureSourceByUUID :execrows
DELETE FROM yara_signature_sources WHERE uuid = $1
`

func (q *Queries) DeleteYaraSignatureSourceByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteYaraSignatureSourceByUUID, argUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const errorYaraScanTarget = `-- name: ErrorYaraScanTarget :exec
UPDATE yara_scan_targets
SET status = 'error',
    error = $3,
    completed_at = now(),
    updated_at = now()
WHERE scan_id = $1
  AND node_id = $2
`

type ErrorYaraScanTargetParams struct {
	ScanID int64  `db:"scan_id" json:"scan_id"`
	NodeID int64  `db:"node_id" json:"node_id"`
	Error  string `db:"error" json:"error"`
}

func (q *Queries) ErrorYaraScanTarget(ctx context.Context, arg ErrorYaraScanTargetParams) error {
	_, err := q.db.ExecContext(ctx, errorYaraScanTarget, arg.ScanID, arg.NodeID, arg.Error)
	return err
}

const getYaraScanByUUID = `-- name: GetYaraScanByUUID :one
SELECT
    yara_scans.id,
    yara_scans.uuid,
    yara_scans.group_id,
    groups.uuid AS group_uuid,
    groups.name AS group_name,
    yara_scans.paths,
    yara_scans.status,
    yara_scans.target_count,
    yara_scans.completed_count,
    yara_scans.match_count,
    yara_scans.error,
    yara_scans.created_at,
    yara_scans.updated_at,
    yara_scans.completed_at
FROM yara_scans
LEFT JOIN groups ON groups.id = yara_scans.group_id
WHERE yara_scans.uuid = $1
`

type GetYaraScanByUUIDRow struct {
	ID             int64          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	GroupID        sql.NullInt64  `db:"group_id" json:"group_id"`
	GroupUuid      uuid.NullUUID  `db:"group_uuid" json:"group_uuid"`
	GroupName      sql.NullString `db:"group_name" json:"group_name"`
	Paths          []string       `db:"paths" json:"paths"`
	Status         string         `db:"status" json:"status"`
	TargetCount    int32          `db:"target_count" json:"target_count"`
	CompletedCount int32          `db:"completed_count" json:"completed_count"`
	MatchCount     int32          `db:"match_count" json:"match_count"`
	Error          string         `db:"error" json:"error"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	CompletedAt    sql.NullTime   `db:"completed_at" json:"completed_at"`
}

func (q *Queries) GetYaraScanByUUID(ctx context.Context, argUuid uuid.UUID) (GetYaraScanByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getYaraScanByUUID, argUuid)
	var i GetYaraScanByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GroupID,
		&i.GroupUuid,
		&i.GroupName,
		pq.Array(&i.Paths),
		&i.Status,
		&i.TargetCount,
		&i.CompletedCount,
		&i.MatchCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getYaraSignatureSourceByUUID = `-- name: GetYaraSignatureSourceByUUID :one
SELECT id, uuid, group_id, url, label, enabled, created_at, updated_at FROM yara_signature_sources WHERE uuid = $1
`

func (q *Queries) GetYaraSignatureSourceByUUID(ctx context.Context, argUuid uuid.UUID) (YaraSignatureSource, error) {
	row := q.db.QueryRowContext(ctx, getYaraSignatureSourceByUUID, argUuid)
	var i YaraSignatureSource
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GroupID,
		&i.Url,
		&i.Label,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertYaraScanMatch = `-- name: InsertYaraScanMatch :exec
INSERT INTO yara_scan_matches (
    scan_id,
    node_id,
    path,
    matches,
    count
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertYaraScanMatchParams struct {
	ScanID  int64  `db:"scan_id" json:"scan_id"`
	NodeID  int64  `db:"node_id" json:"node_id"`
	Path    string `db:"path" json:"path"`
	Matches string `db:"matches" json:"matches"`
	Count   int32  `db:"count" json:"count"`
}

func (q *Queries) InsertYaraScanMatch(ctx context.Context, arg InsertYaraScanMatchParams) error {
	_, err := q.db.ExecContext(ctx, insertYaraScanMatch,
		arg.ScanID,
		arg.NodeID,
		arg.Path,
		arg.Matches,
		arg.Count,
	)
	return err
}

const listAllNodeIDs = `-- name: ListAllNodeIDs :many
SELECT id FROM nodes ORDER BY id
`

func (q *Queries) ListAllNodeIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAllNodeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDefaultYaraSignatureSources = `-- name: ListEnabledDefaultYaraSignatureSources :many
SELECT id, uuid, group_id, url, label, enabled, created_at, updated_at
FROM yara_signature_sources
WHERE group_id IS NULL
  AND enabled = true
ORDER BY created_at ASC
`

func (q *Queries) ListEnabledDefaultYaraSignatureSources(ctx context.Context) ([]YaraSignatureSource, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledDefaultYaraSignatureSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YaraSignatureSource
	for rows.Next() {
		var i YaraSignatureSource
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.GroupID,
			&i.Url,
			&i.Label,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledYaraSignatureSourcesByGroupID = `-- name: ListEnabledYaraSignatureSourcesByGroupID :many
SELECT id, uuid, group_id, url, label, enabled, created_at, updated_at
FROM yara_signature_sources
WHERE group_id = $1
  AND enabled = true
ORDER BY created_at ASC
`

func (q *Queries) ListEnabledYaraSignatureSourcesByGroupID(ctx context.Context, groupID sql.NullInt64) ([]YaraSignatureSource, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledYaraSignatureSourcesByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YaraSignatureSource
	for rows.Next() {
		var i YaraSignatureSource
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.GroupID,
			&i.Url,
			&i.Label,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeIDsByGroupUUID = `-- name: ListNodeIDsByGroupUUID :many
SELECT nodes.id
FROM nodes
JOIN group_membership ON group_membership.node_id = nodes.id
JOIN groups ON groups.id = group_membership.group_id
WHERE groups.uuid = $1
ORDER BY nodes.id
`

func (q *Queries) ListNodeIDsByGroupUUID(ctx context.Context, argUuid uuid.UUID) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listNodeIDsByGroupUUID, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingYaraScanTargetsForNode = `-- name: ListPendingYaraScanTargetsForNode :many
SELECT
    yara_scans.id AS scan_id,
    yara_scans.uuid AS scan_uuid,
    yara_scans.paths,
    yara_scans.rule_urls
FROM yara_scan_targets
JOIN yara_scans ON yara_scans.id = yara_scan_targets.scan_id
WHERE yara_scan_targets.node_id = $1
  AND yara_scan_targets.status = 'pending'
ORDER BY yara_scan_targets.created_at ASC
`

type ListPendingYaraScanTargetsForNodeRow struct {
	ScanID   int64     `db:"scan_id" json:"scan_id"`
	ScanUuid uuid.UUID `db:"scan_uuid" json:"scan_uuid"`
	Paths    []string  `db:"paths" json:"paths"`
	RuleUrls []string  `db:"rule_urls" json:"rule_urls"`
}

func (q *Queries) ListPendingYaraScanTargetsForNode(ctx context.Context, nodeID int64) ([]ListPendingYaraScanTargetsForNodeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingYaraScanTargetsForNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingYaraScanTargetsForNodeRow
	for rows.Next() {
		var i ListPendingYaraScanTargetsForNodeRow
		if err := rows.Scan(
			&i.ScanID,
			&i.ScanUuid,
			pq.Array(&i.Paths),
			pq.Array(&i.RuleUrls),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYaraScanMatches = `-- name: ListYaraScanMatches :many
WITH filtered AS (
    SELECT
        yara_scan_matches.id,
        nodes.uuid AS node_uuid,
        nodes.hostname,
        yara_scan_matches.path,
        yara_scan_matches.matches,
        yara_scan_matches.count,
        yara_scan_matches.created_at
    FROM yara_scan_matches
    JOIN nodes ON nodes.id = yara_scan_matches.node_id
    JOIN yara_scans ON yara_scans.id = yara_scan_matches.scan_id
    WHERE yara_scans.uuid = $3
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.node_uuid, filtered.hostname, filtered.path, filtered.matches, filtered.count, filtered.created_at, total.total_count
FROM filtered, total
ORDER BY filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListYaraScanMatchesParams struct {
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
	ScanUuid    uuid.UUID `db:"scan_uuid" json:"scan_uuid"`
}

type ListYaraScanMatchesRow struct {
	ID         int64     `db:"id" json:"id"`
	NodeUuid   uuid.UUID `db:"node_uuid" json:"node_uuid"`
	Hostname   string    `db:"hostname" json:"hostname"`
	Path       string    `db:"path" json:"path"`
	Matches    string    `db:"matches" json:"matches"`
	Count      int32     `db:"count" json:"count"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	TotalCount int64     `db:"total_count" json:"total_count"`
}

func (q *Queries) ListYaraScanMatches(ctx context.Context, arg ListYaraScanMatchesParams) ([]ListYaraScanMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listYaraScanMatches, arg.OffsetCount, arg.LimitCount, arg.ScanUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYaraScanMatchesRow
	for rows.Next() {
		var i ListYaraScanMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeUuid,
			&i.Hostname,
			&i.Path,
			&i.Matches,
			&i.Count,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYaraScanTargets = `-- name: ListYaraScanTargets :many
WITH filtered AS (
    SELECT
        nodes.uuid AS node_uuid,
        nodes.hostname,
        yara_scan_targets.status,
        yara_scan_targets.dispatched_at,
        yara_scan_targets.completed_at,
        yara_scan_targets.error,
        yara_scan_targets.created_at,
        yara_scan_targets.updated_at
    FROM yara_scan_targets
    JOIN nodes ON nodes.id = yara_scan_targets.node_id
    JOIN yara_scans ON yara_scans.id = yara_scan_targets.scan_id
    WHERE yara_scans.uuid = $3
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.node_uuid, filtered.hostname, filtered.status, filtered.dispatched_at, filtered.completed_at, filtered.error, filtered.created_at, filtered.updated_at, total.total_count
FROM filtered, total
ORDER BY filtered.created_at ASC
LIMIT $2 OFFSET $1
`

type ListYaraScanTargetsParams struct {
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
	ScanUuid    uuid.UUID `db:"scan_uuid" json:"scan_uuid"`
}

type ListYaraScanTargetsRow struct {
	NodeUuid     uuid.UUID    `db:"node_uuid" json:"node_uuid"`
	Hostname     string       `db:"hostname" json:"hostname"`
	Status       string       `db:"status" json:"status"`
	DispatchedAt sql.NullTime `db:"dispatched_at" json:"dispatched_at"`
	CompletedAt  sql.NullTime `db:"completed_at" json:"completed_at"`
	Error        string       `db:"error" json:"error"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time    `db:"updated_at" json:"updated_at"`
	TotalCount   int64        `db:"total_count" json:"total_count"`
}

func (q *Queries) ListYaraScanTargets(ctx context.Context, arg ListYaraScanTargetsParams) ([]ListYaraScanTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listYaraScanTargets, arg.OffsetCount, arg.LimitCount, arg.ScanUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYaraScanTargetsRow
	for rows.Next() {
		var i ListYaraScanTargetsRow
		if err := rows.Scan(
			&i.NodeUuid,
			&i.Hostname,
			&i.Status,
			&i.DispatchedAt,
			&i.CompletedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYaraScans = `-- name: ListYaraScans :many
WITH filtered AS (
    SELECT
        yara_scans.id,
        yara_scans.uuid,
        yara_scans.group_id,
        groups.uuid AS group_uuid,
        groups.name AS group_name,
        yara_scans.paths,
        yara_scans.status,
        yara_scans.target_count,
        yara_scans.completed_count,
        yara_scans.match_count,
        yara_scans.error,
        yara_scans.created_at,
        yara_scans.updated_at,
        yara_scans.completed_at
    FROM yara_scans
    LEFT JOIN groups ON groups.id = yara_scans.group_id
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.uuid, filtered.group_id, filtered.group_uuid, filtered.group_name, filtered.paths, filtered.status, filtered.target_count, filtered.completed_count, filtered.match_count, filtered.error, filtered.created_at, filtered.updated_at, filtered.completed_at, total.total_count
FROM filtered, total
ORDER BY filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListYaraScansParams struct {
	OffsetCount int32 `db:"offset_count" json:"offset_count"`
	LimitCount  int32 `db:"limit_count" json:"limit_count"`
}

type ListYaraScansRow struct {
	ID             int64          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	GroupID        sql.NullInt64  `db:"group_id" json:"group_id"`
	GroupUuid      uuid.NullUUID  `db:"group_uuid" json:"group_uuid"`
	GroupName      sql.NullString `db:"group_name" json:"group_name"`
	Paths          []string       `db:"paths" json:"paths"`
	Status         string         `db:"status" json:"status"`
	TargetCount    int32          `db:"target_count" json:"target_count"`
	CompletedCount int32          `db:"completed_count" json:"completed_count"`
	MatchCount     int32          `db:"match_count" json:"match_count"`
	Error          string         `db:"error" json:"error"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	CompletedAt    sql.NullTime   `db:"completed_at" json:"completed_at"`
	TotalCount     int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListYaraScans(ctx context.Context, arg ListYaraScansParams) ([]ListYaraScansRow, error) {
	rows, err := q.db.QueryContext(ctx, listYaraScans, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYaraScansRow
	for rows.Next() {
		var i ListYaraScansRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.GroupID,
			&i.GroupUuid,
			&i.GroupName,
			pq.Array(&i.Paths),
			&i.Status,
			&i.TargetCount,
			&i.CompletedCount,
			&i.MatchCount,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYaraSignatureSources = `-- name: ListYaraSignatureSources :many
WITH filtered AS (
    SELECT
        yara_signature_sources.id,
        yara_signature_sources.uuid,
        yara_signature_sources.group_id,
        groups.uuid AS group_uuid,
        groups.name AS group_name,
        yara_signature_sources.url,
        yara_signature_sources.label,
        yara_signature_sources.enabled,
        yara_signature_sources.created_at,
        yara_signature_sources.updated_at
    FROM yara_signature_sources
    LEFT JOIN groups ON groups.id = yara_signature_sources.group_id
),
total AS (
    SELECT count(*) AS total_count FROM filtered
)
SELECT filtered.id, filtered.uuid, filtered.group_id, filtered.group_uuid, filtered.group_name, filtered.url, filtered.label, filtered.enabled, filtered.created_at, filtered.updated_at, total.total_count
FROM filtered, total
ORDER BY filtered.group_name NULLS FIRST, filtered.created_at DESC
LIMIT $2 OFFSET $1
`

type ListYaraSignatureSourcesParams struct {
	OffsetCount int32 `db:"offset_count" json:"offset_count"`
	LimitCount  int32 `db:"limit_count" json:"limit_count"`
}

type ListYaraSignatureSourcesRow struct {
	ID         int64          `db:"id" json:"id"`
	Uuid       uuid.UUID      `db:"uuid" json:"uuid"`
	GroupID    sql.NullInt64  `db:"group_id" json:"group_id"`
	GroupUuid  uuid.NullUUID  `db:"group_uuid" json:"group_uuid"`
	GroupName  sql.NullString `db:"group_name" json:"group_name"`
	Url        string         `db:"url" json:"url"`
	Label      string         `db:"label" json:"label"`
	Enabled    bool           `db:"enabled" json:"enabled"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time      `db:"updated_at" json:"updated_at"`
	TotalCount int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListYaraSignatureSources(ctx context.Context, arg ListYaraSignatureSourcesParams) ([]ListYaraSignatureSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listYaraSignatureSources, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYaraSignatureSourcesRow
	for rows.Next() {
		var i ListYaraSignatureSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.GroupID,
			&i.GroupUuid,
			&i.GroupName,
			&i.Url,
			&i.Label,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markYaraScanRunning = `-- name: MarkYaraScanRunning :exec
UPDATE yara_scans
SET status = 'running',
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
`

func (q *Queries) MarkYaraScanRunning(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markYaraScanRunning, id)
	return err
}

const markYaraScanTargetDispatched = `-- name: MarkYaraScanTargetDispatched :exec
UPDATE yara_scan_targets
SET status = 'dispatched',
    dispatched_at = COALESCE(dispatched_at, now()),
    updated_at = now()
WHERE scan_id = $1
  AND node_id = $2
  AND status = 'pending'
`

type MarkYaraScanTargetDispatchedParams struct {
	ScanID int64 `db:"scan_id" json:"scan_id"`
	NodeID int64 `db:"node_id" json:"node_id"`
}

func (q *Queries) MarkYaraScanTargetDispatched(ctx context.Context, arg MarkYaraScanTargetDispatchedParams) error {
	_, err := q.db.ExecContext(ctx, markYaraScanTargetDispatched, arg.ScanID, arg.NodeID)
	return err
}

const refreshYaraScanStats = `-- name: RefreshYaraScanStats :exec
WITH stats AS (
    SELECT
        yara_scan_targets.scan_id,
        count(*)::integer AS target_count,
        count(*) FILTER (WHERE status IN ('complete', 'error'))::integer AS completed_count,
        count(*) FILTER (WHERE status = 'error')::integer AS error_count
    FROM yara_scan_targets
    WHERE yara_scan_targets.scan_id = $1
    GROUP BY yara_scan_targets.scan_id
),
matches AS (
    SELECT yara_scan_matches.scan_id, count(*)::integer AS match_count
    FROM yara_scan_matches
    WHERE yara_scan_matches.scan_id = $1
    GROUP BY yara_scan_matches.scan_id
),
first_error AS (
    SELECT scan_id, error
    FROM yara_scan_targets
    WHERE scan_id = $1
      AND status = 'error'
      AND length(trim(error)) > 0
    ORDER BY completed_at ASC NULLS LAST, updated_at ASC
    LIMIT 1
)
UPDATE yara_scans
SET target_count = stats.target_count,
    completed_count = stats.completed_count,
    match_count = COALESCE(matches.match_count, 0),
    status = CASE
        WHEN stats.completed_count = 0 AND yara_scans.status = 'pending' THEN 'pending'
        WHEN stats.completed_count < stats.target_count THEN 'running'
        WHEN stats.error_count = 0 THEN 'complete'
        WHEN stats.error_count = stats.target_count THEN 'error'
        ELSE 'partial'
    END,
    error = CASE
        WHEN stats.error_count = 0 THEN ''
        WHEN stats.error_count = 1 THEN first_error.error
        ELSE stats.error_count::text || ' YARA scan targets failed; first error: ' || COALESCE(first_error.error, 'unknown error')
    END,
    completed_at = CASE
        WHEN stats.completed_count = stats.target_count THEN COALESCE(yara_scans.completed_at, now())
        ELSE NULL
    END,
    updated_at = now()
FROM stats
LEFT JOIN matches ON matches.scan_id = stats.scan_id
LEFT JOIN first_error ON first_error.scan_id = stats.scan_id
WHERE yara_scans.id = stats.scan_id
`

func (q *Queries) RefreshYaraScanStats(ctx context.Context, scanID int64) error {
	_, err := q.db.ExecContext(ctx, refreshYaraScanStats, scanID)
	return err
}

const timeoutStaleYaraScanTargets = `-- name: TimeoutStaleYaraScanTargets :many
UPDATE yara_scan_targets
SET status = 'error',
    error = CASE
        WHEN status = 'pending' THEN 'YARA scan was not dispatched before timeout'
        ELSE 'YARA scan did not report results before timeout'
    END,
    completed_at = now(),
    updated_at = now()
WHERE status IN ('pending', 'dispatched')
  AND COALESCE(dispatched_at, created_at) < now() - $1::text::interval
RETURNING scan_id
`

func (q *Queries) TimeoutStaleYaraScanTargets(ctx context.Context, timeout string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, timeoutStaleYaraScanTargets, timeout)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var scan_id int64
		if err := rows.Scan(&scan_id); err != nil {
			return nil, err
		}
		items = append(items, scan_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateYaraSignatureSourceByUUID = `-- name: UpdateYaraSignatureSourceByUUID :one
UPDATE yara_signature_sources SET
    group_id = $2,
    url = $3,
    label = $4,
    enabled = $5,
    updated_at = now()
WHERE uuid = $1
RETURNING id, uuid, group_id, url, label, enabled, created_at, updated_at
`

type UpdateYaraSignatureSourceByUUIDParams struct {
	Uuid    uuid.UUID     `db:"uuid" json:"uuid"`
	GroupID sql.NullInt64 `db:"group_id" json:"group_id"`
	Url     string        `db:"url" json:"url"`
	Label   string        `db:"label" json:"label"`
	Enabled bool          `db:"enabled" json:"enabled"`
}

func (q *Queries) UpdateYaraSignatureSourceByUUID(ctx context.Context, arg UpdateYaraSignatureSourceByUUIDParams) (YaraSignatureSource, error) {
	row := q.db.QueryRowContext(ctx, updateYaraSignatureSourceByUUID,
		arg.Uuid,
		arg.GroupID,
		arg.Url,
		arg.Label,
		arg.Enabled,
	)
	var i YaraSignatureSource
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GroupID,
		&i.Url,
		&i.Label,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
