services:
  watcher:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1323:1323"
    environment:
      - WATCHER_APP__ROOT_URL=https://localhost:1323
      - WATCHER_APP__USE_TLS=true
      - WATCHER_APP__HTTP_TLS_CERT=/etc/watcher/tls/server_cert.pem
      - WATCHER_APP__HTTP_TLS_KEY=/etc/watcher/tls/server_key.pem
      - WATCHER_APP__ENROLLMENT_KEY=secret-key
      - WATCHER_APP__POLICY_UPDATE_INTERVAL=5s
      - WATCHER_DB__HOST=postgres
      - WATCHER_DB__PORT=5432
      - WATCHER_DB__USER=watcher
      - WATCHER_DB__PASSWORD=watcher
      - WATCHER_DB__DBNAME=watcher
    volumes:
      - "./testdata/server_cert.pem:/etc/watcher/tls/server_cert.pem:ro,z"
      - "./testdata/server_key.pem:/etc/watcher/tls/server_key.pem:ro,Z"
      - "./data:/app/data:Z"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      default:
        aliases:
          - watcher

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=watcher
      - POSTGRES_USER=watcher
      - POSTGRES_DB=watcher
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U watcher"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - type: volume
        source: watcher-db-data
        target: /var/lib/postgresql

  osquery:
    build:
      context: ./testdata
      dockerfile: Dockerfile.osquery
    depends_on:
      watcher:
        condition: service_started
    volumes:
      - "./testdata/server_cert.pem:/etc/osquery-tls/certs/server.pem:ro,z"
      - "osquery-db:/var/osquery/osquery.db"
    environment:
      - ENROLLMENT_SECRET=secret-key
    command:
      [
        "osqueryd",
        "--logger_plugin=tls",
        "--config_plugin=tls",
        "--enroll_tls_endpoint=/api/v1/osquery/enroll",
        "--config_tls_endpoint=/api/v1/osquery/config",
        "--logger_tls_endpoint=/api/v1/osquery/logger",
        "--disable_distributed=false",
        "--distributed_plugin=tls",
        "--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read",
        "--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write",
        "--distributed_interval=5",
        "--tls_hostname=watcher:1323",
        "--tls_server_certs=/etc/osquery-tls/certs/server.pem",
        "--disable_enrollment=false",
        "--enroll_secret_env=ENROLLMENT_SECRET",
        "--config_refresh=30",
      ]
volumes:
  watcher-db-data:
  osquery-db:
