<script lang="ts">
  import { onMount } from 'svelte'
  import {
    fetchEnrollmentSecrets,
    generateAnonymousEnrollmentSecret,
    revokeEnrollmentSecret,
    fetchEnrollmentSecretMachines,
    type EnrollmentSecret,
    type Machine
  } from '$lib/api'
  import { me, canFrom } from '$lib/auth'
  import { formatTimestamp, isOnline, machineHostname } from '$lib/util'
  import ErrorMessage from '$lib/components/ErrorMessage.svelte'
  import Spinner from '$lib/components/Spinner.svelte'
  import ActionsMenu from '$lib/components/ActionsMenu.svelte'
  import ConfirmDialog from '$lib/components/ConfirmDialog.svelte'
  import CopyableId from '$lib/components/CopyableId.svelte'
  import Plus from '@lucide/svelte/icons/plus'

  let secrets = $state<EnrollmentSecret[]>([])
  let loading = $state(true)
  let error = $state('')

  let revokeOpen = $state(false)
  let selected = $state<EnrollmentSecret | null>(null)
  let revoking = $state(false)

  let machinesDialog = $state<HTMLDialogElement>()
  let machinesFor = $state<EnrollmentSecret | null>(null)
  let machines = $state<Machine[]>([])
  let machinesLoading = $state(false)

  let generating = $state(false)

  const hasActiveAnonymous = $derived(secrets.some((s) => s.type === 'anonymous' && !s.revoked_at))
  const canGenerate = $derived(canFrom($me, 'setting', 'update'))

  type Status = { label: string; variant: 'success' | 'danger' }

  function statusOf(secret: EnrollmentSecret): Status {
    if (secret.revoked_at) return { label: 'Revoked', variant: 'danger' }
    return { label: 'Active', variant: 'success' }
  }

  function machineStatusLabel(machine: Machine): string {
    if (!machine.last_seen_at && !machine.enrolled_at) return 'unknown'
    return isOnline(machine) ? 'active' : 'offline'
  }

  function machineStatusVariant(machine: Machine): 'success' | 'danger' | 'warning' {
    const label = machineStatusLabel(machine)
    if (label === 'active') return 'success'
    if (label === 'offline') return 'danger'
    return 'warning'
  }

  onMount(() => {
    void load()
  })

  async function load() {
    loading = true
    error = ''
    try {
      secrets = (await fetchEnrollmentSecrets()).enrollment_secrets || []
    } catch (err) {
      error = (err as Error).message || 'Failed to load enrollment secrets'
    } finally {
      loading = false
    }
  }

  async function generate() {
    generating = true
    error = ''
    try {
      await generateAnonymousEnrollmentSecret()
      await load()
    } catch (err) {
      error = (err as Error).message || 'Failed to generate enrollment secret'
    } finally {
      generating = false
    }
  }

  function confirmRevoke(secret: EnrollmentSecret) {
    selected = secret
    revokeOpen = true
  }

  async function doRevoke() {
    if (!selected) return
    revoking = true
    try {
      await revokeEnrollmentSecret(selected.uuid)
      revokeOpen = false
      selected = null
      await load()
    } catch (err) {
      error = (err as Error).message || 'Failed to revoke enrollment secret'
    } finally {
      revoking = false
    }
  }

  async function openMachines(secret: EnrollmentSecret) {
    machinesFor = secret
    machines = []
    machinesLoading = true
    machinesDialog?.showModal()
    try {
      machines = (await fetchEnrollmentSecretMachines(secret.uuid)).machines || []
    } catch (err) {
      error = (err as Error).message || 'Failed to load machines'
      machinesDialog?.close()
    } finally {
      machinesLoading = false
    }
  }
</script>

<section class="vstack gap-4">
  <header class="hstack justify-between mb-4">
    <div>
      <h1 class="mb-2">Enrollment secrets</h1>
      <p class="text-light">
        Permanent, tracked secrets machines use to enroll. Revoke one to block future enrollments
        with it; machines already enrolled keep working until their host is deleted.
      </p>
    </div>
    {#if canGenerate && !hasActiveAnonymous}
      <button type="button" class="gap-1" onclick={generate} disabled={generating}>
        <Plus size={16} aria-hidden="true" />
        {generating ? 'Generating...' : 'Generate anonymous secret'}
      </button>
    {/if}
  </header>

  <ErrorMessage message={error} onClose={() => (error = '')} />

  {#if loading}
    <Spinner fill />
  {:else}
    <div class="table">
      <table>
        <thead>
          <tr>
            <th>Secret ID</th>
            <th>Type</th>
            <th>Generated by</th>
            <th class="align-right">Machines</th>
            <th>Status</th>
            <th>Created</th>
            <th class="align-right"><span class="sr-only">Actions</span></th>
          </tr>
        </thead>
        <tbody>
          {#each secrets as secret}
            {@const status = statusOf(secret)}
            <tr>
              <td><CopyableId value={secret.secret_id} label="Secret ID" /></td>
              <td><span class="badge outline">{secret.type}</span></td>
              <td>{secret.generated_by || (secret.type === 'anonymous' ? 'System' : '—')}</td>
              <td class="align-right">
                {#if secret.machine_count > 0}
                  <button type="button" class="cell-link" onclick={() => openMachines(secret)}>
                    {secret.machine_count}
                  </button>
                {:else}
                  <span class="text-light">0</span>
                {/if}
              </td>
              <td><span class="badge" data-variant={status.variant}>{status.label}</span></td>
              <td>{formatTimestamp(secret.created_at)}</td>
              <td class="align-right">
                {#if secret.revoked_at}
                  <span class="text-light">—</span>
                {:else}
                  <ActionsMenu label={`Actions for secret ${secret.secret_id}`}>
                    <button role="menuitem" type="button" onclick={() => confirmRevoke(secret)}>
                      Revoke
                    </button>
                  </ActionsMenu>
                {/if}
              </td>
            </tr>
          {:else}
            <tr><td colspan={7} class="align-center text-light">No enrollment secrets yet</td></tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</section>

<ConfirmDialog
  bind:open={revokeOpen}
  title="Revoke enrollment secret"
  message="Revoke this secret? New machines will no longer be able to enroll with it. Machines already enrolled keep working until you delete them individually."
  confirmLabel="Revoke"
  confirmingLabel="Revoking..."
  confirming={revoking}
  onConfirm={doRevoke}
  onCancel={() => (selected = null)}
/>

<dialog bind:this={machinesDialog} class="machines-dialog" closedby="any">
  <header>
    <h2>Machines using this secret</h2>
    {#if machinesFor}
      <p class="text-light"><CopyableId value={machinesFor.secret_id} label="Secret ID" /></p>
    {/if}
  </header>
  {#if machinesLoading}
    <Spinner fill />
  {:else}
    <div class="table">
      <table>
        <thead>
          <tr>
            <th>Host</th>
            <th>Platform</th>
            <th>Status</th>
            <th>Last seen</th>
          </tr>
        </thead>
        <tbody>
          {#each machines as machine}
            <tr>
              <td><a href={`/machines/${machine.uuid}`}>{machineHostname(machine)}</a></td>
              <td>{machine.platform || '—'}</td>
              <td>
                <span class="badge" data-variant={machineStatusVariant(machine)}>
                  {machineStatusLabel(machine)}
                </span>
              </td>
              <td>{machine.last_seen_at ? formatTimestamp(machine.last_seen_at) : 'Never'}</td>
            </tr>
          {:else}
            <tr><td colspan={4} class="align-center text-light">No machines</td></tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
  <footer>
    <button type="button" class="outline" onclick={() => machinesDialog?.close()}>Close</button>
  </footer>
</dialog>

<style>
  .machines-dialog {
    width: min(48rem, 94vw);
  }
</style>
