FROM debian:bookworm

RUN apt update && apt install -y wget

RUN wget https://pkg.osquery.io/deb/osquery_5.16.0-1.linux_amd64.deb
RUN dpkg -i osquery_5.16.0-1.linux_amd64.deb

RUN mkdir -p /etc/osquery-tls/certs
RUN chmod 755 /etc/osquery-tls/certs
